{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"orders_export_1\",\"orders_export_2\",\"orders_export_3\",\"orders_export_4\",\"orders_export_5\",\"orders_export_6\",\"orders_export_7\",\"orders_export\",\"metrics\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.130.930.0 (24.06)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "orders_export_7",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Csv.Document(File.Contents(\"C:\\Users\\Nedko\\Desktop\\orders_export\\orders_export_7.csv\"),[Delimiter=\",\", Columns=74, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Name\", type text}, {\"Financial Status\", type text}, {\"Paid at\", type datetimezone}, {\"Fulfillment Status\", type text}, {\"Fulfilled at\", type datetimezone}, {\"Accepts Marketing\", type text}, {\"Currency\", type text}, {\"Subtotal\", type text}, {\"Shipping\", type text}, {\"Taxes\", type text}, {\"Total\", type text}, {\"Discount Code\", type text}, {\"Discount Amount\", type text}, {\"Shipping Method\", type text}, {\"Created at\", type datetimezone}, {\"Lineitem quantity\", Int64.Type}, {\"Lineitem name\", type text}, {\"Lineitem price\", type text}, {\"Lineitem compare at price\", type text}, {\"Lineitem sku\", type text}, {\"Lineitem requires shipping\", type logical}, {\"Lineitem taxable\", type logical}, {\"Lineitem fulfillment status\", type text}, {\"Billing Name\", type text}, {\"Billing Street\", type text}, {\"Billing Address1\", type text}, {\"Billing Address2\", type text}, {\"Billing Company\", type text}, {\"Billing City\", type text}, {\"Billing Zip\", type text}, {\"Billing Province\", type text}, {\"Billing Country\", type text}, {\"Billing Phone\", type text}, {\"Shipping Name\", type text}, {\"Shipping Street\", type text}, {\"Shipping Address1\", type text}, {\"Shipping Address2\", type text}, {\"Shipping Company\", type text}, {\"Shipping City\", type text}, {\"Shipping Zip\", type text}, {\"Shipping Province\", type text}, {\"Shipping Country\", type text}, {\"Shipping Phone\", type text}, {\"Notes\", type text}, {\"Note Attributes\", type text}, {\"Cancelled at\", type text}, {\"Payment Method\", type text}, {\"Payment Reference\", type text}, {\"Refunded Amount\", type text}, {\"Vendor\", type text}, {\"Id\", Int64.Type}, {\"Tags\", type text}, {\"Risk Level\", type text}, {\"Source\", type text}, {\"Lineitem discount\", type text}, {\"Tax 1 Name\", type text}, {\"Tax 1 Value\", type text}, {\"Tax 2 Name\", type text}, {\"Tax 2 Value\", type text}, {\"Tax 3 Name\", type text}, {\"Tax 3 Value\", type text}, {\"Tax 4 Name\", type text}, {\"Tax 4 Value\", type text}, {\"Tax 5 Name\", type text}, {\"Tax 5 Value\", type text}, {\"Phone\", Int64.Type}, {\"Receipt Number\", type text}, {\"Duties\", type text}, {\"Billing Province Name\", type text}, {\"Shipping Province Name\", type text}, {\"Payment ID\", type text}, {\"Payment Terms Name\", type text}, {\"Next Payment Due At\", type text}, {\"Payment References\", type text}})",
          "in",
          "    #\"Changed Type\""
        ],
        "kind": "m",
        "lineageTag": "eaa4b96a-0399-485e-b880-29f27534764b"
      },
      {
        "name": "orders_export_6",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Csv.Document(File.Contents(\"C:\\Users\\Nedko\\Desktop\\orders_export\\orders_export_6.csv\"),[Delimiter=\",\", Columns=74, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Name\", type text}, {\"Financial Status\", type text}, {\"Paid at\", type datetimezone}, {\"Fulfillment Status\", type text}, {\"Fulfilled at\", type datetimezone}, {\"Accepts Marketing\", type text}, {\"Currency\", type text}, {\"Subtotal\", type text}, {\"Shipping\", type text}, {\"Taxes\", type text}, {\"Total\", type text}, {\"Discount Code\", type text}, {\"Discount Amount\", type text}, {\"Shipping Method\", type text}, {\"Created at\", type datetimezone}, {\"Lineitem quantity\", Int64.Type}, {\"Lineitem name\", type text}, {\"Lineitem price\", type text}, {\"Lineitem compare at price\", type text}, {\"Lineitem sku\", type text}, {\"Lineitem requires shipping\", type logical}, {\"Lineitem taxable\", type logical}, {\"Lineitem fulfillment status\", type text}, {\"Billing Name\", type text}, {\"Billing Street\", type text}, {\"Billing Address1\", type text}, {\"Billing Address2\", type text}, {\"Billing Company\", type text}, {\"Billing City\", type text}, {\"Billing Zip\", type text}, {\"Billing Province\", type text}, {\"Billing Country\", type text}, {\"Billing Phone\", type text}, {\"Shipping Name\", type text}, {\"Shipping Street\", type text}, {\"Shipping Address1\", type text}, {\"Shipping Address2\", type text}, {\"Shipping Company\", type text}, {\"Shipping City\", type text}, {\"Shipping Zip\", type text}, {\"Shipping Province\", type text}, {\"Shipping Country\", type text}, {\"Shipping Phone\", type text}, {\"Notes\", type text}, {\"Note Attributes\", type text}, {\"Cancelled at\", type text}, {\"Payment Method\", type text}, {\"Payment Reference\", type text}, {\"Refunded Amount\", type text}, {\"Vendor\", type text}, {\"Id\", Int64.Type}, {\"Tags\", type text}, {\"Risk Level\", type text}, {\"Source\", type text}, {\"Lineitem discount\", type text}, {\"Tax 1 Name\", type text}, {\"Tax 1 Value\", type text}, {\"Tax 2 Name\", type text}, {\"Tax 2 Value\", type text}, {\"Tax 3 Name\", type text}, {\"Tax 3 Value\", type text}, {\"Tax 4 Name\", type text}, {\"Tax 4 Value\", type text}, {\"Tax 5 Name\", type text}, {\"Tax 5 Value\", type text}, {\"Phone\", Int64.Type}, {\"Receipt Number\", type text}, {\"Duties\", type text}, {\"Billing Province Name\", type text}, {\"Shipping Province Name\", type text}, {\"Payment ID\", type text}, {\"Payment Terms Name\", type text}, {\"Next Payment Due At\", type text}, {\"Payment References\", type text}})",
          "in",
          "    #\"Changed Type\""
        ],
        "kind": "m",
        "lineageTag": "9e308136-c4be-40f7-bc19-d3a8eaff9a8d"
      },
      {
        "name": "orders_export_5",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Csv.Document(File.Contents(\"C:\\Users\\Nedko\\Desktop\\orders_export\\orders_export_5.csv\"),[Delimiter=\",\", Columns=74, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Name\", type text}, {\"Financial Status\", type text}, {\"Paid at\", type datetimezone}, {\"Fulfillment Status\", type text}, {\"Fulfilled at\", type datetimezone}, {\"Accepts Marketing\", type text}, {\"Currency\", type text}, {\"Subtotal\", type text}, {\"Shipping\", type text}, {\"Taxes\", type text}, {\"Total\", type text}, {\"Discount Code\", type text}, {\"Discount Amount\", type text}, {\"Shipping Method\", type text}, {\"Created at\", type datetimezone}, {\"Lineitem quantity\", Int64.Type}, {\"Lineitem name\", type text}, {\"Lineitem price\", type text}, {\"Lineitem compare at price\", type text}, {\"Lineitem sku\", type text}, {\"Lineitem requires shipping\", type logical}, {\"Lineitem taxable\", type logical}, {\"Lineitem fulfillment status\", type text}, {\"Billing Name\", type text}, {\"Billing Street\", type text}, {\"Billing Address1\", type text}, {\"Billing Address2\", type text}, {\"Billing Company\", type text}, {\"Billing City\", type text}, {\"Billing Zip\", type text}, {\"Billing Province\", type text}, {\"Billing Country\", type text}, {\"Billing Phone\", type text}, {\"Shipping Name\", type text}, {\"Shipping Street\", type text}, {\"Shipping Address1\", type text}, {\"Shipping Address2\", type text}, {\"Shipping Company\", type text}, {\"Shipping City\", type text}, {\"Shipping Zip\", type text}, {\"Shipping Province\", type text}, {\"Shipping Country\", type text}, {\"Shipping Phone\", type text}, {\"Notes\", type text}, {\"Note Attributes\", type text}, {\"Cancelled at\", type text}, {\"Payment Method\", type text}, {\"Payment Reference\", type text}, {\"Refunded Amount\", type text}, {\"Vendor\", type text}, {\"Id\", Int64.Type}, {\"Tags\", type text}, {\"Risk Level\", type text}, {\"Source\", type text}, {\"Lineitem discount\", type text}, {\"Tax 1 Name\", type text}, {\"Tax 1 Value\", type text}, {\"Tax 2 Name\", type text}, {\"Tax 2 Value\", type text}, {\"Tax 3 Name\", type text}, {\"Tax 3 Value\", type text}, {\"Tax 4 Name\", type text}, {\"Tax 4 Value\", type text}, {\"Tax 5 Name\", type text}, {\"Tax 5 Value\", type text}, {\"Phone\", Int64.Type}, {\"Receipt Number\", type text}, {\"Duties\", type text}, {\"Billing Province Name\", type text}, {\"Shipping Province Name\", type text}, {\"Payment ID\", type text}, {\"Payment Terms Name\", type text}, {\"Next Payment Due At\", type text}, {\"Payment References\", type text}})",
          "in",
          "    #\"Changed Type\""
        ],
        "kind": "m",
        "lineageTag": "ecdeddee-8761-4457-8038-e60d1de0dfde"
      },
      {
        "name": "orders_export_4",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Csv.Document(File.Contents(\"C:\\Users\\Nedko\\Desktop\\orders_export\\orders_export_4.csv\"),[Delimiter=\",\", Columns=74, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Name\", type text}, {\"Financial Status\", type text}, {\"Paid at\", type datetimezone}, {\"Fulfillment Status\", type text}, {\"Fulfilled at\", type datetimezone}, {\"Accepts Marketing\", type text}, {\"Currency\", type text}, {\"Subtotal\", type text}, {\"Shipping\", type text}, {\"Taxes\", type text}, {\"Total\", type text}, {\"Discount Code\", type text}, {\"Discount Amount\", type text}, {\"Shipping Method\", type text}, {\"Created at\", type datetimezone}, {\"Lineitem quantity\", Int64.Type}, {\"Lineitem name\", type text}, {\"Lineitem price\", type text}, {\"Lineitem compare at price\", type text}, {\"Lineitem sku\", type text}, {\"Lineitem requires shipping\", type logical}, {\"Lineitem taxable\", type logical}, {\"Lineitem fulfillment status\", type text}, {\"Billing Name\", type text}, {\"Billing Street\", type text}, {\"Billing Address1\", type text}, {\"Billing Address2\", type text}, {\"Billing Company\", type text}, {\"Billing City\", type text}, {\"Billing Zip\", type text}, {\"Billing Province\", type text}, {\"Billing Country\", type text}, {\"Billing Phone\", type text}, {\"Shipping Name\", type text}, {\"Shipping Street\", type text}, {\"Shipping Address1\", type text}, {\"Shipping Address2\", type text}, {\"Shipping Company\", type text}, {\"Shipping City\", type text}, {\"Shipping Zip\", type text}, {\"Shipping Province\", type text}, {\"Shipping Country\", type text}, {\"Shipping Phone\", type text}, {\"Notes\", type text}, {\"Note Attributes\", type text}, {\"Cancelled at\", type datetimezone}, {\"Payment Method\", type text}, {\"Payment Reference\", type text}, {\"Refunded Amount\", type text}, {\"Vendor\", type text}, {\"Id\", Int64.Type}, {\"Tags\", type text}, {\"Risk Level\", type text}, {\"Source\", type text}, {\"Lineitem discount\", type text}, {\"Tax 1 Name\", type text}, {\"Tax 1 Value\", type text}, {\"Tax 2 Name\", type text}, {\"Tax 2 Value\", type text}, {\"Tax 3 Name\", type text}, {\"Tax 3 Value\", type text}, {\"Tax 4 Name\", type text}, {\"Tax 4 Value\", type text}, {\"Tax 5 Name\", type text}, {\"Tax 5 Value\", type text}, {\"Phone\", Int64.Type}, {\"Receipt Number\", type text}, {\"Duties\", type text}, {\"Billing Province Name\", type text}, {\"Shipping Province Name\", type text}, {\"Payment ID\", type text}, {\"Payment Terms Name\", type text}, {\"Next Payment Due At\", type text}, {\"Payment References\", type text}})",
          "in",
          "    #\"Changed Type\""
        ],
        "kind": "m",
        "lineageTag": "e7b213ac-3768-400f-8ba6-af7b7ae1c6be"
      },
      {
        "name": "orders_export_3",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Csv.Document(File.Contents(\"C:\\Users\\Nedko\\Desktop\\orders_export\\orders_export_3.csv\"),[Delimiter=\",\", Columns=74, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Name\", type text}, {\"Financial Status\", type text}, {\"Paid at\", type datetimezone}, {\"Fulfillment Status\", type text}, {\"Fulfilled at\", type datetimezone}, {\"Accepts Marketing\", type text}, {\"Currency\", type text}, {\"Subtotal\", type text}, {\"Shipping\", type text}, {\"Taxes\", type text}, {\"Total\", type text}, {\"Discount Code\", type text}, {\"Discount Amount\", type text}, {\"Shipping Method\", type text}, {\"Created at\", type datetimezone}, {\"Lineitem quantity\", Int64.Type}, {\"Lineitem name\", type text}, {\"Lineitem price\", type text}, {\"Lineitem compare at price\", type text}, {\"Lineitem sku\", type text}, {\"Lineitem requires shipping\", type logical}, {\"Lineitem taxable\", type logical}, {\"Lineitem fulfillment status\", type text}, {\"Billing Name\", type text}, {\"Billing Street\", type text}, {\"Billing Address1\", type text}, {\"Billing Address2\", type text}, {\"Billing Company\", type text}, {\"Billing City\", type text}, {\"Billing Zip\", type text}, {\"Billing Province\", type text}, {\"Billing Country\", type text}, {\"Billing Phone\", type text}, {\"Shipping Name\", type text}, {\"Shipping Street\", type text}, {\"Shipping Address1\", type text}, {\"Shipping Address2\", type text}, {\"Shipping Company\", type text}, {\"Shipping City\", type text}, {\"Shipping Zip\", type text}, {\"Shipping Province\", type text}, {\"Shipping Country\", type text}, {\"Shipping Phone\", type text}, {\"Notes\", type text}, {\"Note Attributes\", type text}, {\"Cancelled at\", type text}, {\"Payment Method\", type text}, {\"Payment Reference\", type text}, {\"Refunded Amount\", type text}, {\"Vendor\", type text}, {\"Id\", Int64.Type}, {\"Tags\", type text}, {\"Risk Level\", type text}, {\"Source\", type text}, {\"Lineitem discount\", type text}, {\"Tax 1 Name\", type text}, {\"Tax 1 Value\", type text}, {\"Tax 2 Name\", type text}, {\"Tax 2 Value\", type text}, {\"Tax 3 Name\", type text}, {\"Tax 3 Value\", type text}, {\"Tax 4 Name\", type text}, {\"Tax 4 Value\", type text}, {\"Tax 5 Name\", type text}, {\"Tax 5 Value\", type text}, {\"Phone\", Int64.Type}, {\"Receipt Number\", type text}, {\"Duties\", type text}, {\"Billing Province Name\", type text}, {\"Shipping Province Name\", type text}, {\"Payment ID\", type text}, {\"Payment Terms Name\", type text}, {\"Next Payment Due At\", type text}, {\"Payment References\", type text}})",
          "in",
          "    #\"Changed Type\""
        ],
        "kind": "m",
        "lineageTag": "50d4a61d-83c2-4ac5-9bb6-5b6cbfd30e7c"
      },
      {
        "name": "orders_export_2",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Csv.Document(File.Contents(\"C:\\Users\\Nedko\\Desktop\\orders_export\\orders_export_2.csv\"),[Delimiter=\",\", Columns=74, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Name\", type text}, {\"Financial Status\", type text}, {\"Paid at\", type datetimezone}, {\"Fulfillment Status\", type text}, {\"Fulfilled at\", type datetimezone}, {\"Accepts Marketing\", type text}, {\"Currency\", type text}, {\"Subtotal\", type text}, {\"Shipping\", type text}, {\"Taxes\", type text}, {\"Total\", type text}, {\"Discount Code\", type text}, {\"Discount Amount\", type text}, {\"Shipping Method\", type text}, {\"Created at\", type datetimezone}, {\"Lineitem quantity\", Int64.Type}, {\"Lineitem name\", type text}, {\"Lineitem price\", type text}, {\"Lineitem compare at price\", type text}, {\"Lineitem sku\", type text}, {\"Lineitem requires shipping\", type logical}, {\"Lineitem taxable\", type logical}, {\"Lineitem fulfillment status\", type text}, {\"Billing Name\", type text}, {\"Billing Street\", type text}, {\"Billing Address1\", type text}, {\"Billing Address2\", type text}, {\"Billing Company\", type text}, {\"Billing City\", type text}, {\"Billing Zip\", type text}, {\"Billing Province\", type text}, {\"Billing Country\", type text}, {\"Billing Phone\", type text}, {\"Shipping Name\", type text}, {\"Shipping Street\", type text}, {\"Shipping Address1\", type text}, {\"Shipping Address2\", type text}, {\"Shipping Company\", type text}, {\"Shipping City\", type text}, {\"Shipping Zip\", type text}, {\"Shipping Province\", type text}, {\"Shipping Country\", type text}, {\"Shipping Phone\", type text}, {\"Notes\", type text}, {\"Note Attributes\", type text}, {\"Cancelled at\", type text}, {\"Payment Method\", type text}, {\"Payment Reference\", type text}, {\"Refunded Amount\", type text}, {\"Vendor\", type text}, {\"Id\", Int64.Type}, {\"Tags\", type text}, {\"Risk Level\", type text}, {\"Source\", type text}, {\"Lineitem discount\", type text}, {\"Tax 1 Name\", type text}, {\"Tax 1 Value\", type text}, {\"Tax 2 Name\", type text}, {\"Tax 2 Value\", type text}, {\"Tax 3 Name\", type text}, {\"Tax 3 Value\", type text}, {\"Tax 4 Name\", type text}, {\"Tax 4 Value\", type text}, {\"Tax 5 Name\", type text}, {\"Tax 5 Value\", type text}, {\"Phone\", Int64.Type}, {\"Receipt Number\", type text}, {\"Duties\", type text}, {\"Billing Province Name\", type text}, {\"Shipping Province Name\", type text}, {\"Payment ID\", type text}, {\"Payment Terms Name\", type text}, {\"Next Payment Due At\", type text}, {\"Payment References\", type text}})",
          "in",
          "    #\"Changed Type\""
        ],
        "kind": "m",
        "lineageTag": "c61972dd-b7a7-4e53-b941-b545fa8c8187"
      },
      {
        "name": "orders_export_1",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Csv.Document(File.Contents(\"C:\\Users\\Nedko\\Desktop\\orders_export\\orders_export_1.csv\"),[Delimiter=\",\", Columns=74, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Name\", type text}, {\"Financial Status\", type text}, {\"Paid at\", type datetimezone}, {\"Fulfillment Status\", type text}, {\"Fulfilled at\", type text}, {\"Accepts Marketing\", type text}, {\"Currency\", type text}, {\"Subtotal\", type text}, {\"Shipping\", type text}, {\"Taxes\", type text}, {\"Total\", type text}, {\"Discount Code\", type text}, {\"Discount Amount\", type text}, {\"Shipping Method\", type text}, {\"Created at\", type datetimezone}, {\"Lineitem quantity\", Int64.Type}, {\"Lineitem name\", type text}, {\"Lineitem price\", type text}, {\"Lineitem compare at price\", type text}, {\"Lineitem sku\", type text}, {\"Lineitem requires shipping\", type logical}, {\"Lineitem taxable\", type logical}, {\"Lineitem fulfillment status\", type text}, {\"Billing Name\", type text}, {\"Billing Street\", type text}, {\"Billing Address1\", type text}, {\"Billing Address2\", type text}, {\"Billing Company\", type text}, {\"Billing City\", type text}, {\"Billing Zip\", type text}, {\"Billing Province\", type text}, {\"Billing Country\", type text}, {\"Billing Phone\", type text}, {\"Shipping Name\", type text}, {\"Shipping Street\", type text}, {\"Shipping Address1\", type text}, {\"Shipping Address2\", type text}, {\"Shipping Company\", type text}, {\"Shipping City\", type text}, {\"Shipping Zip\", type text}, {\"Shipping Province\", type text}, {\"Shipping Country\", type text}, {\"Shipping Phone\", type text}, {\"Notes\", type text}, {\"Note Attributes\", type text}, {\"Cancelled at\", type text}, {\"Payment Method\", type text}, {\"Payment Reference\", type text}, {\"Refunded Amount\", type text}, {\"Vendor\", type text}, {\"Id\", Int64.Type}, {\"Tags\", type text}, {\"Risk Level\", type text}, {\"Source\", type text}, {\"Lineitem discount\", type text}, {\"Tax 1 Name\", type text}, {\"Tax 1 Value\", type text}, {\"Tax 2 Name\", type text}, {\"Tax 2 Value\", type text}, {\"Tax 3 Name\", type text}, {\"Tax 3 Value\", type text}, {\"Tax 4 Name\", type text}, {\"Tax 4 Value\", type text}, {\"Tax 5 Name\", type text}, {\"Tax 5 Value\", type text}, {\"Phone\", Int64.Type}, {\"Receipt Number\", type text}, {\"Duties\", type text}, {\"Billing Province Name\", type text}, {\"Shipping Province Name\", type text}, {\"Payment ID\", type text}, {\"Payment Terms Name\", type text}, {\"Next Payment Due At\", type text}, {\"Payment References\", type text}})",
          "in",
          "    #\"Changed Type\""
        ],
        "kind": "m",
        "lineageTag": "03e50bc5-faec-4a2c-b658-18f938ef3a17"
      }
    ],
    "relationships": [
      {
        "name": "556d6ef6-6c93-4bb9-89ee-dbb21529ed44",
        "fromColumn": "Paid at",
        "fromTable": "orders_export",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_0229ec9b-511f-4abc-8b01-cbfa7233c771"
      },
      {
        "name": "03694267-3944-4685-ae22-a84183ec9685",
        "fromColumn": "Fulfilled at",
        "fromTable": "orders_export",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_4bbad5d2-e4ac-43dd-9b31-c39af29f709a"
      },
      {
        "name": "a119f627-7602-41cf-b8fb-171212a09f72",
        "fromColumn": "Created at",
        "fromTable": "orders_export",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_46f25b8d-2243-4f95-874f-40474ac2f644"
      },
      {
        "name": "64e43e5f-0a49-48ba-a2ed-1eb99aa31bb6",
        "fromColumn": "Cancelled at",
        "fromTable": "orders_export",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_dc3ed4a0-f438-455f-85c6-ea1ab6a644cc"
      },
      {
        "name": "ba49107b-4be1-4199-9218-d12cf6a24fdf",
        "fromColumn": "Next Payment Due At",
        "fromTable": "orders_export",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_b21d5046-ba36-4e4b-ae98-52f90db16fcb"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "DateTableTemplate_1ded4510-0e97-44cd-9148-867d6994cbf8",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "c492b06b-5883-49b5-9d4b-e27beaf96355",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "204bcce8-58e8-4446-bdb7-8a67f1597d6b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "41634cda-bd52-4af3-ba5b-73048d7ef93a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "e6e09a80-f772-41d8-bbe5-a388fefdff85",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "ec8b3509-e9a8-417c-a877-8fe616b37aed",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "525be63d-5cb9-434c-b367-ced85bc941ba",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "ae32ec78-c3de-4864-b9f8-7da2481acd0b",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "8b2f9e23-0494-444a-bf74-edc95fa129b5",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "566c17bd-8cdc-474d-97b2-b3192fec0070",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "2c491636-fed9-48d5-9aee-cc3283d0ddbe",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "89c2237b-c639-4496-b006-3ac9f65f05fc",
                "ordinal": 3
              }
            ],
            "lineageTag": "92655caf-8f70-4715-9190-0bbb55366a47"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "1832259a-424c-44db-bc98-5ccf7e802d2a",
        "partitions": [
          {
            "name": "DateTableTemplate_1ded4510-0e97-44cd-9148-867d6994cbf8",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "orders_export",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d5a05401-8d1c-4144-9578-4764269366d5",
            "sourceColumn": "Name",
            "summarizeBy": "none"
          },
          {
            "name": "Financial Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3764bd88-cb17-41e8-b87c-671096b94ca0",
            "sourceColumn": "Financial Status",
            "summarizeBy": "none"
          },
          {
            "name": "Paid at",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd/mm/yyyy",
            "lineageTag": "97622abb-71c4-4b9c-a58d-e3c355a466b1",
            "sourceColumn": "Paid at",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_0229ec9b-511f-4abc-8b01-cbfa7233c771"
                },
                "isDefault": true,
                "relationship": "556d6ef6-6c93-4bb9-89ee-dbb21529ed44"
              }
            ]
          },
          {
            "name": "Fulfillment Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0b87cd63-9ecc-41b6-8d04-285112dc1f2c",
            "sourceColumn": "Fulfillment Status",
            "summarizeBy": "none"
          },
          {
            "name": "Fulfilled at",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd/mm/yyyy",
            "lineageTag": "f9670786-1c6e-4605-9d06-e04b03d6e049",
            "sourceColumn": "Fulfilled at",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_4bbad5d2-e4ac-43dd-9b31-c39af29f709a"
                },
                "isDefault": true,
                "relationship": "03694267-3944-4685-ae22-a84183ec9685"
              }
            ]
          },
          {
            "name": "Accepts Marketing",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "45cce3c8-8e37-4aa8-a00b-b7495bc256d8",
            "sourceColumn": "Accepts Marketing",
            "summarizeBy": "none"
          },
          {
            "name": "Currency",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dafe1ccf-d0c7-4129-a4cf-a66d9398d944",
            "sourceColumn": "Currency",
            "summarizeBy": "none"
          },
          {
            "name": "Subtotal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "d69832a7-8781-4fc4-a1b4-7bd1a50a2ad1",
            "sourceColumn": "Subtotal",
            "summarizeBy": "sum"
          },
          {
            "name": "Shipping",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"bg-BG\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "#,0.###############\\ \"лв.\";-#,0.###############\\ \"лв.\";#,0.###############\\ \"лв.\"",
            "lineageTag": "acb801cb-bb9b-43a1-bbea-193e9a154b99",
            "sourceColumn": "Shipping",
            "summarizeBy": "sum"
          },
          {
            "name": "Taxes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"bg-BG\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "#,0.###############\\ \"лв.\";-#,0.###############\\ \"лв.\";#,0.###############\\ \"лв.\"",
            "lineageTag": "d6fd7002-fb9d-4ae1-9cfb-3fd1b296abc4",
            "sourceColumn": "Taxes",
            "summarizeBy": "sum"
          },
          {
            "name": "Total",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "eedb7ffe-4c60-4173-a62c-6d4d2e0dc49a",
            "sourceColumn": "Total",
            "summarizeBy": "sum"
          },
          {
            "name": "Discount Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b5ea3a89-5688-4b07-814f-f02a7c48cdda",
            "sourceColumn": "Discount Code",
            "summarizeBy": "none"
          },
          {
            "name": "Discount Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"bg-BG\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "#,0.###############\\ \"лв.\";-#,0.###############\\ \"лв.\";#,0.###############\\ \"лв.\"",
            "lineageTag": "0c28d570-b698-466d-8b05-cea24cce8ba3",
            "sourceColumn": "Discount Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Shipping Method",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "69c9547d-6b61-4d17-b7fb-f70cc572229b",
            "sourceColumn": "Shipping Method",
            "summarizeBy": "none"
          },
          {
            "name": "Created at",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd/mm/yyyy",
            "lineageTag": "de482e9f-9973-486a-8668-4a526d2f5593",
            "sourceColumn": "Created at",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_46f25b8d-2243-4f95-874f-40474ac2f644"
                },
                "isDefault": true,
                "relationship": "a119f627-7602-41cf-b8fb-171212a09f72"
              }
            ]
          },
          {
            "name": "Lineitem quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "55207ffa-f180-46a3-8df3-041d0688ac46",
            "sourceColumn": "Lineitem quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "Lineitem name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f5e44ce3-27a2-4c12-9d1c-e736b770ec77",
            "sourceColumn": "Lineitem name",
            "summarizeBy": "none"
          },
          {
            "name": "Lineitem price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "0ca38192-6b51-4660-bdde-f10ea359280b",
            "sourceColumn": "Lineitem price",
            "summarizeBy": "sum"
          },
          {
            "name": "Lineitem compare at price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "11fb144d-232e-4303-951c-c516688ac9b6",
            "sourceColumn": "Lineitem compare at price",
            "summarizeBy": "sum"
          },
          {
            "name": "Lineitem sku",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "154771d3-937f-44dd-ad83-87af364aca40",
            "sourceColumn": "Lineitem sku",
            "summarizeBy": "none"
          },
          {
            "name": "Lineitem requires shipping",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "d0fc84e9-33f8-4263-8b0c-7c4165f50139",
            "sourceColumn": "Lineitem requires shipping",
            "summarizeBy": "none"
          },
          {
            "name": "Lineitem taxable",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "0540d6ed-fb1f-4cd8-86b3-b6626b238581",
            "sourceColumn": "Lineitem taxable",
            "summarizeBy": "none"
          },
          {
            "name": "Lineitem fulfillment status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7471b311-620b-431b-a96a-ace2c5c7f477",
            "sourceColumn": "Lineitem fulfillment status",
            "summarizeBy": "none"
          },
          {
            "name": "Billing Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c0ac4f2a-9cb0-400c-9473-5a2c2231b5ec",
            "sourceColumn": "Billing Name",
            "summarizeBy": "none"
          },
          {
            "name": "Billing Street",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "71ea7e62-a9b1-4d7b-ac6d-d385b74a78f9",
            "sourceColumn": "Billing Street",
            "summarizeBy": "none"
          },
          {
            "name": "Billing Address1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ccdc9420-f1f0-4aa0-9667-3cc929a2d9e2",
            "sourceColumn": "Billing Address1",
            "summarizeBy": "none"
          },
          {
            "name": "Billing Address2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "934cbb29-f1a7-4549-99f6-de82ac2a8950",
            "sourceColumn": "Billing Address2",
            "summarizeBy": "none"
          },
          {
            "name": "Billing Company",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ae8d6885-3195-4e87-a620-003056306c31",
            "sourceColumn": "Billing Company",
            "summarizeBy": "none"
          },
          {
            "name": "Billing City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1f59ef7e-c8c8-4d23-ad75-ff458e6f07d5",
            "sourceColumn": "Billing City",
            "summarizeBy": "none"
          },
          {
            "name": "Billing Zip",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4c2f7167-5d24-4040-83be-24f93968268c",
            "sourceColumn": "Billing Zip",
            "summarizeBy": "none"
          },
          {
            "name": "Billing Province",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "45e78cf7-76cb-4a8e-a130-1102868f1271",
            "sourceColumn": "Billing Province",
            "summarizeBy": "none"
          },
          {
            "name": "Billing Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9ba75f19-1dec-4592-b986-0e461edd5800",
            "sourceColumn": "Billing Country",
            "summarizeBy": "none"
          },
          {
            "name": "Billing Phone",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "da760021-5347-449a-bc26-ec390f740921",
            "sourceColumn": "Billing Phone",
            "summarizeBy": "none"
          },
          {
            "name": "Shipping Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e6fce76e-2e79-4621-88dc-223df5653dfa",
            "sourceColumn": "Shipping Name",
            "summarizeBy": "none"
          },
          {
            "name": "Shipping Street",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7e7b668b-8c1b-4563-b898-849944aa1997",
            "sourceColumn": "Shipping Street",
            "summarizeBy": "none"
          },
          {
            "name": "Shipping Address1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fd7954fc-eba2-4592-8961-c2644d1e696b",
            "sourceColumn": "Shipping Address1",
            "summarizeBy": "none"
          },
          {
            "name": "Shipping Address2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5187065f-a012-4c75-bcce-d5aa38834045",
            "sourceColumn": "Shipping Address2",
            "summarizeBy": "none"
          },
          {
            "name": "Shipping Company",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "05fe0307-b908-4864-baef-5cf04f2e1994",
            "sourceColumn": "Shipping Company",
            "summarizeBy": "none"
          },
          {
            "name": "Shipping City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "30860af4-4e0a-4846-b444-f1c8c2f44ecb",
            "sourceColumn": "Shipping City",
            "summarizeBy": "none"
          },
          {
            "name": "Shipping Zip",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "29751b58-9ac8-4dfc-9e72-4c1bd58b76a8",
            "sourceColumn": "Shipping Zip",
            "summarizeBy": "none"
          },
          {
            "name": "Shipping Province",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fb4e714e-f433-4750-98c7-fb7de9174b04",
            "sourceColumn": "Shipping Province",
            "summarizeBy": "none"
          },
          {
            "name": "Shipping Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "82be741d-e81d-4ac4-a012-dd8854ba9dfb",
            "sourceColumn": "Shipping Country",
            "summarizeBy": "none"
          },
          {
            "name": "Shipping Phone",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "87c3735a-de64-4d54-8c91-96ed7f56a8a0",
            "sourceColumn": "Shipping Phone",
            "summarizeBy": "none"
          },
          {
            "name": "Notes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bd7c5d2e-e380-41bb-9aa8-a6619652981f",
            "sourceColumn": "Notes",
            "summarizeBy": "none"
          },
          {
            "name": "Note Attributes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e901d86d-c3b2-413d-bdb2-c3b2f7f8bdfd",
            "sourceColumn": "Note Attributes",
            "summarizeBy": "none"
          },
          {
            "name": "Cancelled at",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd/mm/yyyy",
            "lineageTag": "956adea5-ced8-4d20-a58a-f56c82b52205",
            "sourceColumn": "Cancelled at",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_dc3ed4a0-f438-455f-85c6-ea1ab6a644cc"
                },
                "isDefault": true,
                "relationship": "64e43e5f-0a49-48ba-a2ed-1eb99aa31bb6"
              }
            ]
          },
          {
            "name": "Payment Method",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bd9dc511-9578-48ad-bd63-c08ee27d3d41",
            "sourceColumn": "Payment Method",
            "summarizeBy": "none"
          },
          {
            "name": "Payment Reference",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5e080542-7fff-4240-ae17-875fa749d9ff",
            "sourceColumn": "Payment Reference",
            "summarizeBy": "none"
          },
          {
            "name": "Refunded Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "7edcabba-327b-4af4-97a1-f6c7dcd0c339",
            "sourceColumn": "Refunded Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Vendor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "aab23232-e138-458d-8e9f-fc90813d3a48",
            "sourceColumn": "Vendor",
            "summarizeBy": "none"
          },
          {
            "name": "Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d2efe6ff-b11d-4c3c-8e01-9447765c8b8b",
            "sourceColumn": "Id",
            "summarizeBy": "none"
          },
          {
            "name": "Tags",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eb8f4790-bb20-4f6d-9467-994d9cb33a88",
            "sourceColumn": "Tags",
            "summarizeBy": "none"
          },
          {
            "name": "Risk Level",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e76255f1-78d4-44de-b511-f551aee1c8a8",
            "sourceColumn": "Risk Level",
            "summarizeBy": "none"
          },
          {
            "name": "Source",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ba896393-9977-41fc-aa62-b711fa37517a",
            "sourceColumn": "Source",
            "summarizeBy": "none"
          },
          {
            "name": "Lineitem discount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "e4498a68-6ac0-44a4-b501-45abe8d854dd",
            "sourceColumn": "Lineitem discount",
            "summarizeBy": "sum"
          },
          {
            "name": "Tax 1 Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "862e007f-5ff0-4b1a-b8b2-9948f74009ba",
            "sourceColumn": "Tax 1 Name",
            "summarizeBy": "none"
          },
          {
            "name": "Tax 1 Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "91dda483-b4e3-49c2-b82c-5a1cdd29f8e8",
            "sourceColumn": "Tax 1 Value",
            "summarizeBy": "sum"
          },
          {
            "name": "Tax 2 Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "52732750-47a7-407f-b7f1-67a45da681a0",
            "sourceColumn": "Tax 2 Name",
            "summarizeBy": "none"
          },
          {
            "name": "Tax 2 Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "5aa515e7-1335-4d79-81c9-e9584c052794",
            "sourceColumn": "Tax 2 Value",
            "summarizeBy": "sum"
          },
          {
            "name": "Tax 3 Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ae2ae080-66f1-4478-9c5c-04f9aa73d75f",
            "sourceColumn": "Tax 3 Name",
            "summarizeBy": "none"
          },
          {
            "name": "Tax 3 Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "7765f4d2-52cf-4ace-8451-23e109419829",
            "sourceColumn": "Tax 3 Value",
            "summarizeBy": "sum"
          },
          {
            "name": "Tax 4 Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "15683923-fa5e-4b66-ac23-a73abd6c7783",
            "sourceColumn": "Tax 4 Name",
            "summarizeBy": "none"
          },
          {
            "name": "Tax 4 Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "4c38aed7-3a04-4efe-a668-99e2fcc2d7da",
            "sourceColumn": "Tax 4 Value",
            "summarizeBy": "sum"
          },
          {
            "name": "Tax 5 Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "abdd78f5-51fe-462f-8330-9d9f877e2dee",
            "sourceColumn": "Tax 5 Name",
            "summarizeBy": "none"
          },
          {
            "name": "Tax 5 Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "45f28d17-604c-41cc-aa93-841579c3badc",
            "sourceColumn": "Tax 5 Value",
            "summarizeBy": "sum"
          },
          {
            "name": "Phone",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "98f52bfb-81ca-4016-adbe-1d8b5e73733f",
            "sourceColumn": "Phone",
            "summarizeBy": "none"
          },
          {
            "name": "Receipt Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "66e3725c-f8b8-48f6-b12d-e3467eb650e2",
            "sourceColumn": "Receipt Number",
            "summarizeBy": "none"
          },
          {
            "name": "Duties",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d2c06a00-1d91-4dac-9629-4c4fdaceb8d4",
            "sourceColumn": "Duties",
            "summarizeBy": "none"
          },
          {
            "name": "Billing Province Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "23fa793e-3341-4b39-b48e-646865b29036",
            "sourceColumn": "Billing Province Name",
            "summarizeBy": "none"
          },
          {
            "name": "Shipping Province Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "afd6a16f-a12e-40aa-9f7c-ab1e88f70106",
            "sourceColumn": "Shipping Province Name",
            "summarizeBy": "none"
          },
          {
            "name": "Payment ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3db1269f-0023-4796-9d7c-0ab98ab3e38a",
            "sourceColumn": "Payment ID",
            "summarizeBy": "none"
          },
          {
            "name": "Payment Terms Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c53863f1-cf4d-430c-8969-d761d9b14b5e",
            "sourceColumn": "Payment Terms Name",
            "summarizeBy": "none"
          },
          {
            "name": "Next Payment Due At",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd/mm/yyyy",
            "lineageTag": "93261fd5-c02e-43a2-878b-c1675f7cddf7",
            "sourceColumn": "Next Payment Due At",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_b21d5046-ba36-4e4b-ae98-52f90db16fcb"
                },
                "isDefault": true,
                "relationship": "ba49107b-4be1-4199-9218-d12cf6a24fdf"
              }
            ]
          },
          {
            "name": "Payment References",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a4642f92-063b-40ca-9bd2-5120eb13407b",
            "sourceColumn": "Payment References",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "df296fef-da2b-4a82-8866-f586b6674ebe",
        "partitions": [
          {
            "name": "orders_export",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.Combine({orders_export_1, orders_export_2, orders_export_3, orders_export_4, orders_export_5, orders_export_6, orders_export_7}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Fulfilled at\", type datetimezone}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Changed Type\",\".\",\",\",Replacer.ReplaceText,{\"Subtotal\", \"Shipping\", \"Taxes\", \"Total\", \"Discount Amount\", \"Lineitem price\", \"Lineitem compare at price\"}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Replaced Value\",{{\"Subtotal\", Currency.Type}, {\"Shipping\", Currency.Type}, {\"Taxes\", Currency.Type}, {\"Total\", Currency.Type}, {\"Discount Amount\", Currency.Type}, {\"Lineitem price\", Currency.Type}, {\"Lineitem compare at price\", Currency.Type}, {\"Cancelled at\", type datetimezone}, {\"Id\", type text}}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Changed Type1\",\".\",\",\",Replacer.ReplaceText,{\"Refunded Amount\"}),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Replaced Value1\",{{\"Refunded Amount\", Currency.Type}}),",
                "    #\"Replaced Value2\" = Table.ReplaceValue(#\"Changed Type2\",\".\",\",\",Replacer.ReplaceText,{\"Lineitem discount\"}),",
                "    #\"Changed Type3\" = Table.TransformColumnTypes(#\"Replaced Value2\",{{\"Lineitem discount\", Currency.Type}}),",
                "    #\"Replaced Value3\" = Table.ReplaceValue(#\"Changed Type3\",\".\",\",\",Replacer.ReplaceText,{\"Tax 1 Value\", \"Tax 2 Value\", \"Tax 3 Value\", \"Tax 4 Value\", \"Tax 5 Value\"}),",
                "    #\"Changed Type4\" = Table.TransformColumnTypes(#\"Replaced Value3\",{{\"Tax 1 Value\", Currency.Type}, {\"Tax 2 Value\", Currency.Type}, {\"Tax 3 Value\", Currency.Type}, {\"Tax 4 Value\", Currency.Type}, {\"Tax 5 Value\", Currency.Type}, {\"Phone\", type text}, {\"Next Payment Due At\", type datetime}, {\"Paid at\", type datetime}, {\"Fulfilled at\", type datetime}, {\"Created at\", type datetime}}),",
                "    #\"Replaced Value4\" = Table.ReplaceValue(#\"Changed Type4\",\"Mrs.\",\"Mrs\",Replacer.ReplaceText,{\"Shipping Company\"})",
                "in",
                "    #\"Replaced Value4\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_0229ec9b-511f-4abc-8b01-cbfa7233c771",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "1b996a4b-9756-4528-a2b1-9c30f3598ffa",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "89244460-da86-426a-9dec-1c9b2cea4142",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "2459b8fe-d308-4d7b-9549-645a043a7d7a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "b044f39c-35fb-43ac-84f8-2a60e9e595ba",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "9f5687db-1392-4833-9f27-c9e9c957078b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "acb76294-31c7-489a-a8d1-e9b25f0d35c5",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "b2cf61d4-61c7-43dc-be47-7047ca8b3dd5",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "73c2c0d0-81cd-42f9-84d9-a06779000af7",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "a489d726-54df-4380-bb7c-af351275add2",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "98324b52-1a47-4268-b71c-444d15d7a2fb",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "0660a2f6-3df1-4ee5-a211-51514b24b408",
                "ordinal": 3
              }
            ],
            "lineageTag": "5f498a79-ce45-4d99-896f-0d47de0ba957"
          }
        ],
        "isHidden": true,
        "lineageTag": "61e1df82-37c6-430d-aa88-20dcf90096bd",
        "partitions": [
          {
            "name": "LocalDateTable_0229ec9b-511f-4abc-8b01-cbfa7233c771",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('orders_export'[Paid at])), 1, 1), Date(Year(MAX('orders_export'[Paid at])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_4bbad5d2-e4ac-43dd-9b31-c39af29f709a",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "b5b5e0a3-0e71-4374-ab1a-3c341b087bd5",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "848d1e35-b995-447a-80bb-73c5d012a477",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "f918e9e0-6d51-4ca1-8aaf-c54fa195e439",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "6e9b6978-09de-4f92-8012-b939a4e18043",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "2db44ac7-8870-408b-b260-4960844825da",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "b3451334-73dd-41d8-9f5b-0a928a50630e",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "7524d59e-cb39-472f-a493-c17d61e13726",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "f18981d0-5558-4515-a3be-2936d1ea7100",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "133785a4-3706-4530-bfa9-80e3c61b6b42",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "0b907663-093a-4bc8-8438-eebe53b76809",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "c17619a4-fd48-4a8e-86d8-17467520a7dc",
                "ordinal": 3
              }
            ],
            "lineageTag": "9a127c35-b38a-4a9b-b33c-a4fd5a36cf1e"
          }
        ],
        "isHidden": true,
        "lineageTag": "503b8e34-1719-49a0-a2bb-8180bb8b8bee",
        "partitions": [
          {
            "name": "LocalDateTable_4bbad5d2-e4ac-43dd-9b31-c39af29f709a",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('orders_export'[Fulfilled at])), 1, 1), Date(Year(MAX('orders_export'[Fulfilled at])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_46f25b8d-2243-4f95-874f-40474ac2f644",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "ed992ff9-3d39-48a2-8138-362175835180",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "5e1b179c-bc19-47f9-b09c-27b35dbdc30f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "1fd8577a-b2df-467a-86c2-2f388d723e72",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "455a34f3-ee42-4873-9e5a-ee1354159916",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "9505df8a-a771-4298-9a41-828636f56090",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "3476b30e-e485-472a-87e1-2488705257b4",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "0083b0ab-edfa-41bb-be1d-72a6745a0ead",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "6435da03-948f-449f-ba99-92e782a6b5c1",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "65132b1d-791e-4df6-89d6-1da6c07641b6",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "e826e1e2-c19a-461b-b120-994ecc0b3da4",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "c71a6b2b-df61-4a1e-afc4-3353d7af3604",
                "ordinal": 3
              }
            ],
            "lineageTag": "28d9d30f-82c1-4dc2-956f-5b52f42e4747"
          }
        ],
        "isHidden": true,
        "lineageTag": "4b6d0f81-3a69-4c04-97aa-3c05ff3ec14d",
        "partitions": [
          {
            "name": "LocalDateTable_46f25b8d-2243-4f95-874f-40474ac2f644",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('orders_export'[Created at])), 1, 1), Date(Year(MAX('orders_export'[Created at])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_dc3ed4a0-f438-455f-85c6-ea1ab6a644cc",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "b6023cbe-2a0d-48da-8429-8d321847fd16",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "77790b88-5b9d-48f9-b5df-f61046869946",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "b9c6e9c6-6f37-4f9f-b087-2524a988b087",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "92f5a260-f1da-45a2-bc44-d475b36c2740",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "2271dba8-086e-4d3a-8c20-22bdbda3c580",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "624710f5-3b74-4081-938f-9a3a922dfcfd",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "502db197-6e2c-402b-b56a-fb6ef36371a3",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "50b802ca-6bb9-4bd3-be3c-abfc4a36a947",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "b22625d4-d9ef-414a-a181-ee44535adb2c",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "77913732-53b3-4b3d-a2ea-24c94b659a31",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "5e7c4daa-a51a-43d7-ab12-bae6292e2ffb",
                "ordinal": 3
              }
            ],
            "lineageTag": "ebedc515-0f90-438e-80d3-8f824cab98fe"
          }
        ],
        "isHidden": true,
        "lineageTag": "8828c9b9-7f79-465a-9c97-b57d278df8e9",
        "partitions": [
          {
            "name": "LocalDateTable_dc3ed4a0-f438-455f-85c6-ea1ab6a644cc",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('orders_export'[Cancelled at])), 1, 1), Date(Year(MAX('orders_export'[Cancelled at])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_b21d5046-ba36-4e4b-ae98-52f90db16fcb",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "e7de402c-a7b1-4da0-867f-46d9d7e908cd",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "dfcaaafe-417c-43df-90b0-b3dfc5ae4408",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "2f324ca8-d3cb-4d28-aee1-bc9a00147476",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "5ea29372-0099-4604-8c79-063d29915348",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "9c87ab14-def5-485d-b9bb-001f7e9bb2c2",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "0c6d99d9-9804-4e86-be1b-4470db2d046c",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "56ef9e24-9955-4105-ad00-786e4946cc80",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "4cfe65ed-84ed-4b95-8597-9eee7cdd9812",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "8cb189e9-7588-4e51-ab10-ccc10d711349",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "b2df307f-48fe-4935-a1f4-f6753916d5ac",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "8f02f7d2-8a1c-4280-a622-2dc9a7fff50e",
                "ordinal": 3
              }
            ],
            "lineageTag": "7c5646fe-7f1e-4ee4-99f9-a71fd5396414"
          }
        ],
        "isHidden": true,
        "lineageTag": "2d104035-0bc6-4951-ae27-4d47369502e6",
        "partitions": [
          {
            "name": "LocalDateTable_b21d5046-ba36-4e4b-ae98-52f90db16fcb",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('orders_export'[Next Payment Due At])), 1, 1), Date(Year(MAX('orders_export'[Next Payment Due At])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "metrics",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "lineageTag": "3e03e050-d0d9-457c-8712-cba89ef24e85",
        "measures": [
          {
            "name": "Total Sales Income",
            "expression": [
              "CALCULATE(",
              "    SUMX(orders_export, orders_export[Lineitem price] * orders_export[Lineitem quantity]),",
              "    ALL(orders_export)",
              ")"
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "56a6899a-3604-4768-8a07-21d625969cf4"
          },
          {
            "name": "Total Sales Count",
            "expression": [
              "CALCULATE(",
              "    SUMX(orders_export, orders_export[Lineitem quantity]),",
              "    ALL(orders_export)",
              ")"
            ],
            "formatString": "#,0.00",
            "lineageTag": "3f3c8697-4e9f-4a2c-aaf1-442302b02401"
          },
          {
            "name": "Most Common Lineitem Combinations",
            "expression": [
              "",
              "VAR TopCombinations = ",
              "    TOPN(",
              "        1,",
              "        SUMMARIZE(",
              "            ALL(orders_export),",
              "            'orders_export'[Name],",
              "            \"Lineitem Combination\", CONCATENATEX(RELATEDTABLE('orders_export'), orders_export[Lineitem name], \" + \")",
              "        ),",
              "        [Lineitem Combination], ",
              "        DESC",
              "    )",
              "RETURN",
              "    CONCATENATEX(",
              "        TopCombinations,",
              "        [Lineitem Combination],",
              "        \", \"",
              "    )",
              ""
            ],
            "lineageTag": "b70e75fe-b03d-4a39-b380-6b7333616476"
          }
        ],
        "partitions": [
          {
            "name": "metrics",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}