{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Chess Games\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.124.2028.0 (23.12)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Entities": {
              "chess_games.opening_fullname": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Chess Games",
                    "ConceptualProperty": "opening_fullname"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Opening": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "chess_games.winner": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Chess Games",
                    "ConceptualProperty": "winner"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Winner": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              }
            },
            "Language": "en-US",
            "Version": "2.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "bg-BG",
    "tables": [
      {
        "name": "Chess Games",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "game_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5235deb2-510a-4776-a187-0b74d2df85ee",
            "sourceColumn": "game_id",
            "summarizeBy": "sum"
          },
          {
            "name": "rated",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "c796dc3c-f3b1-40ba-ba78-a5b939b4d68f",
            "sourceColumn": "rated",
            "summarizeBy": "none"
          },
          {
            "name": "turns",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d6e5360f-588e-4b65-86bd-87ad59df622d",
            "sourceColumn": "turns",
            "summarizeBy": "sum"
          },
          {
            "name": "victory_status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "148ee25e-3fc9-4669-9d06-ec626f8b4ce6",
            "sourceColumn": "victory_status",
            "summarizeBy": "none"
          },
          {
            "name": "winner",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "34822978-d540-4987-b6a4-661f3de35c12",
            "sourceColumn": "winner",
            "summarizeBy": "none"
          },
          {
            "name": "time_increment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "63027649-5ebc-4ad7-9f14-45667e4c636d",
            "sourceColumn": "time_increment",
            "summarizeBy": "none"
          },
          {
            "name": "white_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8522f226-ef9b-441c-b08a-e144ecf6525a",
            "sourceColumn": "white_id",
            "summarizeBy": "none"
          },
          {
            "name": "white_rating",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5dc4d5d6-469c-4e16-adda-c2b945a210d4",
            "sourceColumn": "white_rating",
            "summarizeBy": "sum"
          },
          {
            "name": "black_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3837c3df-7db0-4ab3-9817-26e6b8ca4279",
            "sourceColumn": "black_id",
            "summarizeBy": "none"
          },
          {
            "name": "black_rating",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "17262b81-513c-43c1-a647-2cbd5946587e",
            "sourceColumn": "black_rating",
            "summarizeBy": "sum"
          },
          {
            "name": "moves",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "943ccdf3-f485-4338-b0f4-8c73a8766428",
            "sourceColumn": "moves",
            "summarizeBy": "none"
          },
          {
            "name": "opening_code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8d0caec4-cf56-4bba-9cb3-ec53da3018e5",
            "sourceColumn": "opening_code",
            "summarizeBy": "none"
          },
          {
            "name": "opening_moves",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "86c7fcee-88af-4968-86d7-9b6d2b2b818c",
            "sourceColumn": "opening_moves",
            "summarizeBy": "sum"
          },
          {
            "name": "opening_fullname",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0515b631-8550-4fd6-8dc9-7772e6f6b3ed",
            "sourceColumn": "opening_fullname",
            "summarizeBy": "none"
          },
          {
            "name": "opening_shortname",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "18be05cc-027b-4d9b-b30a-74910977f858",
            "sourceColumn": "opening_shortname",
            "summarizeBy": "none"
          },
          {
            "name": "opening_response",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b33bc912-e5db-4904-a57f-468f6656c1a9",
            "sourceColumn": "opening_response",
            "summarizeBy": "none"
          },
          {
            "name": "opening_variation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e5be4c0f-baf3-4fe5-99a1-fe90b970ede7",
            "sourceColumn": "opening_variation",
            "summarizeBy": "none"
          },
          {
            "name": "WinnerHigherRating",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "expression": [
              "",
              "IF(",
              "    'Chess Games'[Winner] <> \"Draw\",",
              "    IF(",
              "        'Chess Games'[Winner] = \"White\" && 'Chess Games'[white_rating] > 'Chess Games'[black_rating],",
              "        TRUE(),",
              "        IF(",
              "            'Chess Games'[Winner] = \"Black\" && 'Chess Games'[black_rating] > 'Chess Games'[white_rating],",
              "            TRUE(),",
              "            FALSE()",
              "        )",
              "    )",
              ")",
              ""
            ],
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isDataTypeInferred": true,
            "lineageTag": "52cc327e-f3fc-47ac-8acf-8b9626e0a4f0",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "c0f7182b-3703-481d-8150-bb3056b50dda",
        "partitions": [
          {
            "name": "Chess Games",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\Nedko\\Desktop\\Online+Chess+Games\\chess_games.csv\"),[Delimiter=\",\", Columns=17, Encoding=1251, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"game_id\", Int64.Type}, {\"rated\", type logical}, {\"turns\", Int64.Type}, {\"victory_status\", type text}, {\"winner\", type text}, {\"time_increment\", type text}, {\"white_id\", type text}, {\"white_rating\", Int64.Type}, {\"black_id\", type text}, {\"black_rating\", Int64.Type}, {\"moves\", type text}, {\"opening_code\", type text}, {\"opening_moves\", Int64.Type}, {\"opening_fullname\", type text}, {\"opening_shortname\", type text}, {\"opening_response\", type text}, {\"opening_variation\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_577d330e-c5d2-4514-8b83-08e7b72ce864",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "0b237feb-3f92-492f-97ce-036ecfa7d201",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "245c3a17-2527-48a7-8e94-8e1b61ff5719",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "e69e2f2d-5374-4387-9745-29c21c6c9858",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "a3170102-c6f0-4fca-a913-2473a86ea175",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "780fd2b2-3941-4ff1-91dc-45dc437c92b6",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "0af0c3c2-f4cb-428a-b032-da0f910a3801",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "b0473858-4452-4ce7-8644-e402465bec68",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "eaef4556-2c01-4eec-942c-e78bc3916ad1",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "6628d85c-3914-4349-b9e4-c316c677d2f3",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "c5e14f2c-84f6-45c3-8dc8-234f6fc969a0",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "91faa3c7-7ca8-4de5-bd63-0e91451c46f7",
                "ordinal": 3
              }
            ],
            "lineageTag": "1159d549-dd31-409e-878f-cfe0dfb4f0ba"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "5efe92c3-d568-4bb0-995f-38a0189c18b9",
        "partitions": [
          {
            "name": "DateTableTemplate_577d330e-c5d2-4514-8b83-08e7b72ce864",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "All Measures",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "cff6711d57714dd29f0a34ad9e3541c2"
          },
          {
            "name": "436ba87b-9c83-4389-a31b-ebd06a36be98",
            "value": "{\"Expression\":\"\"}"
          }
        ],
        "columns": [
          {
            "name": "Column",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "4b373753-6609-43b4-9a41-a14e0f4aedd8",
            "sourceColumn": "[Column]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "448709a1-d21f-48fa-87d0-0969a0abd807",
        "measures": [
          {
            "name": "CountHigherRatingWins",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNTAX(",
              "        FILTER('Chess Games', 'Chess Games'[WinnerHigherRating] = TRUE()),",
              "        'Chess Games'[WinnerHigherRating]",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "50fc9cb9-69e4-4e1e-ad2a-05352e2203b8"
          },
          {
            "name": "MostWinsPlayerID",
            "expression": [
              "",
              "CALCULATE(",
              "    TOPN(1, VALUES('Player Results'[player_id]), CALCULATE(COUNTROWS('Player Results')))",
              ")"
            ],
            "lineageTag": "300912d1-ec7f-4788-9d6e-ef37eb75ff32"
          },
          {
            "name": "PercentageHigherRatedWins",
            "expression": [
              "",
              "DIVIDE(",
              "    CALCULATE(",
              "        COUNTAX(",
              "            FILTER('Player Results', 'Player Results'[player_id] = [MostWinsPlayerID] && 'Player Results'[Winner] <> \"Draw\"),",
              "            'Player Results'[Winner]",
              "        )",
              "    ),",
              "    CALCULATE(",
              "        COUNTAX(",
              "            FILTER('Player Results', 'Player Results'[player_id] = [MostWinsPlayerID]),",
              "            'Player Results'[Winner]",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "a0604ff2-89ab-4723-9e5d-057085012ce3"
          }
        ],
        "partitions": [
          {
            "name": "All Measures",
            "mode": "import",
            "source": {
              "expression": "Row(\"Column\", BLANK())",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Player Results",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "8607d138e4954bc68a0dae1a33c7f6cd"
          }
        ],
        "columns": [
          {
            "name": "player_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "701e6737-b9a8-49fe-9289-79e862cd2fff",
            "sourceColumn": "[player_id]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Rating",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "0d5ad940-940e-41c2-bbed-b56a10e58028",
            "sourceColumn": "[Rating]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Winner",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "1186af60-6b7e-420f-9108-32f848d7a65f",
            "sourceColumn": "[Winner]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "7c9ec493-f0eb-4509-b91d-bd6bc17540f3",
        "partitions": [
          {
            "name": "Player Results",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "UNION(",
                "    SELECTCOLUMNS('Chess Games', \"player_id\", 'Chess Games'[white_id], \"Rating\", 'Chess Games'[white_rating], \"Winner\", 'Chess Games'[Winner]),",
                "    SELECTCOLUMNS('Chess Games', \"player_id\", 'Chess Games'[black_id], \"Rating\", 'Chess Games'[black_rating], \"Winner\", 'Chess Games'[Winner])",
                ")",
                ""
              ],
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}