{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"dim_consumer_preferences\",\"dim_consumers\",\"fact_ratings\",\"dim_restaurant_cuisines\",\"dim_restaurants\",\"metrics\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.129.905.0 (24.05)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "AutoDetected_9f318b4b-dabe-4956-bfd9-291d773e3af0",
        "fromColumn": "Consumer_ID",
        "fromTable": "dim_consumer_preferences",
        "toColumn": "Consumer_ID",
        "toTable": "dim_consumers"
      },
      {
        "name": "AutoDetected_353a129f-bfe4-44a6-8bbf-2df17ca43c0e",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "Consumer_ID",
        "fromTable": "fact_ratings",
        "toColumn": "Consumer_ID",
        "toTable": "dim_consumers"
      },
      {
        "name": "AutoDetected_af7b7feb-3770-4079-8ea0-f589f5000105",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "Restaurant_ID",
        "fromTable": "fact_ratings",
        "toColumn": "Restaurant_ID",
        "toTable": "dim_restaurants"
      },
      {
        "name": "AutoDetected_b8710f19-9011-4230-92a7-bf36be11c47a",
        "fromColumn": "Restaurant_ID",
        "fromTable": "dim_restaurant_cuisines",
        "toColumn": "Restaurant_ID",
        "toTable": "dim_restaurants"
      }
    ],
    "sourceQueryCulture": "bg-BG",
    "tables": [
      {
        "name": "dim_consumer_preferences",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Consumer_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "024c1b46-e25f-4170-9150-03ad263a42d1",
            "sourceColumn": "Consumer_ID",
            "summarizeBy": "none"
          },
          {
            "name": "Preferred_Cuisine",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2282bc6f-4c5c-4153-bfc6-cde1e4b78a0f",
            "sourceColumn": "Preferred_Cuisine",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "55856521-700f-4632-8e69-24f39e72588b",
        "partitions": [
          {
            "name": "dim_consumer_preferences",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"E:\\GitHub projects\\Power-BI-Portfolio\\Mexico Restaurant Ratings Dashboard\\Mexico Restaurant Ratings.Dataset\\consumer_preferences.csv\"),[Delimiter=\",\", Columns=2, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}, {\"Column2\", type text}}),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Changed Type\", [PromoteAllScalars=true])",
                "in",
                "    #\"Promoted Headers\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_de5e3f72-90c6-41e7-832e-133e9c7f4d04",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "8517236f-611f-483b-8ca9-22b27c592fef",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "d0f75fd2-b890-44c0-9188-b0dbd4f1b15c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "5d28dd17-c3d5-4a98-8909-63503bec8150",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "996de814-cbe7-41e0-8277-b9be421bb77b",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "056a975f-f6df-4642-9000-2fba522d74c8",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "dd9223af-f86a-4625-bd52-9c47094f84ee",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "56cbb68f-b2f0-4738-84f0-8e2f51ed0997",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "9423458b-e588-4431-91ce-84ec37cd2a5e",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "89fe03b6-5487-4ba4-a374-522e1252ab95",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "56cb8864-7eec-411a-a2f7-2fc9572aa1c0",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "e7a1425e-8e4c-4a2e-bca5-f28cb610755f",
                "ordinal": 3
              }
            ],
            "lineageTag": "22284536-cf55-41ec-9ebd-d4a60bb1cef3"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "a10b8538-6f77-4343-bdd3-fe04223bb73a",
        "partitions": [
          {
            "name": "DateTableTemplate_de5e3f72-90c6-41e7-832e-133e9c7f4d04",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "dim_consumers",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Consumer_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "aaa844af-da32-4866-801c-d140d01cb27c",
            "sourceColumn": "Consumer_ID",
            "summarizeBy": "none"
          },
          {
            "name": "City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f235b494-37ff-4b7e-814f-69845401ba28",
            "sourceColumn": "City",
            "summarizeBy": "none"
          },
          {
            "name": "State",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "01373374-046a-439a-8c72-60f237ba3ea1",
            "sourceColumn": "State",
            "summarizeBy": "none"
          },
          {
            "name": "Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ea019090-d144-4d9c-9c5a-abb2518be6a9",
            "sourceColumn": "Country",
            "summarizeBy": "none"
          },
          {
            "name": "Latitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d77d711f-fcd5-4bc3-b0ea-a05452c7b476",
            "sourceColumn": "Latitude",
            "summarizeBy": "sum"
          },
          {
            "name": "Longitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "aed9e5ce-2aba-44e1-a7e8-fb929346a508",
            "sourceColumn": "Longitude",
            "summarizeBy": "sum"
          },
          {
            "name": "Smoker",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4d6338bf-42f3-4686-a895-3c6a27c1e236",
            "sourceColumn": "Smoker",
            "summarizeBy": "none"
          },
          {
            "name": "Drink_Level",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d5813ded-3b9d-4220-8fb2-36f1b73b9258",
            "sourceColumn": "Drink_Level",
            "summarizeBy": "none"
          },
          {
            "name": "Transportation_Method",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "18912fea-5350-4d02-aa6e-dca77204d9fd",
            "sourceColumn": "Transportation_Method",
            "summarizeBy": "none"
          },
          {
            "name": "Marital_Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d2ad66c4-72bc-4a5d-be8f-8e20a6748450",
            "sourceColumn": "Marital_Status",
            "summarizeBy": "none"
          },
          {
            "name": "Children",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "88d06470-809e-477b-9e45-16ce384ff3b1",
            "sourceColumn": "Children",
            "summarizeBy": "none"
          },
          {
            "name": "Age",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0b665d13-d7db-41d6-93ce-fda4054e4211",
            "sourceColumn": "Age",
            "summarizeBy": "sum"
          },
          {
            "name": "Occupation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cb82bd57-df30-4458-b04f-a5b5378eff2e",
            "sourceColumn": "Occupation",
            "summarizeBy": "none"
          },
          {
            "name": "Budget",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "48979cb4-f266-44f4-9a27-0d0d29752e4e",
            "sourceColumn": "Budget",
            "summarizeBy": "none"
          },
          {
            "name": "Age Group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e52718a2-bcd6-4264-8945-397d2ea2acea",
            "sourceColumn": "Age Group",
            "summarizeBy": "none"
          },
          {
            "name": "Full Location",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bdb15d5b-965e-46e5-8466-2ad8ce3f528b",
            "sourceColumn": "Full Location",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "bf89ce0b-e99d-4443-a89d-84e8f83126a2",
        "partitions": [
          {
            "name": "dim_consumers",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"E:\\GitHub projects\\Power-BI-Portfolio\\Mexico Restaurant Ratings Dashboard\\Mexico Restaurant Ratings.Dataset\\consumers.csv\"),[Delimiter=\",\", Columns=14, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Consumer_ID\", type text}, {\"City\", type text}, {\"State\", type text}, {\"Country\", type text}, {\"Latitude\", type text}, {\"Longitude\", type text}, {\"Smoker\", type text}, {\"Drink_Level\", type text}, {\"Transportation_Method\", type text}, {\"Marital_Status\", type text}, {\"Children\", type text}, {\"Age\", Int64.Type}, {\"Occupation\", type text}, {\"Budget\", type text}}),",
                "    #\"Replaced Latitude delimiter\" = Table.ReplaceValue(#\"Changed Type\",\".\",\",\",Replacer.ReplaceText,{\"Latitude\"}),",
                "    #\"Changed Type Latitude\" = Table.TransformColumnTypes(#\"Replaced Latitude delimiter\",{{\"Latitude\", type number}}),",
                "    #\"Replaced Longitude delimiter\" = Table.ReplaceValue(#\"Changed Type Latitude\",\".\",\",\",Replacer.ReplaceText,{\"Longitude\"}),",
                "    #\"Changed Type Longitude\" = Table.TransformColumnTypes(#\"Replaced Longitude delimiter\",{{\"Longitude\", type number}}),",
                "    #\"Added Column Age Group\" = Table.AddColumn(#\"Changed Type Longitude\", \"Age Group\", each if [Age] >= 18 and [Age] <= 24 then \"18-24\"",
                "else if [Age] >= 25 and [Age] <= 35 then \"25-35\"",
                "else if [Age] >= 35 and [Age] <= 54 then \"35-54\"",
                "else \"55+\"),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Added Column Age Group\",{\"Consumer_ID\", \"City\", \"State\", \"Country\", \"Latitude\", \"Longitude\", \"Smoker\", \"Drink_Level\", \"Transportation_Method\", \"Marital_Status\", \"Children\", \"Age\", \"Age Group\", \"Occupation\", \"Budget\"}),",
                "    #\"Inserted Merged Column Full Location\" = Table.AddColumn(#\"Reordered Columns\", \"Full Location\", each Text.Combine({[City], [State], [Country]}, \",\"), type text),",
                "    #\"Replaced Full Location delimiter\" = Table.ReplaceValue(#\"Inserted Merged Column Full Location\",\",\",\", \",Replacer.ReplaceText,{\"Full Location\"}),",
                "    #\"Reordered Columns1\" = Table.ReorderColumns(#\"Replaced Full Location delimiter\",{\"Consumer_ID\", \"City\", \"State\", \"Country\", \"Full Location\", \"Latitude\", \"Longitude\", \"Smoker\", \"Drink_Level\", \"Transportation_Method\", \"Marital_Status\", \"Children\", \"Age\", \"Age Group\", \"Occupation\", \"Budget\"}),",
                "    #\"Replaced Value empty values in Budget\" = Table.ReplaceValue(#\"Reordered Columns1\",\"\",\"Not Specified\",Replacer.ReplaceValue,{\"Budget\"}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Replaced Value empty values in Budget\",\"\",\"Not Specified\",Replacer.ReplaceValue,{\"Transportation_Method\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",\"\",\"Not Specified\",Replacer.ReplaceValue,{\"Marital_Status\"}),",
                "    #\"Replaced Value2\" = Table.ReplaceValue(#\"Replaced Value1\",\"\",\"Not Specified\",Replacer.ReplaceValue,{\"Children\"}),",
                "    #\"Replaced Value3\" = Table.ReplaceValue(#\"Replaced Value2\",\"\",\"Not Specified\",Replacer.ReplaceValue,{\"Occupation\"}),",
                "    #\"Replaced Value4\" = Table.ReplaceValue(#\"Replaced Value3\",\"\",\"Not Specified\",Replacer.ReplaceValue,{\"Smoker\"})",
                "in",
                "    #\"Replaced Value4\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "fact_ratings",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Consumer_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "617c0513-b641-4fe7-bb5a-1ab606a9dac3",
            "sourceColumn": "Consumer_ID",
            "summarizeBy": "none"
          },
          {
            "name": "Restaurant_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7cb0dba3-b5ee-4c19-bc1a-f8c516245301",
            "sourceColumn": "Restaurant_ID",
            "summarizeBy": "none"
          },
          {
            "name": "Overall_Rating",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5acf2d43-705c-43eb-90f9-33722423a839",
            "sourceColumn": "Overall_Rating",
            "summarizeBy": "sum"
          },
          {
            "name": "Food_Rating",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "696999e7-5191-446e-a678-331fb0d70ef3",
            "sourceColumn": "Food_Rating",
            "summarizeBy": "sum"
          },
          {
            "name": "Service_Rating",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e8246459-24f3-4714-8475-b14959b886a0",
            "sourceColumn": "Service_Rating",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "ff763fc1-7426-4291-af91-709ed0bda5f0",
        "partitions": [
          {
            "name": "fact_ratings",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"E:\\GitHub projects\\Power-BI-Portfolio\\Mexico Restaurant Ratings Dashboard\\Mexico Restaurant Ratings.Dataset\\ratings.csv\"),[Delimiter=\",\", Columns=5, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Rating Columns Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Consumer_ID\", type text}, {\"Restaurant_ID\", Int64.Type}, {\"Overall_Rating\", Int64.Type}, {\"Food_Rating\", Int64.Type}, {\"Service_Rating\", Int64.Type}})",
                "in",
                "    #\"Changed Rating Columns Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dim_restaurant_cuisines",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Restaurant_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "97d9737f-a753-4a14-8847-89d357d19880",
            "sourceColumn": "Restaurant_ID",
            "summarizeBy": "none"
          },
          {
            "name": "Cuisine",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "afea1670-31c0-4a0e-a2ce-0618840a7f05",
            "sourceColumn": "Cuisine",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "fcfa9edd-8d85-427e-a90a-ade92dd8e592",
        "partitions": [
          {
            "name": "dim_restaurant_cuisines",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"E:\\GitHub projects\\Power-BI-Portfolio\\Mexico Restaurant Ratings Dashboard\\Mexico Restaurant Ratings.Dataset\\restaurant_cuisines.csv\"),[Delimiter=\",\", Columns=2, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Restaurant_ID Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Restaurant_ID\", Int64.Type}, {\"Cuisine\", type text}})",
                "in",
                "    #\"Changed Restaurant_ID Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dim_restaurants",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Restaurant_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c79a1ffc-8a20-400c-8308-3eac7b9019e0",
            "sourceColumn": "Restaurant_ID",
            "summarizeBy": "none"
          },
          {
            "name": "Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7aba9057-1cac-4f6d-97a8-30b004625020",
            "sourceColumn": "Name",
            "summarizeBy": "none"
          },
          {
            "name": "City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d87a41b1-5c69-4a18-8ebb-adf10e555286",
            "sourceColumn": "City",
            "summarizeBy": "none"
          },
          {
            "name": "State",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c444bf13-80ae-40f8-b6d9-3044d2a909a4",
            "sourceColumn": "State",
            "summarizeBy": "none"
          },
          {
            "name": "Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dc63982a-c813-44c4-b076-1a97c6fad034",
            "sourceColumn": "Country",
            "summarizeBy": "none"
          },
          {
            "name": "Latitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "aed551cc-1a4e-4d20-ad9b-c24e87dc389e",
            "sourceColumn": "Latitude",
            "summarizeBy": "sum"
          },
          {
            "name": "Longitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "4186e5b1-adb3-4082-85a5-99f8db225006",
            "sourceColumn": "Longitude",
            "summarizeBy": "sum"
          },
          {
            "name": "Alcohol_Service",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bf6a5e2e-c57c-47f4-890d-a3037ce8a3b6",
            "sourceColumn": "Alcohol_Service",
            "summarizeBy": "none"
          },
          {
            "name": "Smoking_Allowed",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0b2b13df-4d1c-4e17-92f5-9ef8a2c03ebc",
            "sourceColumn": "Smoking_Allowed",
            "summarizeBy": "none"
          },
          {
            "name": "Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3bffb644-b9ed-4a69-8db8-1952881f0ab6",
            "sourceColumn": "Price",
            "summarizeBy": "none"
          },
          {
            "name": "Franchise",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f31b8dd9-50dc-46f7-9090-ee0b62819687",
            "sourceColumn": "Franchise",
            "summarizeBy": "none"
          },
          {
            "name": "Area",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "07ad01fa-c363-48fa-970f-8b87d5d531ef",
            "sourceColumn": "Area",
            "summarizeBy": "none"
          },
          {
            "name": "Parking",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "61eb1357-3bfa-4b99-9757-886cf908e18a",
            "sourceColumn": "Parking",
            "summarizeBy": "none"
          },
          {
            "name": "Full Location",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1738cd90-2c4b-4b04-a4be-7584b3e6adb9",
            "sourceColumn": "Full Location",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "edee11a2-3ff7-4bdd-be21-010d352e869b",
        "partitions": [
          {
            "name": "dim_restaurants",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"E:\\GitHub projects\\Power-BI-Portfolio\\Mexico Restaurant Ratings Dashboard\\Mexico Restaurant Ratings.Dataset\\restaurants.csv\"),[Delimiter=\",\", Columns=14, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Restaurant_ID Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Restaurant_ID\", Int64.Type}, {\"Name\", type text}, {\"City\", type text}, {\"State\", type text}, {\"Country\", type text}, {\"Zip_Code\", Int64.Type}, {\"Latitude\", type text}, {\"Longitude\", type text}, {\"Alcohol_Service\", type text}, {\"Smoking_Allowed\", type text}, {\"Price\", type text}, {\"Franchise\", type text}, {\"Area\", type text}, {\"Parking\", type text}}),",
                "    #\"Replaced Latitude delimiter\" = Table.ReplaceValue(#\"Changed Restaurant_ID Type\",\".\",\",\",Replacer.ReplaceText,{\"Latitude\"}),",
                "    #\"Changed Latitude Type\" = Table.TransformColumnTypes(#\"Replaced Latitude delimiter\",{{\"Latitude\", type number}}),",
                "    #\"Replaced Longitude delimiter\" = Table.ReplaceValue(#\"Changed Latitude Type\",\".\",\",\",Replacer.ReplaceText,{\"Longitude\"}),",
                "    #\"Changed Longitude Type\" = Table.TransformColumnTypes(#\"Replaced Longitude delimiter\",{{\"Longitude\", type number}}),",
                "    #\"Inserted Merged Column Full Location\" = Table.AddColumn(#\"Changed Longitude Type\", \"Full Location\", each Text.Combine({[City], [State], [Country]}, \",\"), type text),",
                "    #\"Replaced Full Location delimiter\" = Table.ReplaceValue(#\"Inserted Merged Column Full Location\",\",\",\", \",Replacer.ReplaceText,{\"Full Location\"}),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Replaced Full Location delimiter\",{\"Restaurant_ID\", \"Name\", \"City\", \"State\", \"Country\", \"Full Location\", \"Zip_Code\", \"Latitude\", \"Longitude\", \"Alcohol_Service\", \"Smoking_Allowed\", \"Price\", \"Franchise\", \"Area\", \"Parking\"}),",
                "    #\"Removed Column Zip Code\" = Table.RemoveColumns(#\"Reordered Columns\",{\"Zip_Code\"})",
                "in",
                "    #\"Removed Column Zip Code\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "metrics",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "changedProperties": [
          {
            "property": "Name"
          }
        ],
        "lineageTag": "575b3884-12da-44c6-a101-6457f52593de",
        "measures": [
          {
            "name": "Average_Ratings",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "(AVERAGE(fact_ratings[Overall_Rating]) + AVERAGE(fact_ratings[Food_Rating]) + AVERAGE(fact_ratings[Service_Rating])) / 3",
            "lineageTag": "757dc36c-218d-46a5-a9f9-d4e14de06779"
          },
          {
            "name": "Top Rated Restaurant Name",
            "expression": [
              "",
              "VAR MaxRating = MAXX(ALLSELECTED(dim_restaurants), [Average_Ratings])",
              "RETURN",
              "    CALCULATE(",
              "        SELECTEDVALUE(dim_restaurants[Name]),",
              "        FILTER(",
              "            ALLSELECTED(dim_restaurants),",
              "            [Average_Ratings] = MaxRating",
              "        )",
              "    )",
              ""
            ],
            "lineageTag": "0de7f654-83a8-4396-91af-412048446764"
          },
          {
            "name": "Top Rated Restaurant Parking",
            "expression": [
              "",
              "VAR MaxRating = MAXX(ALLSELECTED(dim_restaurants), [Average_Ratings])",
              "VAR TopRestaurant = ",
              "    CALCULATE(",
              "        SELECTEDVALUE(dim_restaurants[Name]),",
              "        FILTER(",
              "            ALLSELECTED(dim_restaurants),",
              "            [Average_Ratings] = MaxRating",
              "        )",
              "    )",
              "RETURN",
              "    LOOKUPVALUE(",
              "        dim_restaurants[Parking], ",
              "        dim_restaurants[Name], TopRestaurant",
              "    )"
            ],
            "lineageTag": "4ddb2858-6c22-4684-83f5-d5b09770bea1"
          },
          {
            "name": "Max_Rating",
            "expression": [
              "",
              "VAR MaxRating = MAXX(ALLSELECTED(dim_restaurants), [Average_Ratings])",
              "VAR TopRestaurant = ",
              "    CALCULATE(",
              "        FIRSTNONBLANK(dim_restaurants[Name], 1),",
              "        FILTER(",
              "            ALLSELECTED(dim_restaurants),",
              "            [Average_Ratings] = MaxRating",
              "        )",
              "    )",
              "RETURN [Top Rated Restaurant Name]"
            ],
            "lineageTag": "1da52cbc-1e25-4977-881b-c1704b510100"
          },
          {
            "name": "Top Rated Restaurant Area",
            "expression": [
              "",
              "VAR MaxRating = MAXX(ALLSELECTED(dim_restaurants), [Average_Ratings])",
              "VAR TopRestaurant = ",
              "    CALCULATE(",
              "        SELECTEDVALUE(dim_restaurants[Name]),",
              "        FILTER(",
              "            ALLSELECTED(dim_restaurants),",
              "            [Average_Ratings] = MaxRating",
              "        )",
              "    )",
              "RETURN",
              "    LOOKUPVALUE(",
              "        dim_restaurants[Area], ",
              "        dim_restaurants[Name], TopRestaurant",
              "    )",
              ""
            ],
            "lineageTag": "19de65ef-89a5-4c67-ba67-939cc5335f2d"
          },
          {
            "name": "Top Rated Restaurant Smoking",
            "expression": [
              "",
              "VAR MaxRating = MAXX(ALLSELECTED(dim_restaurants), [Average_Ratings])",
              "VAR TopRestaurant = ",
              "    CALCULATE(",
              "        SELECTEDVALUE(dim_restaurants[Name]),",
              "        FILTER(",
              "            ALLSELECTED(dim_restaurants),",
              "            [Average_Ratings] = MaxRating",
              "        )",
              "    )",
              "RETURN",
              "    LOOKUPVALUE(",
              "        dim_restaurants[Smoking_Allowed], ",
              "        dim_restaurants[Name], TopRestaurant",
              "    )"
            ],
            "lineageTag": "25d82c21-ae92-4c4a-8538-643e5944150c"
          },
          {
            "name": "Top Rated Restaurant Price",
            "expression": [
              "",
              "VAR MaxRating = MAXX(ALLSELECTED(dim_restaurants), [Average_Ratings])",
              "VAR TopRestaurant = ",
              "    CALCULATE(",
              "        SELECTEDVALUE(dim_restaurants[Name]),",
              "        FILTER(",
              "            ALLSELECTED(dim_restaurants),",
              "            [Average_Ratings] = MaxRating",
              "        )",
              "    )",
              "RETURN",
              "    LOOKUPVALUE(",
              "        dim_restaurants[Price], ",
              "        dim_restaurants[Name], TopRestaurant",
              "    )"
            ],
            "lineageTag": "5ea8e0b2-0964-4679-afdb-a715afbef5a7"
          },
          {
            "name": "Top Rated Restaurant City",
            "expression": [
              "",
              "VAR MaxRating = MAXX(ALLSELECTED(dim_restaurants), [Average_Ratings])",
              "VAR TopRestaurant = ",
              "    CALCULATE(",
              "        SELECTEDVALUE(dim_restaurants[Name]),",
              "        FILTER(",
              "            ALLSELECTED(dim_restaurants),",
              "            [Average_Ratings] = MaxRating",
              "        )",
              "    )",
              "RETURN",
              "    LOOKUPVALUE(",
              "        dim_restaurants[City], ",
              "        dim_restaurants[Name], TopRestaurant",
              "    )"
            ],
            "lineageTag": "d4d80cd9-1ec0-49a6-8e4b-2f6c1164088c"
          },
          {
            "name": "Top Rated Restaurant Country",
            "expression": [
              "",
              "VAR MaxRating = MAXX(ALLSELECTED(dim_restaurants), [Average_Ratings])",
              "VAR TopRestaurant = ",
              "    CALCULATE(",
              "        SELECTEDVALUE(dim_restaurants[Name]),",
              "        FILTER(",
              "            ALLSELECTED(dim_restaurants),",
              "            [Average_Ratings] = MaxRating",
              "        )",
              "    )",
              "RETURN",
              "    LOOKUPVALUE(",
              "        dim_restaurants[Country], ",
              "        dim_restaurants[Name], TopRestaurant",
              "    )"
            ],
            "lineageTag": "b8715294-66f6-4692-b2e9-585a8c9fd992"
          },
          {
            "name": "Top Rated Restaurant Alcohol",
            "expression": [
              "",
              "VAR MaxRating = MAXX(ALLSELECTED(dim_restaurants), [Average_Ratings])",
              "VAR TopRestaurant = ",
              "    CALCULATE(",
              "        SELECTEDVALUE(dim_restaurants[Name]),",
              "        FILTER(",
              "            ALLSELECTED(dim_restaurants),",
              "            [Average_Ratings] = MaxRating",
              "        )",
              "    )",
              "RETURN",
              "    LOOKUPVALUE(",
              "        dim_restaurants[Alcohol_Service], ",
              "        dim_restaurants[Name], TopRestaurant",
              "    )"
            ],
            "lineageTag": "6086d2a3-f408-4cd2-ab12-e43bc74f2e16"
          },
          {
            "name": "Top Rated Restaurant State",
            "expression": [
              "",
              "VAR MaxRating = MAXX(ALLSELECTED(dim_restaurants), [Average_Ratings])",
              "VAR TopRestaurant = ",
              "    CALCULATE(",
              "        SELECTEDVALUE(dim_restaurants[Name]),",
              "        FILTER(",
              "            ALLSELECTED(dim_restaurants),",
              "            [Average_Ratings] = MaxRating",
              "        )",
              "    )",
              "RETURN",
              "    LOOKUPVALUE(",
              "        dim_restaurants[State], ",
              "        dim_restaurants[Name], TopRestaurant",
              "    )"
            ],
            "lineageTag": "a93f5cab-c76d-405f-bcf9-7ea5710eb9f5"
          },
          {
            "name": "Top Rated Restaurant Average Rating",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "VAR MaxRating = MAXX(ALLSELECTED(dim_restaurants), [Average_Ratings])",
              "VAR TopRestaurant = ",
              "    CALCULATE(",
              "        SELECTEDVALUE(dim_restaurants[Name]),",
              "        FILTER(",
              "            ALLSELECTED(dim_restaurants),",
              "            [Average_Ratings] = MaxRating",
              "        )",
              "    )",
              "RETURN",
              "    MaxRating"
            ],
            "lineageTag": "094be0c1-34fc-4373-a6b3-b0fc7db5b201"
          }
        ],
        "partitions": [
          {
            "name": "metrics",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}