{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"spotify-2023\",\"metrics\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.128.751.0 (24.04)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "96135eea-cbcb-46b8-a28f-d7a1a28ef7de",
        "fromColumn": "Date",
        "fromTable": "spotify-2023",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_1b2b0812-baae-4a4f-8adc-8f14496688e6"
      }
    ],
    "sourceQueryCulture": "bg-BG",
    "tables": [
      {
        "name": "spotify-2023",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "track_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b3588a30-c148-4854-9dda-b85048930087",
            "sourceColumn": "track_name",
            "summarizeBy": "none"
          },
          {
            "name": "artist(s)_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1cec81b3-6b95-4cb7-99bb-dcfc28d264fe",
            "sourceColumn": "artist(s)_name",
            "summarizeBy": "none"
          },
          {
            "name": "artist_count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "125ff1d5-e892-4a60-a009-dbe20c94122b",
            "sourceColumn": "artist_count",
            "summarizeBy": "sum"
          },
          {
            "name": "released_year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "14093412-f913-4226-b837-2198eb6ab850",
            "sourceColumn": "released_year",
            "summarizeBy": "sum"
          },
          {
            "name": "released_month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d9002a61-1fac-43d7-80ad-48475a06e7c5",
            "sourceColumn": "released_month",
            "summarizeBy": "sum"
          },
          {
            "name": "released_day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ffc3a4f8-ea92-4922-86c5-1318b945103e",
            "sourceColumn": "released_day",
            "summarizeBy": "sum"
          },
          {
            "name": "in_spotify_playlists",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3306306f-5b9e-4f52-8591-ae757f9e980a",
            "sourceColumn": "in_spotify_playlists",
            "summarizeBy": "sum"
          },
          {
            "name": "in_spotify_charts",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "32675133-4add-40a4-9756-38df8e45ecf1",
            "sourceColumn": "in_spotify_charts",
            "summarizeBy": "sum"
          },
          {
            "name": "streams",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "fe7a5d5b-d7f3-475c-8727-aac18109c64a",
            "sourceColumn": "streams",
            "summarizeBy": "sum"
          },
          {
            "name": "in_apple_playlists",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e2011382-e718-4c4b-accf-fef59ccbcca1",
            "sourceColumn": "in_apple_playlists",
            "summarizeBy": "sum"
          },
          {
            "name": "in_apple_charts",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f226bc17-61d5-4b28-b570-0e995546b86e",
            "sourceColumn": "in_apple_charts",
            "summarizeBy": "sum"
          },
          {
            "name": "in_deezer_playlists",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "1c7fd005-47e6-46f9-94a4-b15274184aac",
            "sourceColumn": "in_deezer_playlists",
            "summarizeBy": "sum"
          },
          {
            "name": "in_deezer_charts",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "fc27cc6e-a218-4700-96ff-52e2e2e8f34d",
            "sourceColumn": "in_deezer_charts",
            "summarizeBy": "sum"
          },
          {
            "name": "in_shazam_charts",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "49ae1b02-cabf-4001-94a8-1eb8b45d7621",
            "sourceColumn": "in_shazam_charts",
            "summarizeBy": "sum"
          },
          {
            "name": "bpm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5216c9d9-a1e9-4113-b5d2-972151056a63",
            "sourceColumn": "bpm",
            "summarizeBy": "sum"
          },
          {
            "name": "key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "54f8fe3d-e1d5-4b42-8d8d-4c378f0e65ea",
            "sourceColumn": "key",
            "summarizeBy": "none"
          },
          {
            "name": "mode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8530fb00-1534-4840-9b87-8eda1c043249",
            "sourceColumn": "mode",
            "summarizeBy": "none"
          },
          {
            "name": "danceability_%",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ff4e64ea-22cc-457e-86ae-dd14b5fd7a62",
            "sourceColumn": "danceability_%",
            "summarizeBy": "sum"
          },
          {
            "name": "valence_%",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3dda8c96-c547-40b5-9d8f-060d35bc746b",
            "sourceColumn": "valence_%",
            "summarizeBy": "sum"
          },
          {
            "name": "energy_%",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "688d6ec4-c37c-4c22-8571-38b440d844f3",
            "sourceColumn": "energy_%",
            "summarizeBy": "sum"
          },
          {
            "name": "acousticness_%",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9c272fc3-6ea7-4a9a-bf7c-fb42f69c6641",
            "sourceColumn": "acousticness_%",
            "summarizeBy": "sum"
          },
          {
            "name": "instrumentalness_%",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c2fdcebc-3e59-4d55-9c2b-8f355441e16e",
            "sourceColumn": "instrumentalness_%",
            "summarizeBy": "sum"
          },
          {
            "name": "liveness_%",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "13110cc9-45cf-42b5-86a5-d8e7ce41a09b",
            "sourceColumn": "liveness_%",
            "summarizeBy": "sum"
          },
          {
            "name": "speechiness_%",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6d92db6f-b132-47e2-88cf-f105041d7d02",
            "sourceColumn": "speechiness_%",
            "summarizeBy": "sum"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "dateTime",
            "expression": "DATE([released_year], [released_month], [released_day])",
            "formatString": "dd/mm/yyyy",
            "isDataTypeInferred": true,
            "lineageTag": "12b4c4b6-d927-46d0-acc0-a3ba95cf9e8d",
            "summarizeBy": "none",
            "type": "calculated",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_1b2b0812-baae-4a4f-8adc-8f14496688e6"
                },
                "isDefault": true,
                "relationship": "96135eea-cbcb-46b8-a28f-d7a1a28ef7de"
              }
            ]
          }
        ],
        "lineageTag": "b151d3ab-5a17-44a4-86b5-7c7a8b5d3f31",
        "partitions": [
          {
            "name": "spotify-2023",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\Nedko\\Desktop\\Work\\Power BI\\Spotify Dashboard\\spotify-2023.csv\"),[Delimiter=\";\", Columns=24, Encoding=1251, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"track_name\", type text}, {\"artist(s)_name\", type text}, {\"artist_count\", Int64.Type}, {\"released_year\", Int64.Type}, {\"released_month\", Int64.Type}, {\"released_day\", Int64.Type}, {\"in_spotify_playlists\", Int64.Type}, {\"in_spotify_charts\", Int64.Type}, {\"streams\", Int64.Type}, {\"in_apple_playlists\", Int64.Type}, {\"in_apple_charts\", Int64.Type}, {\"in_deezer_playlists\", type number}, {\"in_deezer_charts\", Int64.Type}, {\"in_shazam_charts\", type number}, {\"bpm\", Int64.Type}, {\"key\", type text}, {\"mode\", type text}, {\"danceability_%\", Int64.Type}, {\"valence_%\", Int64.Type}, {\"energy_%\", Int64.Type}, {\"acousticness_%\", Int64.Type}, {\"instrumentalness_%\", Int64.Type}, {\"liveness_%\", Int64.Type}, {\"speechiness_%\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_a92a8e29-b2b9-45ef-80b3-b5c7ebe6503c",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "8fff1b99-b80e-4c6f-bfc0-14a33b465870",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "7078f24c-da75-451c-9d5a-e4d92062fbf7",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "a1bcc1b9-d5cf-494d-b9ab-298352a569bd",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "69c52d20-588c-4c86-bf9b-c93cb94ac11d",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "678259bf-c9c6-46c0-872c-cb398f4654d4",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "98220c54-b8e1-41e8-b1cb-897b577bc5df",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "8405e241-6cbd-400e-8c89-cfe53cd34fe9",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "09185a97-bf7e-42bf-ad9b-14f4aa6bc92e",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "d47215b2-78f4-48db-9f75-4675572be98c",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "547c9d5d-3653-405b-80ae-cb92ec9c5a2c",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "cbaf4d14-dd8d-45c5-8a3f-23c3dda44775",
                "ordinal": 3
              }
            ],
            "lineageTag": "67fd368a-4a18-49e2-9a77-28dad9427f6b"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "f696c5c0-1a99-4c6a-9f9e-fa5f22f2968f",
        "partitions": [
          {
            "name": "DateTableTemplate_a92a8e29-b2b9-45ef-80b3-b5c7ebe6503c",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_1b2b0812-baae-4a4f-8adc-8f14496688e6",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "29a85437-7b6c-4c51-9916-6daa0c2ff21a",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "c38d305d-b2f9-4c08-95d2-b509572218d3",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "ed0117a5-a66a-4600-9dcc-3698e0d0fb08",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "1e905629-b31f-4c79-9a85-8a1542d53d65",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "6530f19a-39f9-497e-a8c6-087a32124856",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "5219f6ff-1b0c-4284-8b6d-999023be1d3c",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "465d900d-24e8-44b6-be46-1d9d76e5595f",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "5f22d8fc-a06e-4054-9ad6-72e5f4756e8f",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "7d1941e1-5c2f-4a8a-ac2a-0f57357df5ea",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "d557215b-dcb6-4f27-85bf-073ea4e121ea",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "5b64266d-1e2b-45ea-9671-c982b6dcc5c5",
                "ordinal": 3
              }
            ],
            "lineageTag": "a371dda4-2d37-48d1-81ac-0460d1a2ee49"
          }
        ],
        "isHidden": true,
        "lineageTag": "7d70155c-32ee-4719-bd85-621621137b29",
        "partitions": [
          {
            "name": "LocalDateTable_1b2b0812-baae-4a4f-8adc-8f14496688e6",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('spotify-2023'[Date])), 1, 1), Date(Year(MAX('spotify-2023'[Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "metrics",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Column1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "70929625-854b-419f-add8-d14f3f9357a0",
            "sourceColumn": "Column1",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "cca05b0c-9dab-47e3-9af8-a1cb73f4bf27",
        "measures": [
          {
            "name": "_Track",
            "expression": "count('spotify-2023'[track_name])",
            "formatString": "0",
            "lineageTag": "927fa271-e4af-45c6-9a03-155b5aab704e"
          },
          {
            "name": "_Top song vs avg val",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "DIVIDE(",
              "    [_Top Song streams] - [_Average Stream per years] ,",
              "    [_Average Stream per years]",
              ")"
            ],
            "lineageTag": "51cac574-57d7-4f28-b8fc-d8369392b593"
          },
          {
            "name": "_Top song vs AVG",
            "expression": [
              "",
              "VAR x = [_Top song vs avg val] RETURN",
              "",
              "IF (x > 0,",
              "FORMAT(x, \"#.0%\") & \" \" & UNICHAR ( 9650),",
              "FORMAT(x, \"#.0%\") & \" \" & UNICHAR ( 9660))"
            ],
            "lineageTag": "e070d76a-d225-4252-8ced-9f8a836fcff9"
          },
          {
            "name": "_Top Song streams",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM('spotify-2023'[streams]),",
              "    'spotify-2023'[streams] = MAX('spotify-2023'[streams])",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "6c70f0f7-e475-48f7-a5a3-c5eac4ca84b5"
          },
          {
            "name": "_Percent_Val",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "AVERAGE('spotify-2023'[energy_%])"
            ],
            "lineageTag": "31e7bec8-ddf8-476f-bc28-52386c5afdeb"
          },
          {
            "name": "_Max Streams",
            "expression": "MAX('spotify-2023'[streams])",
            "formatString": "0",
            "lineageTag": "cb16a257-ff44-4598-b54a-a742f3c9bcce"
          },
          {
            "name": "_Average Stream per years",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "    AVERAGE('spotify-2023'[streams]),",
              "    ALLEXCEPT('spotify-2023', 'spotify-2023'[Date].[Year])",
              "    )"
            ],
            "lineageTag": "2e34a4a6-4ac6-468b-8467-82b2d038a9ca"
          }
        ],
        "partitions": [
          {
            "name": "metrics",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}