{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"dimASIN\",\"factSales\",\"metrics\",\"dimInventory\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.130.930.0 (24.06)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Entities": {
              "dim_ASIN": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dimASIN"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "dim ASIN": {
                      "State": "Generated"
                    }
                  },
                  {
                    "dimASIN": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  }
                ]
              },
              "dim_ASIN.SKU__amazon": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dimASIN",
                    "ConceptualProperty": "SKU ( Amazon) "
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "SKU ( amazon)": {
                      "State": "Generated"
                    }
                  },
                  {
                    "SKU": {
                      "State": "Generated",
                      "Weight": 0.75
                    }
                  }
                ]
              },
              "dim_ASIN.asin": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dimASIN",
                    "ConceptualProperty": "ASIN"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "asin": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "dim_inventory": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dimInventory"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "dim inventory": {
                      "State": "Generated"
                    }
                  },
                  {
                    "dimInventory": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "inventory": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "dim portfolio": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "portfolio": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "dim list": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "dim record": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "dim account": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "dim register": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "dim catalogue": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "dim catalog": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "dim roster": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "dim roll": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  }
                ]
              },
              "dim_inventory.TOTAL_INVENTORY_unit": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dimInventory",
                    "ConceptualProperty": "TOTAL INVENTORY Units"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "TOTAL INVENTORY unit": {
                      "State": "Generated"
                    }
                  },
                  {
                    "unit": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "INVENTORY unit": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "total inventory module": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.762
                    }
                  },
                  {
                    "total inventory element": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.762
                    }
                  },
                  {
                    "total inventory entity": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.762
                    }
                  },
                  {
                    "inventory module": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "inventory element": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "inventory entity": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "total inventory group": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.739
                    }
                  },
                  {
                    "total inventory component": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.739
                    }
                  },
                  {
                    "total inventory constituent": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.739
                    }
                  },
                  {
                    "total inventory item": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.739
                    }
                  }
                ]
              },
              "dim_inventory.asin": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "dimInventory",
                    "ConceptualProperty": "ASIN"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "asin": {
                      "State": "Generated"
                    }
                  }
                ],
                "Visibility": {
                  "Value": "Hidden"
                }
              },
              "fact_sales_data": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "factSales"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "fact sale": {
                      "State": "Generated"
                    }
                  },
                  {
                    "factSales": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "sale": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "fact auction": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "auction": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "fact transaction": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.475
                    }
                  },
                  {
                    "transaction": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.466
                    }
                  },
                  {
                    "fact deal": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.461
                    }
                  },
                  {
                    "fact trade": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.461
                    }
                  },
                  {
                    "fact vending": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.461
                    }
                  },
                  {
                    "fact retailing": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.461
                    }
                  },
                  {
                    "fact selling": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.461
                    }
                  },
                  {
                    "deal": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.452
                    }
                  }
                ]
              },
              "fact_sales_data.amazonorderid": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "factSales",
                    "ConceptualProperty": "amazon-order-id"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "amazon-order-id": {
                      "State": "Generated"
                    }
                  },
                  {
                    "amazon order id": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "order": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "amazon order": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "order id": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "amazon-order-identification": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.78
                    }
                  },
                  {
                    "amazon-order-identity": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.78
                    }
                  },
                  {
                    "amazon-order-identifier": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.78
                    }
                  },
                  {
                    "amazon order identification": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.762
                    }
                  },
                  {
                    "amazon order identity": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.762
                    }
                  },
                  {
                    "amazon order identifier": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.762
                    }
                  },
                  {
                    "amazon-order-credential": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.757
                    }
                  },
                  {
                    "order identification": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "order identity": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "order identifier": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  }
                ]
              },
              "fact_sales_data.buyeremail": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "factSales",
                    "ConceptualProperty": "buyer-email"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "buyer-email": {
                      "State": "Generated"
                    }
                  },
                  {
                    "buyer email": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "email": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "buyer-correspondence": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.492
                    }
                  },
                  {
                    "buyer correspondence": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "correspondence": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "buyer-message": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.468
                    }
                  },
                  {
                    "buyer-communication": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.468
                    }
                  },
                  {
                    "buyer message": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.461
                    }
                  },
                  {
                    "buyer communication": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.461
                    }
                  },
                  {
                    "message": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.452
                    }
                  },
                  {
                    "communication": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.452
                    }
                  }
                ]
              },
              "fact_sales_data.carrier": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "factSales",
                    "ConceptualProperty": "carrier"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "carrier": {
                      "State": "Generated"
                    }
                  },
                  {
                    "transporter": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "hauler": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "carter": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "shipper": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "mover": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "exporter": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "importer": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "transferor": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "Carrier Company": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "fact_sales_data.currency": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "factSales",
                    "ConceptualProperty": "currency"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "currency": {
                      "State": "Generated"
                    }
                  },
                  {
                    "money": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "coinage": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "exchange": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "cash": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "prevalence": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.466
                    }
                  },
                  {
                    "frequency": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.466
                    }
                  },
                  {
                    "popularity": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.466
                    }
                  },
                  {
                    "vogue": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.466
                    }
                  },
                  {
                    "circulation": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.466
                    }
                  },
                  {
                    "commonness": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.466
                    }
                  }
                ]
              },
              "fact_sales_data.itemprice": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "factSales",
                    "ConceptualProperty": "item-price"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "item-price": {
                      "State": "Generated"
                    }
                  },
                  {
                    "item price": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "price": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "product -price": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.609
                    }
                  },
                  {
                    "element -price": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.609
                    }
                  },
                  {
                    "entry -price": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.609
                    }
                  },
                  {
                    "product price": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "element price": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "entry price": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "article -price": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.591
                    }
                  },
                  {
                    "object -price": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.591
                    }
                  },
                  {
                    "piece -price": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.591
                    }
                  },
                  {
                    "token -price": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.591
                    }
                  }
                ]
              },
              "fact_sales_data.itempromotiondiscount": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "factSales",
                    "ConceptualProperty": "item-promotion-discount"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "item-promotion-discount": {
                      "State": "Generated"
                    }
                  },
                  {
                    "item promotion discount": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "discount": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "promotion discount": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "product -promotion-discount": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.624
                    }
                  },
                  {
                    "element -promotion-discount": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.624
                    }
                  },
                  {
                    "entry -promotion-discount": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.624
                    }
                  },
                  {
                    "product promotion discount": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.609
                    }
                  },
                  {
                    "element promotion discount": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.609
                    }
                  },
                  {
                    "entry promotion discount": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.609
                    }
                  },
                  {
                    "article -promotion-discount": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.605
                    }
                  },
                  {
                    "object -promotion-discount": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.605
                    }
                  },
                  {
                    "piece -promotion-discount": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.605
                    }
                  },
                  {
                    "token -promotion-discount": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.605
                    }
                  }
                ]
              },
              "fact_sales_data.purchasedate": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "factSales",
                    "ConceptualProperty": "purchase-date"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "purchase-date": {
                      "State": "Generated"
                    }
                  },
                  {
                    "date": {
                      "State": "Generated",
                      "Weight": 0.7
                    }
                  },
                  {
                    "purchase date": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "purchase-moment": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.762
                    }
                  },
                  {
                    "purchase moment": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "purchase-period": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.739
                    }
                  },
                  {
                    "purchase period": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  }
                ]
              },
              "fact_sales_data.purchasedate.variation.date_hierarchy": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "factSales",
                    "Hierarchy": "Date Hierarchy",
                    "VariationSet": "Variation",
                    "VariationSource": "purchase-date"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "purchase - date hierarchy": {
                      "State": "Generated"
                    }
                  },
                  {
                    "date hierarchy": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "purchase date hierarchy": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  }
                ]
              },
              "fact_sales_data.purchasedate.variation.date_hierarchy.day": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "factSales",
                    "Hierarchy": "Date Hierarchy",
                    "HierarchyLevel": "Day",
                    "VariationSet": "Variation",
                    "VariationSource": "purchase-date"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "purchase - day": {
                      "State": "Generated"
                    }
                  },
                  {
                    "day": {
                      "State": "Generated"
                    }
                  },
                  {
                    "purchase-date day": {
                      "State": "Generated"
                    }
                  },
                  {
                    "purchase day": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "purchase date day": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "date day": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "purchase-moment day": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.617
                    }
                  },
                  {
                    "purchase moment day": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.609
                    }
                  },
                  {
                    "moment day": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "purchase-period day": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.599
                    }
                  },
                  {
                    "purchase period day": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.591
                    }
                  },
                  {
                    "period day": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  }
                ]
              },
              "fact_sales_data.purchasedate.variation.date_hierarchy.month": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "factSales",
                    "Hierarchy": "Date Hierarchy",
                    "HierarchyLevel": "Month",
                    "VariationSet": "Variation",
                    "VariationSource": "purchase-date"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "purchase - month": {
                      "State": "Generated"
                    }
                  },
                  {
                    "month": {
                      "State": "Generated"
                    }
                  },
                  {
                    "purchase-date month": {
                      "State": "Generated"
                    }
                  },
                  {
                    "purchase month": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "purchase date month": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "date month": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "purchase-date mth": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.771
                    }
                  },
                  {
                    "purchase - mth": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.762
                    }
                  },
                  {
                    "purchase date mth": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.762
                    }
                  },
                  {
                    "purchase mth": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "date mth": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "mth": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "purchase-moment month": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.617
                    }
                  },
                  {
                    "purchase moment month": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.609
                    }
                  },
                  {
                    "moment month": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "purchase-period month": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.599
                    }
                  }
                ]
              },
              "fact_sales_data.purchasedate.variation.date_hierarchy.quarter": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "factSales",
                    "Hierarchy": "Date Hierarchy",
                    "HierarchyLevel": "Quarter",
                    "VariationSet": "Variation",
                    "VariationSource": "purchase-date"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "purchase - quarter": {
                      "State": "Generated"
                    }
                  },
                  {
                    "quarter": {
                      "State": "Generated"
                    }
                  },
                  {
                    "purchase-date quarter": {
                      "State": "Generated"
                    }
                  },
                  {
                    "purchase quarter": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "purchase date quarter": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "date quarter": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "purchase-date qtr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.857
                    }
                  },
                  {
                    "purchase - qtr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.846
                    }
                  },
                  {
                    "purchase date qtr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.846
                    }
                  },
                  {
                    "purchase qtr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.833
                    }
                  },
                  {
                    "date qtr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.833
                    }
                  },
                  {
                    "qtr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.818
                    }
                  },
                  {
                    "purchase-moment quarter": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.617
                    }
                  },
                  {
                    "purchase moment quarter": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.609
                    }
                  },
                  {
                    "moment quarter": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "purchase-period quarter": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.599
                    }
                  }
                ]
              },
              "fact_sales_data.purchasedate.variation.date_hierarchy.year": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "factSales",
                    "Hierarchy": "Date Hierarchy",
                    "HierarchyLevel": "Year",
                    "VariationSet": "Variation",
                    "VariationSource": "purchase-date"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "purchase - year": {
                      "State": "Generated"
                    }
                  },
                  {
                    "year": {
                      "State": "Generated"
                    }
                  },
                  {
                    "purchase-date year": {
                      "State": "Generated"
                    }
                  },
                  {
                    "purchase year": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "purchase date year": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "date year": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "purchase-date yr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.771
                    }
                  },
                  {
                    "purchase - yr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.762
                    }
                  },
                  {
                    "purchase date yr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.762
                    }
                  },
                  {
                    "purchase yr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "date yr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "yr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "purchase-moment year": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.617
                    }
                  },
                  {
                    "purchase moment year": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.609
                    }
                  },
                  {
                    "moment year": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "purchase-period year": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.599
                    }
                  }
                ]
              },
              "fact_sales_data.quantityshipped": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "factSales",
                    "ConceptualProperty": "quantity-shipped"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "quantity-shipped": {
                      "State": "Generated"
                    }
                  },
                  {
                    "quantity shipped": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "extent shipped": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "magnitude shipped": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "amount shipped": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "number shipped": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "measure shipped": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "size shipped": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "capacity shipped": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "mass shipped": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  }
                ]
              },
              "fact_sales_data.saleschannel": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "factSales",
                    "ConceptualProperty": "sales-channel"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "sales-channel": {
                      "State": "Generated"
                    }
                  },
                  {
                    "sale-channel": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.78
                    }
                  },
                  {
                    "sales channel": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "sale channel": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.7566
                    }
                  },
                  {
                    "channel": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "sale -channel": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.591
                    }
                  },
                  {
                    "sale-frequency": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.508
                    }
                  },
                  {
                    "sale frequency": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "sale-station": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.492
                    }
                  },
                  {
                    "sale-network": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.492
                    }
                  },
                  {
                    "frequency": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "sale station": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "sale network": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "sale-conduit": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.482
                    }
                  }
                ]
              },
              "fact_sales_data.shipcountry": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "factSales",
                    "ConceptualProperty": "ship-country"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "ship-country": {
                      "State": "Generated"
                    }
                  },
                  {
                    "ship country": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "country": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "ship-nation": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.762
                    }
                  },
                  {
                    "ship-location": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.762
                    }
                  },
                  {
                    "ship nation": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "ship location": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "nation": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "location": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  }
                ]
              },
              "fact_sales_data.shippostalcode": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "factSales",
                    "ConceptualProperty": "ship-postal-code"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "ship-postal-code": {
                      "State": "Generated"
                    }
                  },
                  {
                    "ship postal code": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "ship-postal-id": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.78
                    }
                  },
                  {
                    "ship postal id": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.762
                    }
                  },
                  {
                    "ship-postal-key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.757
                    }
                  },
                  {
                    "ship postal key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.739
                    }
                  }
                ]
              },
              "fact_sales_data.shippromotiondiscount": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "factSales",
                    "ConceptualProperty": "ship-promotion-discount"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "ship-promotion-discount": {
                      "State": "Generated"
                    }
                  },
                  {
                    "ship promotion discount": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "discount": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "promotion discount": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "ship-promotion-reduction": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.52
                    }
                  },
                  {
                    "ship-promotion-markdown": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.52
                    }
                  },
                  {
                    "ship-promotion-concession": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.52
                    }
                  },
                  {
                    "ship-promotion-deduction": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.52
                    }
                  },
                  {
                    "ship promotion reduction": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.508
                    }
                  },
                  {
                    "ship promotion markdown": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.508
                    }
                  },
                  {
                    "ship promotion concession": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.508
                    }
                  },
                  {
                    "ship promotion deduction": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.508
                    }
                  },
                  {
                    "ship-promotion-rebate": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.504
                    }
                  },
                  {
                    "promotion reduction": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  }
                ]
              },
              "fact_sales_data.shipservicelevel": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "factSales",
                    "ConceptualProperty": "ship-service-level"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "ship-service-level": {
                      "State": "Generated"
                    }
                  },
                  {
                    "ship service level": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "level": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "service level": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "ship-service-quantity": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.78
                    }
                  },
                  {
                    "ship-service-threshold": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.78
                    }
                  },
                  {
                    "ship service quantity": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.762
                    }
                  },
                  {
                    "ship service threshold": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.762
                    }
                  },
                  {
                    "ship-service-amount": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.757
                    }
                  },
                  {
                    "ship-service-grade": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.757
                    }
                  },
                  {
                    "ship-service-point": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.757
                    }
                  },
                  {
                    "ship-service-rank": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.757
                    }
                  },
                  {
                    "ship-service-tier": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.757
                    }
                  },
                  {
                    "service quantity": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  }
                ]
              },
              "fact_sales_data.sku": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "factSales",
                    "ConceptualProperty": "sku"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "sku": {
                      "State": "Generated"
                    }
                  },
                  {
                    "Product Name": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ],
                "Visibility": {
                  "Value": "Hidden"
                }
              },
              "fact_sales_data.week_number": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "factSales",
                    "ConceptualProperty": "WeekNumber"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "week number": {
                      "State": "Generated"
                    }
                  },
                  {
                    "WeekNumber": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "week no": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  }
                ]
              },
              "metrics": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "metrics"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "metrics": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "metrics.current_inventory": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "metrics",
                    "ConceptualProperty": "CurrentInventory"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "current inventory": {
                      "State": "Generated"
                    }
                  },
                  {
                    "CurrentInventory": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "inventory": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "latest inventory": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  },
                  {
                    "contemporary inventory": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  },
                  {
                    "present inventory": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  },
                  {
                    "current portfolio": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "portfolio": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "current list": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "current record": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "current account": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "current register": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "current catalogue": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  }
                ]
              },
              "metrics.most_profitable_product": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "metrics",
                    "ConceptualProperty": "MostProfitableProduct"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "most profitable product": {
                      "State": "Generated"
                    }
                  },
                  {
                    "MostProfitableProduct": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "most profitable artifact": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.762
                    }
                  },
                  {
                    "most profitable item": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.739
                    }
                  },
                  {
                    "most profitable merchandise": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.739
                    }
                  },
                  {
                    "most profitable produce": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.739
                    }
                  }
                ]
              },
              "metrics.net_sales_amount": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "metrics",
                    "ConceptualProperty": "NetSalesAmount"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "net sales amount": {
                      "State": "Generated"
                    }
                  },
                  {
                    "NetSalesAmount": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "sales": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "net sales": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "sales amount": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "net sale": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "net sale amount": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.591
                    }
                  },
                  {
                    "sale amount": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  },
                  {
                    "net sale quantity": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.508
                    }
                  },
                  {
                    "net sale volume": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.508
                    }
                  },
                  {
                    "net sale expanse": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.508
                    }
                  },
                  {
                    "net sale extent": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.508
                    }
                  },
                  {
                    "sale quantity": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "sale volume": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "sale expanse": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  }
                ]
              }
            },
            "Language": "en-US",
            "Relationships": {
              "dim_ASIN_has_SKU__amazon": {
                "Binding": {
                  "ConceptualEntity": "dimASIN"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "dim_ASIN.SKU__amazon"
                      },
                      "Subject": {
                        "Role": "dim_ASIN"
                      }
                    },
                    "ID": "dim_ASINs_have_SKU__amazon",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "dim_ASIN": {
                    "Target": {
                      "Entity": "dim_ASIN"
                    }
                  },
                  "dim_ASIN.SKU__amazon": {
                    "Target": {
                      "Entity": "dim_ASIN.SKU__amazon"
                    }
                  }
                },
                "State": "Generated"
              },
              "dim_ASIN_has_asin": {
                "Binding": {
                  "ConceptualEntity": "dimASIN"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "dim_ASIN.asin"
                      },
                      "Subject": {
                        "Role": "dim_ASIN"
                      }
                    },
                    "ID": "dim_ASINs_have_asins",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "dim_ASIN": {
                    "Target": {
                      "Entity": "dim_ASIN"
                    }
                  },
                  "dim_ASIN.asin": {
                    "Target": {
                      "Entity": "dim_ASIN.asin"
                    }
                  }
                },
                "State": "Generated"
              },
              "dim_inventory_has_TOTAL_INVENTORY_unit": {
                "Binding": {
                  "ConceptualEntity": "dimInventory"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "dim_inventory.TOTAL_INVENTORY_unit"
                      },
                      "Subject": {
                        "Role": "dim_inventory"
                      }
                    },
                    "ID": "dim_inventories_have_TOTAL_INVENTORY_units",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "dim_inventory": {
                    "Target": {
                      "Entity": "dim_inventory"
                    }
                  },
                  "dim_inventory.TOTAL_INVENTORY_unit": {
                    "Target": {
                      "Entity": "dim_inventory.TOTAL_INVENTORY_unit"
                    }
                  }
                },
                "State": "Generated"
              },
              "dim_inventory_has_dim_ASIN": {
                "Binding": {
                  "ConceptualEntity": "dimInventory"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "dim_ASIN"
                      },
                      "Subject": {
                        "Role": "dim_inventory"
                      }
                    },
                    "ID": "dim_inventories_have_dim_ASINs",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "dim_inventory"
                      },
                      "Subject": {
                        "Role": "dim_ASIN"
                      }
                    },
                    "ID": "dim_ASINs_have_dim_inventories",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "dim_ASIN": {
                    "Target": {
                      "Entity": "dim_ASIN"
                    }
                  },
                  "dim_inventory": {
                    "Target": {
                      "Entity": "dim_inventory"
                    }
                  }
                },
                "State": "Generated"
              },
              "dim_inventory_has_metrics_current_inventory": {
                "Binding": {
                  "ConceptualEntity": "dimInventory"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "metrics.current_inventory"
                      },
                      "Subject": {
                        "Role": "dim_inventory"
                      }
                    },
                    "ID": "dim_inventories_have_current_inventory",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "dim_inventory": {
                    "Target": {
                      "Entity": "dim_inventory"
                    }
                  },
                  "metrics.current_inventory": {
                    "Target": {
                      "Entity": "metrics.current_inventory"
                    }
                  }
                },
                "State": "Generated"
              },
              "fact_sales_data_has_amazonorderid": {
                "Binding": {
                  "ConceptualEntity": "factSales"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "fact_sales_data.amazonorderid"
                      },
                      "Subject": {
                        "Role": "fact_sales_data"
                      }
                    },
                    "ID": "fact_sales_have_amazonorderids",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "fact_sales_data": {
                    "Target": {
                      "Entity": "fact_sales_data"
                    }
                  },
                  "fact_sales_data.amazonorderid": {
                    "Target": {
                      "Entity": "fact_sales_data.amazonorderid"
                    }
                  }
                },
                "State": "Generated"
              },
              "fact_sales_data_has_buyeremail": {
                "Binding": {
                  "ConceptualEntity": "factSales"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "fact_sales_data.buyeremail"
                      },
                      "Subject": {
                        "Role": "fact_sales_data"
                      }
                    },
                    "ID": "fact_sales_have_buyeremails",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "fact_sales_data": {
                    "Target": {
                      "Entity": "fact_sales_data"
                    }
                  },
                  "fact_sales_data.buyeremail": {
                    "Target": {
                      "Entity": "fact_sales_data.buyeremail"
                    }
                  }
                },
                "State": "Generated"
              },
              "fact_sales_data_has_carrier": {
                "Binding": {
                  "ConceptualEntity": "factSales"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "fact_sales_data.carrier"
                      },
                      "Subject": {
                        "Role": "fact_sales_data"
                      }
                    },
                    "ID": "fact_sales_have_carriers",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "ID": "carriers_carry_fact_sales",
                    "State": "Generated",
                    "Verb": {
                      "Object": {
                        "Role": "fact_sales_data"
                      },
                      "Subject": {
                        "Role": "fact_sales_data.carrier"
                      },
                      "Verbs": [
                        {
                          "carry": {
                            "State": "Generated"
                          }
                        }
                      ]
                    },
                    "Weight": 0.75
                  },
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "fact_sales_data"
                      },
                      "Subject": {
                        "Role": "fact_sales_data.carrier"
                      }
                    },
                    "ID": "carriers_have_fact_sales",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "fact_sales_data": {
                    "Target": {
                      "Entity": "fact_sales_data"
                    }
                  },
                  "fact_sales_data.carrier": {
                    "Target": {
                      "Entity": "fact_sales_data.carrier"
                    }
                  }
                },
                "State": "Generated"
              },
              "fact_sales_data_has_currency": {
                "Binding": {
                  "ConceptualEntity": "factSales"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "fact_sales_data.currency"
                      },
                      "Subject": {
                        "Role": "fact_sales_data"
                      }
                    },
                    "ID": "fact_sales_have_currencies",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "fact_sales_data": {
                    "Target": {
                      "Entity": "fact_sales_data"
                    }
                  },
                  "fact_sales_data.currency": {
                    "Target": {
                      "Entity": "fact_sales_data.currency"
                    }
                  }
                },
                "State": "Generated"
              },
              "fact_sales_data_has_dim_ASIN": {
                "Binding": {
                  "ConceptualEntity": "factSales"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "dim_ASIN"
                      },
                      "Subject": {
                        "Role": "fact_sales_data"
                      }
                    },
                    "ID": "fact_sales_have_dim_ASINs",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "fact_sales_data"
                      },
                      "Subject": {
                        "Role": "dim_ASIN"
                      }
                    },
                    "ID": "dim_ASINs_have_fact_sales",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "dim_ASIN": {
                    "Nouns": [
                      {
                        "sku": {
                          "State": "Generated"
                        }
                      }
                    ],
                    "Target": {
                      "Entity": "dim_ASIN"
                    }
                  },
                  "fact_sales_data": {
                    "Target": {
                      "Entity": "fact_sales_data"
                    }
                  }
                },
                "State": "Generated"
              },
              "fact_sales_data_has_itemprice": {
                "Binding": {
                  "ConceptualEntity": "factSales"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "fact_sales_data.itemprice"
                      },
                      "Subject": {
                        "Role": "fact_sales_data"
                      }
                    },
                    "ID": "fact_sales_have_itemprices",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "Adjective": {
                      "Adjectives": [
                        {
                          "expensive": {
                            "State": "Generated"
                          }
                        }
                      ],
                      "Antonyms": [
                        {
                          "cheap": {
                            "State": "Generated"
                          }
                        }
                      ],
                      "Measurement": {
                        "Role": "fact_sales_data.itemprice"
                      },
                      "Subject": {
                        "Role": "fact_sales_data"
                      }
                    },
                    "ID": "itemprice_indicates_how_expensive_fact_sales_are",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "fact_sales_data": {
                    "Target": {
                      "Entity": "fact_sales_data"
                    }
                  },
                  "fact_sales_data.itemprice": {
                    "Target": {
                      "Entity": "fact_sales_data.itemprice"
                    }
                  }
                },
                "State": "Generated"
              },
              "fact_sales_data_has_itempromotiondiscount": {
                "Binding": {
                  "ConceptualEntity": "factSales"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "fact_sales_data.itempromotiondiscount"
                      },
                      "Subject": {
                        "Role": "fact_sales_data"
                      }
                    },
                    "ID": "fact_sales_have_itempromotiondiscounts",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "fact_sales_data": {
                    "Target": {
                      "Entity": "fact_sales_data"
                    }
                  },
                  "fact_sales_data.itempromotiondiscount": {
                    "Target": {
                      "Entity": "fact_sales_data.itempromotiondiscount"
                    }
                  }
                },
                "State": "Generated"
              },
              "fact_sales_data_has_metrics_most_profitable_product": {
                "Binding": {
                  "ConceptualEntity": "factSales"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "metrics.most_profitable_product"
                      },
                      "Subject": {
                        "Role": "fact_sales_data"
                      }
                    },
                    "ID": "fact_sales_have_most_profitable_product",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "fact_sales_data": {
                    "Target": {
                      "Entity": "fact_sales_data"
                    }
                  },
                  "metrics.most_profitable_product": {
                    "Target": {
                      "Entity": "metrics.most_profitable_product"
                    }
                  }
                },
                "State": "Generated"
              },
              "fact_sales_data_has_metrics_net_sales_amount": {
                "Binding": {
                  "ConceptualEntity": "factSales"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "metrics.net_sales_amount"
                      },
                      "Subject": {
                        "Role": "fact_sales_data"
                      }
                    },
                    "ID": "fact_sales_have_net_sales_amount",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "fact_sales_data": {
                    "Target": {
                      "Entity": "fact_sales_data"
                    }
                  },
                  "metrics.net_sales_amount": {
                    "Target": {
                      "Entity": "metrics.net_sales_amount"
                    }
                  }
                },
                "State": "Generated"
              },
              "fact_sales_data_has_purchasedate": {
                "Binding": {
                  "ConceptualEntity": "factSales"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "fact_sales_data.purchasedate"
                      },
                      "Subject": {
                        "Role": "fact_sales_data"
                      }
                    },
                    "ID": "fact_sales_have_purchasedates",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "fact_sales_data": {
                    "Target": {
                      "Entity": "fact_sales_data"
                    }
                  },
                  "fact_sales_data.purchasedate": {
                    "Target": {
                      "Entity": "fact_sales_data.purchasedate"
                    }
                  }
                },
                "State": "Generated"
              },
              "fact_sales_data_has_quantityshipped": {
                "Binding": {
                  "ConceptualEntity": "factSales"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "fact_sales_data.quantityshipped"
                      },
                      "Subject": {
                        "Role": "fact_sales_data"
                      }
                    },
                    "ID": "fact_sales_have_quantityshipped",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "fact_sales_data": {
                    "Target": {
                      "Entity": "fact_sales_data"
                    }
                  },
                  "fact_sales_data.quantityshipped": {
                    "Target": {
                      "Entity": "fact_sales_data.quantityshipped"
                    }
                  }
                },
                "State": "Generated"
              },
              "fact_sales_data_has_saleschannel": {
                "Binding": {
                  "ConceptualEntity": "factSales"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "fact_sales_data.saleschannel"
                      },
                      "Subject": {
                        "Role": "fact_sales_data"
                      }
                    },
                    "ID": "fact_sales_have_saleschannels",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "fact_sales_data": {
                    "Target": {
                      "Entity": "fact_sales_data"
                    }
                  },
                  "fact_sales_data.saleschannel": {
                    "Target": {
                      "Entity": "fact_sales_data.saleschannel"
                    }
                  }
                },
                "State": "Generated"
              },
              "fact_sales_data_has_shipcountry": {
                "Binding": {
                  "ConceptualEntity": "factSales"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "fact_sales_data.shipcountry"
                      },
                      "Subject": {
                        "Role": "fact_sales_data"
                      }
                    },
                    "ID": "fact_sales_have_shipcountries",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "fact_sales_data": {
                    "Target": {
                      "Entity": "fact_sales_data"
                    }
                  },
                  "fact_sales_data.shipcountry": {
                    "Target": {
                      "Entity": "fact_sales_data.shipcountry"
                    }
                  }
                },
                "State": "Generated"
              },
              "fact_sales_data_has_shippostalcode": {
                "Binding": {
                  "ConceptualEntity": "factSales"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "fact_sales_data.shippostalcode"
                      },
                      "Subject": {
                        "Role": "fact_sales_data"
                      }
                    },
                    "ID": "fact_sales_have_shippostalcodes",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "fact_sales_data": {
                    "Target": {
                      "Entity": "fact_sales_data"
                    }
                  },
                  "fact_sales_data.shippostalcode": {
                    "Target": {
                      "Entity": "fact_sales_data.shippostalcode"
                    }
                  }
                },
                "State": "Generated"
              },
              "fact_sales_data_has_shippromotiondiscount": {
                "Binding": {
                  "ConceptualEntity": "factSales"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "fact_sales_data.shippromotiondiscount"
                      },
                      "Subject": {
                        "Role": "fact_sales_data"
                      }
                    },
                    "ID": "fact_sales_have_shippromotiondiscounts",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "fact_sales_data": {
                    "Target": {
                      "Entity": "fact_sales_data"
                    }
                  },
                  "fact_sales_data.shippromotiondiscount": {
                    "Target": {
                      "Entity": "fact_sales_data.shippromotiondiscount"
                    }
                  }
                },
                "State": "Generated"
              },
              "fact_sales_data_has_shipservicelevel": {
                "Binding": {
                  "ConceptualEntity": "factSales"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "fact_sales_data.shipservicelevel"
                      },
                      "Subject": {
                        "Role": "fact_sales_data"
                      }
                    },
                    "ID": "fact_sales_have_shipservicelevels",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "fact_sales_data": {
                    "Target": {
                      "Entity": "fact_sales_data"
                    }
                  },
                  "fact_sales_data.shipservicelevel": {
                    "Target": {
                      "Entity": "fact_sales_data.shipservicelevel"
                    }
                  }
                },
                "State": "Generated"
              },
              "fact_sales_data_has_week_number": {
                "Binding": {
                  "ConceptualEntity": "factSales"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "fact_sales_data.week_number"
                      },
                      "Subject": {
                        "Role": "fact_sales_data"
                      }
                    },
                    "ID": "fact_sales_have_week_numbers",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "fact_sales_data": {
                    "Target": {
                      "Entity": "fact_sales_data"
                    }
                  },
                  "fact_sales_data.week_number": {
                    "Target": {
                      "Entity": "fact_sales_data.week_number"
                    }
                  }
                },
                "State": "Generated"
              },
              "fact_sales_data_in_shipcountry": {
                "Binding": {
                  "ConceptualEntity": "factSales"
                },
                "Phrasings": [
                  {
                    "ID": "fact_sales_are_in_shipcountries",
                    "Preposition": {
                      "Object": {
                        "Role": "fact_sales_data.shipcountry"
                      },
                      "Prepositions": [
                        {
                          "in": {
                            "State": "Generated"
                          }
                        }
                      ],
                      "Subject": {
                        "Role": "fact_sales_data"
                      }
                    },
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "fact_sales_data": {
                    "Target": {
                      "Entity": "fact_sales_data"
                    }
                  },
                  "fact_sales_data.shipcountry": {
                    "Target": {
                      "Entity": "fact_sales_data.shipcountry"
                    }
                  }
                },
                "SemanticSlots": {
                  "Where": {
                    "Role": "fact_sales_data.shipcountry"
                  }
                },
                "State": "Generated"
              },
              "fact_sales_data_in_shippostalcode": {
                "Binding": {
                  "ConceptualEntity": "factSales"
                },
                "Phrasings": [
                  {
                    "ID": "fact_sales_are_in_shippostalcodes",
                    "Preposition": {
                      "Object": {
                        "Role": "fact_sales_data.shippostalcode"
                      },
                      "Prepositions": [
                        {
                          "in": {
                            "State": "Generated"
                          }
                        }
                      ],
                      "Subject": {
                        "Role": "fact_sales_data"
                      }
                    },
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "fact_sales_data": {
                    "Target": {
                      "Entity": "fact_sales_data"
                    }
                  },
                  "fact_sales_data.shippostalcode": {
                    "Target": {
                      "Entity": "fact_sales_data.shippostalcode"
                    }
                  }
                },
                "SemanticSlots": {
                  "Where": {
                    "Role": "fact_sales_data.shippostalcode"
                  }
                },
                "State": "Generated"
              },
              "fact_sales_data_is_purchased_on_purchasedate": {
                "Binding": {
                  "ConceptualEntity": "factSales"
                },
                "Phrasings": [
                  {
                    "ID": "fact_sales_are_purchased_on_purchasedates",
                    "State": "Generated",
                    "Verb": {
                      "Object": {
                        "Role": "fact_sales_data"
                      },
                      "Verbs": [
                        {
                          "purchase": {
                            "State": "Generated"
                          }
                        }
                      ]
                    },
                    "Weight": 0.9
                  }
                ],
                "Roles": {
                  "fact_sales_data": {
                    "Target": {
                      "Entity": "fact_sales_data"
                    }
                  },
                  "fact_sales_data.purchasedate": {
                    "Target": {
                      "Entity": "fact_sales_data.purchasedate"
                    }
                  }
                },
                "SemanticSlots": {
                  "When": {
                    "Role": "fact_sales_data.purchasedate"
                  }
                },
                "State": "Generated"
              },
              "fact_sales_data_purchasedate_has_variation_date_hierarchy": {
                "Binding": {
                  "ConceptualEntity": "factSales"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "fact_sales_data.purchasedate.variation.date_hierarchy"
                      },
                      "Subject": {
                        "Role": "fact_sales_data.purchasedate"
                      }
                    },
                    "ID": "purchasedates_have_purchase__date_hierarchies",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "fact_sales_data.purchasedate": {
                    "Target": {
                      "Entity": "fact_sales_data.purchasedate"
                    }
                  },
                  "fact_sales_data.purchasedate.variation.date_hierarchy": {
                    "Target": {
                      "Entity": "fact_sales_data.purchasedate.variation.date_hierarchy"
                    }
                  }
                },
                "State": "Generated"
              },
              "fact_sales_data_purchasedate_variation_date_hierarchy_has_day": {
                "Binding": {
                  "ConceptualEntity": "factSales"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "fact_sales_data.purchasedate.variation.date_hierarchy.day"
                      },
                      "Subject": {
                        "Role": "fact_sales_data.purchasedate.variation.date_hierarchy"
                      }
                    },
                    "ID": "purchase__date_hierarchies_have_purchase__days",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "fact_sales_data.purchasedate.variation.date_hierarchy": {
                    "Target": {
                      "Entity": "fact_sales_data.purchasedate.variation.date_hierarchy"
                    }
                  },
                  "fact_sales_data.purchasedate.variation.date_hierarchy.day": {
                    "Target": {
                      "Entity": "fact_sales_data.purchasedate.variation.date_hierarchy.day"
                    }
                  }
                },
                "State": "Generated"
              },
              "fact_sales_data_purchasedate_variation_date_hierarchy_has_month": {
                "Binding": {
                  "ConceptualEntity": "factSales"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "fact_sales_data.purchasedate.variation.date_hierarchy.month"
                      },
                      "Subject": {
                        "Role": "fact_sales_data.purchasedate.variation.date_hierarchy"
                      }
                    },
                    "ID": "purchase__date_hierarchies_have_purchase__months",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "fact_sales_data.purchasedate.variation.date_hierarchy": {
                    "Target": {
                      "Entity": "fact_sales_data.purchasedate.variation.date_hierarchy"
                    }
                  },
                  "fact_sales_data.purchasedate.variation.date_hierarchy.month": {
                    "Target": {
                      "Entity": "fact_sales_data.purchasedate.variation.date_hierarchy.month"
                    }
                  }
                },
                "State": "Generated"
              },
              "fact_sales_data_purchasedate_variation_date_hierarchy_has_quarter": {
                "Binding": {
                  "ConceptualEntity": "factSales"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "fact_sales_data.purchasedate.variation.date_hierarchy.quarter"
                      },
                      "Subject": {
                        "Role": "fact_sales_data.purchasedate.variation.date_hierarchy"
                      }
                    },
                    "ID": "purchase__date_hierarchies_have_purchase__quarters",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "fact_sales_data.purchasedate.variation.date_hierarchy": {
                    "Target": {
                      "Entity": "fact_sales_data.purchasedate.variation.date_hierarchy"
                    }
                  },
                  "fact_sales_data.purchasedate.variation.date_hierarchy.quarter": {
                    "Target": {
                      "Entity": "fact_sales_data.purchasedate.variation.date_hierarchy.quarter"
                    }
                  }
                },
                "State": "Generated"
              },
              "fact_sales_data_purchasedate_variation_date_hierarchy_has_year": {
                "Binding": {
                  "ConceptualEntity": "factSales"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "fact_sales_data.purchasedate.variation.date_hierarchy.year"
                      },
                      "Subject": {
                        "Role": "fact_sales_data.purchasedate.variation.date_hierarchy"
                      }
                    },
                    "ID": "purchase__date_hierarchies_have_purchase__years",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "fact_sales_data.purchasedate.variation.date_hierarchy": {
                    "Target": {
                      "Entity": "fact_sales_data.purchasedate.variation.date_hierarchy"
                    }
                  },
                  "fact_sales_data.purchasedate.variation.date_hierarchy.year": {
                    "Target": {
                      "Entity": "fact_sales_data.purchasedate.variation.date_hierarchy.year"
                    }
                  }
                },
                "State": "Generated"
              }
            },
            "Version": "3.5.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "1b7a83ab-80c7-454d-83b5-21984aa12532",
        "fromColumn": "purchase-date",
        "fromTable": "factSales",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_656aa998-7af6-46d8-8075-b920f3a52bbc"
      },
      {
        "name": "6c822889-711b-556a-a5ae-b21c1ef3a8e0",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "sku",
        "fromTable": "factSales",
        "toColumn": "SKU ( Amazon) ",
        "toTable": "dimASIN"
      },
      {
        "name": "50902027-aa15-4998-f1e0-23f8704541a2",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "ASIN",
        "fromTable": "dimInventory",
        "toColumn": "ASIN",
        "toTable": "dimASIN"
      }
    ],
    "sourceQueryCulture": "bg-BG",
    "tables": [
      {
        "name": "dimASIN",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "SKU ( Amazon) ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c89f02c7-d93e-4e87-aec1-76bfe6c92296",
            "sourceColumn": "SKU ( Amazon) ",
            "summarizeBy": "none"
          },
          {
            "name": "ASIN",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f84f82d4-304e-482b-af3c-27147891e896",
            "sourceColumn": "ASIN",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "a22fd179-4c26-4e61-b80f-7827384767dd",
        "partitions": [
          {
            "name": "dimASIN",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\Nedko\\Desktop\\Work\\Power BI\\Sales Data Dashboard\\ASIN.xlsx\"), null, true),",
                "    Sheet2_Sheet = Source{[Item=\"Sheet2\",Kind=\"Sheet\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Sheet2_Sheet,{{\"Column1\", type text}, {\"Column2\", type text}}),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Changed Type\", [PromoteAllScalars=true]),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"SKU ( Amazon) \", type text}, {\"ASIN\", type text}}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Changed Type1\", {\"ASIN\"}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Removed Duplicates\",\"&amp;\",\"&\",Replacer.ReplaceText,{\"SKU ( Amazon) \"})",
                "in",
                "    #\"Replaced Value\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_0204fe5a-60d8-45e0-b7b0-ff6c077276dc",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "94b1bbe3-0b94-47ef-bbec-724b0e22ca65",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "62092200-c5a1-45e1-bf38-f28b30ad3706",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "65ac748b-142c-458b-9d7e-358d6af9876c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "bec57864-4d43-4f83-9abe-6be43044f0e4",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "082cb491-47cb-4e3a-8c44-a7a9c92b411d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "3a36dd44-7714-451b-b175-3c4d1d9cd46d",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "337475d8-103a-4bb0-b4b9-6effb66fca83",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "25dd1855-5f31-4859-a5f7-4f5b183dc74c",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "972bacaf-94d1-42e6-9b79-04390cfd294a",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "842b9ee2-2786-45b2-895e-081cdda6e126",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "1b7f85d0-5113-4dec-ad18-7b661c7c693f",
                "ordinal": 3
              }
            ],
            "lineageTag": "9710a8bb-60ea-4a6c-942f-9bbb21895ae1"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "2a5234a5-e03e-4df8-b55b-eadce96bc05d",
        "partitions": [
          {
            "name": "DateTableTemplate_0204fe5a-60d8-45e0-b7b0-ff6c077276dc",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "factSales",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "changedProperties": [
          {
            "property": "Name"
          }
        ],
        "columns": [
          {
            "name": "amazon-order-id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a177d750-0a48-4154-b3bc-5f37d3b5b781",
            "sourceColumn": "amazon-order-id",
            "summarizeBy": "none"
          },
          {
            "name": "purchase-date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd/mm/yyyy",
            "lineageTag": "8ae62d17-7a97-4d10-8e71-a21c2672867e",
            "sourceColumn": "purchase-date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_656aa998-7af6-46d8-8075-b920f3a52bbc"
                },
                "isDefault": true,
                "relationship": "1b7a83ab-80c7-454d-83b5-21984aa12532"
              }
            ]
          },
          {
            "name": "buyer-email",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c413ecef-44ab-4c7a-bc99-1123baa79a74",
            "sourceColumn": "buyer-email",
            "summarizeBy": "none"
          },
          {
            "name": "sku",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "493b660c-6c2a-43ca-bdb0-b1e65cd80c84",
            "sourceColumn": "sku",
            "summarizeBy": "none"
          },
          {
            "name": "quantity-shipped",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2813b5da-3118-43b4-8e78-e10120e825a5",
            "sourceColumn": "quantity-shipped",
            "summarizeBy": "sum"
          },
          {
            "name": "currency",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3cfc572c-6bc3-4187-830e-b42acbf6a0fc",
            "sourceColumn": "currency",
            "summarizeBy": "none"
          },
          {
            "name": "item-price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "47adef28-d36e-4cbc-bc9c-0776b27fd327",
            "sourceColumn": "item-price",
            "summarizeBy": "sum"
          },
          {
            "name": "ship-service-level",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "68ad98a1-61cf-4dcb-bb4a-ddbb22f6bbd4",
            "sourceColumn": "ship-service-level",
            "summarizeBy": "none"
          },
          {
            "name": "ship-postal-code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "70dd34d7-515b-44a9-bb57-30a8777b53c5",
            "sourceColumn": "ship-postal-code",
            "summarizeBy": "none"
          },
          {
            "name": "ship-country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cdd5e0e7-11c7-4518-8f62-408870456b1f",
            "sourceColumn": "ship-country",
            "summarizeBy": "none"
          },
          {
            "name": "item-promotion-discount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f587fccd-4543-4705-a4c9-cc1b9cb88c83",
            "sourceColumn": "item-promotion-discount",
            "summarizeBy": "sum"
          },
          {
            "name": "ship-promotion-discount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "668daab5-1d76-46ea-9302-efeb73bedf81",
            "sourceColumn": "ship-promotion-discount",
            "summarizeBy": "sum"
          },
          {
            "name": "carrier",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1ddb468d-9d59-48b0-8b11-f4cfc0970c8f",
            "sourceColumn": "carrier",
            "summarizeBy": "none"
          },
          {
            "name": "sales-channel",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6011d4b7-e662-4249-a6c3-f1cf11925477",
            "sourceColumn": "sales-channel",
            "summarizeBy": "none"
          },
          {
            "name": "WeekNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "WEEKNUM(factSales[purchase-date], 1)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "3c86e9cf-f327-4517-9083-fa0b0efc044b",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "ffcacacf-7ee6-4ff4-be27-72fe41d1c545",
        "partitions": [
          {
            "name": "factSales",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\Nedko\\Desktop\\Work\\Power BI\\Sales Data Dashboard\\Sales Data.xlsx\"), null, true),",
                "    #\"2170387053601845_Sheet\" = Source{[Item=\"2170387053601845\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"2170387053601845_Sheet\", [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"amazon-order-id\", type text}, {\"purchase-date\", type datetime}, {\"buyer-email\", type text}, {\"sku\", type text}, {\"quantity-shipped\", Int64.Type}, {\"currency\", type text}, {\"item-price\", type number}, {\"ship-service-level\", type text}, {\"ship-postal-code\", type text}, {\"ship-country\", type text}, {\"item-promotion-discount\", type number}, {\"ship-promotion-discount\", type number}, {\"carrier\", type text}, {\"sales-channel\", type text}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Changed Type\",\"&amp;\",\"&\",Replacer.ReplaceText,{\"sku\"})",
                "in",
                "    #\"Replaced Value\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_656aa998-7af6-46d8-8075-b920f3a52bbc",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "ea0de0e1-9b98-4cef-afaf-f7db40a4ecaa",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "da951bda-995f-48f1-98d8-8f652d058d6b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "57658ba4-3737-4d31-bd89-3c3cb1c5abed",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "2430577c-d2f7-4393-9ec2-0005be3f5a8d",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "1d70283a-184a-4cb3-bd16-cdf11a4e94bd",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "378c560f-ea7c-430d-9e01-bdf5d1b33630",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "7c6e771d-aa06-4ae4-874e-9af14af4d98f",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "ed040a50-9e7f-4ab9-8c37-8abaf8a16864",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "bcbf4a9b-272b-4b2c-8a8f-ba1f406c27cc",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "7260c9f0-d841-4ef2-8959-a4c6c1616e62",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "13132c02-0f53-4c6b-a77b-5b002e009b55",
                "ordinal": 3
              }
            ],
            "lineageTag": "90f75bef-e327-4ef4-9ddf-b544a9715722"
          }
        ],
        "isHidden": true,
        "lineageTag": "49d473a2-9935-48f9-b4a1-a3d9a04d75de",
        "partitions": [
          {
            "name": "LocalDateTable_656aa998-7af6-46d8-8075-b920f3a52bbc",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('factSales'[purchase-date])), 1, 1), Date(Year(MAX('factSales'[purchase-date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "metrics",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "lineageTag": "fc24f214-5ed1-4fde-85e6-df53c1fab31a",
        "measures": [
          {
            "name": "NetSalesAmount",
            "expression": [
              "",
              "SUMX(",
              "    factSales,",
              "    (factSales[item-price] - factSales[item-promotion-discount] - factSales[ship-promotion-discount]) * factSales[quantity-shipped]",
              ")"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "1f6953b0-1681-4a52-bd76-63eeb946f713"
          },
          {
            "name": "MostProfitableProduct",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "    MAXX(",
              "        VALUES(factSales[sku]),",
              "        [NetSalesAmount]",
              "    )",
              ")",
              ""
            ],
            "lineageTag": "5d0a97d4-3354-400f-a6b7-c6ba49fd77cf"
          },
          {
            "name": "CurrentInventory",
            "expression": "SUM(dimInventory[TOTAL INVENTORY Units])",
            "formatString": "0",
            "lineageTag": "b29b53a1-d55e-4ca3-98a8-5e78e9276c96"
          }
        ],
        "partitions": [
          {
            "name": "metrics",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dimInventory",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "changedProperties": [
          {
            "property": "Name"
          }
        ],
        "columns": [
          {
            "name": "ASIN",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "827fb976-0ed7-4586-89e6-57fbc33c1756",
            "sourceColumn": "ASIN",
            "summarizeBy": "none"
          },
          {
            "name": "TOTAL INVENTORY Units",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "598179aa-a824-4c6c-a1b2-f556c394834b",
            "sourceColumn": "TOTAL INVENTORY Units",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "1ee2d029-26d9-4061-8bb4-0bac64fa32b2",
        "partitions": [
          {
            "name": "dimInventory",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\Nedko\\Desktop\\Work\\Power BI\\Sales Data Dashboard\\Inventory.xlsx\"), null, true),",
                "    inventory_Sheet = Source{[Item=\"inventory\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(inventory_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"ASIN\", type text}, {\"TOTAL INVENTORY Units\", Int64.Type}}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Changed Type\", each ([TOTAL INVENTORY Units] <> null))",
                "in",
                "    #\"Filtered Rows\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}