{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"dim_Currency\",\"dim_Customer\",\"dim_Product\",\"dim_SalesTerritory\",\"fact_InternetSales\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.124.2028.0 (23.12)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Entities": {
              "measure.productssold": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "#Measure",
                    "ConceptualProperty": "ProductsSold"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Products Sold": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "measure.totalsalesamount": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "#Measure",
                    "ConceptualProperty": "TotalSalesAmount"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Total Sales Amount": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              }
            },
            "Language": "en-US",
            "Version": "2.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "2eaec33f-1d25-4edd-bb17-6aa26ab0e042",
        "fromColumn": "BirthDate",
        "fromTable": "dim_Customer",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_54e739c3-84fa-4439-a286-8f845aa30302"
      },
      {
        "name": "5601c640-ae27-4f7c-90d6-b88be2c748b0",
        "fromColumn": "DateFirstPurchase",
        "fromTable": "dim_Customer",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_1a340ff3-1f64-407a-bf12-80df6f255d0b"
      },
      {
        "name": "f948f8f1-3e9b-4d95-936c-c2de2dc045e8",
        "fromColumn": "OrderDate",
        "fromTable": "fact_InternetSales",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_03523142-955b-4a0d-a2fa-b147be95498b"
      },
      {
        "name": "6a10a2f2-ebca-40c1-a350-da11ce7ee266",
        "fromColumn": "DueDate",
        "fromTable": "fact_InternetSales",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_e842b0ed-90c2-41c8-af23-55612987e3f5"
      },
      {
        "name": "f831c6dd-2276-41bd-b9a7-c2fb287c5023",
        "fromColumn": "ShipDate",
        "fromTable": "fact_InternetSales",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_5b9f202e-4594-4add-8b6e-f9fc0fb11789"
      },
      {
        "name": "03830e5f-760c-45f2-9b04-30faee509114",
        "fromColumn": "CurrencyKey",
        "fromTable": "fact_InternetSales",
        "toColumn": "CurrencyKey",
        "toTable": "dim_Currency"
      },
      {
        "name": "c0621b2c-e31d-4890-99c3-5ba7a9bb0360",
        "fromColumn": "CustomerKey",
        "fromTable": "fact_InternetSales",
        "toColumn": "CustomerKey",
        "toTable": "dim_Customer"
      },
      {
        "name": "08610f31-3e31-4861-b622-79fd2b41f413",
        "fromColumn": "ProductKey",
        "fromTable": "fact_InternetSales",
        "toColumn": "ProductKey",
        "toTable": "dim_Product"
      },
      {
        "name": "779b208e-6dab-46d1-a04c-ed880a157213",
        "fromColumn": "SalesTerritoryKey",
        "fromTable": "fact_InternetSales",
        "toColumn": "SalesTerritoryKey",
        "toTable": "dim_SalesTerritory"
      }
    ],
    "sourceQueryCulture": "bg-BG",
    "tables": [
      {
        "name": "dim_Currency",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "CurrencyKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "85781138-c1ec-4bd0-b63b-2e7401a4f1df",
            "sourceColumn": "CurrencyKey",
            "summarizeBy": "none"
          },
          {
            "name": "CurrencyAlternateKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "00d9c8b4-3db9-4275-9f8c-627a932da9f8",
            "sourceColumn": "CurrencyAlternateKey",
            "summarizeBy": "none"
          },
          {
            "name": "CurrencyName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7f1a25ca-5c71-4a22-88b4-f6d41ab92d09",
            "sourceColumn": "CurrencyName",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "2c7d54ef-25c8-4009-8824-c57d22289964",
        "partitions": [
          {
            "name": "dim_Currency",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\Nedko\\Desktop\\Power BI 365 Data Science\\Task Five\\8_1_section-five-data-extract.xlsx\"), null, true),",
                "    dim_Currency_Sheet = Source{[Item=\"dim_Currency\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(dim_Currency_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"CurrencyKey\", Int64.Type}, {\"CurrencyAlternateKey\", type text}, {\"CurrencyName\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_ed0c525e-8ed0-43c0-afcc-439b800496fe",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "2d103ee2-3c17-4aef-b740-f4ae2fe70166",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "00943dc8-3309-4d98-bfdf-fadbfbe18d86",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "256472ed-d092-4e6b-99dd-39c919e71bb6",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "4b2b6f28-13cf-42fa-a04e-aa40d14d0aff",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "94a5043b-5e42-4c4a-983b-dcc26bbea57a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "4e85d2e9-2b89-4d95-9b10-17b3c1a42b48",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "a20beda0-7cb2-4c88-9c02-f1602862f409",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "bcd95584-9565-4197-a54a-fe98819249ab",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "0bc70c16-8308-4662-83c8-39d1520f4561",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "27310bbf-8215-4492-98c2-cffc20a1a73d",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "a8696e7e-de54-4037-a709-9b8404c09d9b",
                "ordinal": 3
              }
            ],
            "lineageTag": "b2c42cd9-07c8-4040-a259-29f5414dec15"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "ffddef0d-ffdc-4e83-8783-15f6da9ab822",
        "partitions": [
          {
            "name": "DateTableTemplate_ed0c525e-8ed0-43c0-afcc-439b800496fe",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "dim_Customer",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "CustomerKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6d175d27-825b-4e79-857e-539784eec9fe",
            "sourceColumn": "CustomerKey",
            "summarizeBy": "none"
          },
          {
            "name": "GeographyKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a474bdaa-331d-4bee-ab5b-30305cd058e5",
            "sourceColumn": "GeographyKey",
            "summarizeBy": "count"
          },
          {
            "name": "CustomerAlternateKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "338ac8fc-3fdc-424e-8568-477c6f686a6c",
            "sourceColumn": "CustomerAlternateKey",
            "summarizeBy": "none"
          },
          {
            "name": "Title",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "efc83390-27ae-41c1-8316-ab660e62b061",
            "sourceColumn": "Title",
            "summarizeBy": "none"
          },
          {
            "name": "FirstName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7ee63104-8c09-40ad-905a-78ebe8e156ef",
            "sourceColumn": "FirstName",
            "summarizeBy": "none"
          },
          {
            "name": "MiddleName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ec57fcdb-bc62-4589-ab84-76e941dcf2ef",
            "sourceColumn": "MiddleName",
            "summarizeBy": "none"
          },
          {
            "name": "LastName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "67c598fd-20bf-477a-8b34-a566c058a683",
            "sourceColumn": "LastName",
            "summarizeBy": "none"
          },
          {
            "name": "NameStyle",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "52652c02-7fad-42df-a540-9fa05069731b",
            "sourceColumn": "NameStyle",
            "summarizeBy": "sum"
          },
          {
            "name": "BirthDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "13ac4413-eebf-4107-8e9b-76b227c77559",
            "sourceColumn": "BirthDate",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_54e739c3-84fa-4439-a286-8f845aa30302"
                },
                "isDefault": true,
                "relationship": "2eaec33f-1d25-4edd-bb17-6aa26ab0e042"
              }
            ]
          },
          {
            "name": "MaritalStatus",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d1e6dd90-fe79-4191-b78f-9b4623c43619",
            "sourceColumn": "MaritalStatus",
            "summarizeBy": "none"
          },
          {
            "name": "Suffix",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "997e12ad-a3d1-4411-be63-76f4bdf0fa0f",
            "sourceColumn": "Suffix",
            "summarizeBy": "none"
          },
          {
            "name": "Gender",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5bca2156-e16a-423c-8b70-934cb83eb2ca",
            "sourceColumn": "Gender",
            "summarizeBy": "none"
          },
          {
            "name": "EmailAddress",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c3abec2d-9cb4-40d0-88b6-129ea45101d0",
            "sourceColumn": "EmailAddress",
            "summarizeBy": "none"
          },
          {
            "name": "YearlyIncome",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6cffc6a5-cec0-4bbf-8339-59812cb2bd94",
            "sourceColumn": "YearlyIncome",
            "summarizeBy": "sum"
          },
          {
            "name": "TotalChildren",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4bba44f6-c6c1-4651-a8a3-325702b6a26e",
            "sourceColumn": "TotalChildren",
            "summarizeBy": "sum"
          },
          {
            "name": "NumberChildrenAtHome",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "63ada9a5-d12e-4fff-b608-4cd79640ff7e",
            "sourceColumn": "NumberChildrenAtHome",
            "summarizeBy": "sum"
          },
          {
            "name": "EnglishEducation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8ed488cf-4ab7-4325-942e-caa3e3e185b4",
            "sourceColumn": "EnglishEducation",
            "summarizeBy": "none"
          },
          {
            "name": "SpanishEducation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ec60a570-97d1-45f8-9ff5-336bb6426521",
            "sourceColumn": "SpanishEducation",
            "summarizeBy": "none"
          },
          {
            "name": "FrenchEducation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "de32a8cc-8f04-400f-b64e-90357e6f4578",
            "sourceColumn": "FrenchEducation",
            "summarizeBy": "none"
          },
          {
            "name": "EnglishOccupation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f1f87da8-fbbc-49a5-aae6-e285903c793f",
            "sourceColumn": "EnglishOccupation",
            "summarizeBy": "none"
          },
          {
            "name": "SpanishOccupation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c63053f6-bd1b-4468-a545-4fbbeca56b84",
            "sourceColumn": "SpanishOccupation",
            "summarizeBy": "none"
          },
          {
            "name": "FrenchOccupation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "944c3734-ac26-47c6-9c29-d2a1161cc534",
            "sourceColumn": "FrenchOccupation",
            "summarizeBy": "none"
          },
          {
            "name": "HouseOwnerFlag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "bfc6e417-08cf-4734-a771-f203e66be39b",
            "sourceColumn": "HouseOwnerFlag",
            "summarizeBy": "sum"
          },
          {
            "name": "NumberCarsOwned",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "77a20e6f-29ca-4ff3-9c95-05406876968f",
            "sourceColumn": "NumberCarsOwned",
            "summarizeBy": "sum"
          },
          {
            "name": "AddressLine1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e37112cb-4c7d-4315-bb11-4cd24264e3e7",
            "sourceColumn": "AddressLine1",
            "summarizeBy": "none"
          },
          {
            "name": "AddressLine2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f03ed607-1b84-48e6-9370-a8521795849f",
            "sourceColumn": "AddressLine2",
            "summarizeBy": "none"
          },
          {
            "name": "Phone",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "69aef69c-0a96-4cd2-8346-86819fd605c3",
            "sourceColumn": "Phone",
            "summarizeBy": "none"
          },
          {
            "name": "DateFirstPurchase",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "d51c2151-d8e8-41fa-868d-550c394d1093",
            "sourceColumn": "DateFirstPurchase",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_1a340ff3-1f64-407a-bf12-80df6f255d0b"
                },
                "isDefault": true,
                "relationship": "5601c640-ae27-4f7c-90d6-b88be2c748b0"
              }
            ]
          },
          {
            "name": "CommuteDistance",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "925972f9-7a51-42c4-b3b2-30493c54c87a",
            "sourceColumn": "CommuteDistance",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "b6a1f0b4-0b8a-4353-bb9f-56ddb0a66b6b",
        "partitions": [
          {
            "name": "dim_Customer",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\Nedko\\Desktop\\Power BI 365 Data Science\\Task Five\\8_1_section-five-data-extract.xlsx\"), null, true),",
                "    dim_Customer_Sheet = Source{[Item=\"dim_Customer\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(dim_Customer_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"CustomerKey\", Int64.Type}, {\"GeographyKey\", Int64.Type}, {\"CustomerAlternateKey\", type text}, {\"Title\", type text}, {\"FirstName\", type text}, {\"MiddleName\", type text}, {\"LastName\", type text}, {\"NameStyle\", Int64.Type}, {\"BirthDate\", type date}, {\"MaritalStatus\", type text}, {\"Suffix\", type text}, {\"Gender\", type text}, {\"EmailAddress\", type text}, {\"YearlyIncome\", Int64.Type}, {\"TotalChildren\", Int64.Type}, {\"NumberChildrenAtHome\", Int64.Type}, {\"EnglishEducation\", type text}, {\"SpanishEducation\", type text}, {\"FrenchEducation\", type text}, {\"EnglishOccupation\", type text}, {\"SpanishOccupation\", type text}, {\"FrenchOccupation\", type text}, {\"HouseOwnerFlag\", Int64.Type}, {\"NumberCarsOwned\", Int64.Type}, {\"AddressLine1\", type text}, {\"AddressLine2\", type text}, {\"Phone\", type text}, {\"DateFirstPurchase\", type date}, {\"CommuteDistance\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_54e739c3-84fa-4439-a286-8f845aa30302",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "6e772c15-fdd8-4681-aa0d-77fb802992fb",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "fd7da6a4-b99b-41f4-b57c-57b2530dba68",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "fc5ccf5d-8c50-4337-91a2-6158c8a202d8",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "0917d35d-b404-4bc8-bce5-dd2618bc3210",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "e03835dd-fcf3-4f6c-afbb-121e7ec5b108",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "14e19fb0-afa2-4d9c-a902-50ec2d9a4712",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "5272ed41-8183-47d1-b15f-b90cae548677",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "c321dd6b-659d-4f38-88e6-55ec90730448",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "dc7b43cc-970c-42fb-ad95-d7ddf7ecf707",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "66d4140e-3dfa-49d5-89c7-0d26ec37e574",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "86943837-612e-4345-a6f0-e869173106e0",
                "ordinal": 3
              }
            ],
            "lineageTag": "5c82d8b5-0a7e-408a-bc2d-7556a78ca87c"
          }
        ],
        "isHidden": true,
        "lineageTag": "ae273e6b-014d-4d0b-bc3f-e6e99934a7ca",
        "partitions": [
          {
            "name": "LocalDateTable_54e739c3-84fa-4439-a286-8f845aa30302",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('dim_Customer'[BirthDate])), 1, 1), Date(Year(MAX('dim_Customer'[BirthDate])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_1a340ff3-1f64-407a-bf12-80df6f255d0b",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "6167ebd0-eeb3-4b56-9ad1-ea18445e3e4f",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "7a5117cd-2006-4e8e-b38c-333d5be2798b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "5b6ac7b5-7dd4-4da5-9669-68e039a57fb6",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "c46140dd-ba53-4f2a-ad8a-9ff503c8e2d3",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "ce4c9421-d52f-4557-8dc0-7caa1618d1ef",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "7f5f5044-32bf-4fdf-a5a8-7801d6164398",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "a6936c22-5f6f-405f-9503-896fd3b76944",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "16262d78-f1e8-4b26-8835-189128bdfe1b",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "9a04c246-33ab-4206-9143-3d4e965f4040",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "ed6029f9-74b5-439c-8231-82a656f3f6eb",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "692362fc-ed5f-4d00-bf56-2cd8a042644e",
                "ordinal": 3
              }
            ],
            "lineageTag": "8b401d64-b518-4f96-9965-6e57fe24e455"
          }
        ],
        "isHidden": true,
        "lineageTag": "2478211d-f3b0-4d79-b618-638eb05ec3b0",
        "partitions": [
          {
            "name": "LocalDateTable_1a340ff3-1f64-407a-bf12-80df6f255d0b",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('dim_Customer'[DateFirstPurchase])), 1, 1), Date(Year(MAX('dim_Customer'[DateFirstPurchase])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "dim_Product",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ProductKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "91f5e6c8-0bd9-4c87-98f8-db3c47e8cca7",
            "sourceColumn": "ProductKey",
            "summarizeBy": "none"
          },
          {
            "name": "EnglishProductName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eb1f9976-dede-4005-b57b-ac14dfcd08c4",
            "sourceColumn": "EnglishProductName",
            "summarizeBy": "none"
          },
          {
            "name": "Color",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e12e3f1f-07c5-4961-917a-f42d35f215c9",
            "sourceColumn": "Color",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "8a2feadc-2a7e-472b-ab47-b575fb2f0242",
        "partitions": [
          {
            "name": "dim_Product",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\Nedko\\Desktop\\Power BI 365 Data Science\\Task Five\\8_1_section-five-data-extract.xlsx\"), null, true),",
                "    dim_Product_Sheet = Source{[Item=\"dim_Product\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(dim_Product_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"ProductKey\", Int64.Type}, {\"EnglishProductName\", type text}, {\"Color\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dim_SalesTerritory",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "SalesTerritoryKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "28b72476-6613-4eb1-8d20-0113f9132624",
            "sourceColumn": "SalesTerritoryKey",
            "summarizeBy": "none"
          },
          {
            "name": "SalesTerritoryAlternateKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e12f5d19-8d30-4b3e-b852-2d4db3f75fd1",
            "sourceColumn": "SalesTerritoryAlternateKey",
            "summarizeBy": "none"
          },
          {
            "name": "SalesTerritoryRegion",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "01692d4f-79e8-4d36-a19d-16373ab0915f",
            "sourceColumn": "SalesTerritoryRegion",
            "summarizeBy": "none"
          },
          {
            "name": "SalesTerritoryCountry",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "170f4fa2-4950-4f7c-ac46-056493611b05",
            "sourceColumn": "SalesTerritoryCountry",
            "summarizeBy": "none"
          },
          {
            "name": "SalesTerritoryGroup",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f7857d79-6731-4347-a245-c01748d92928",
            "sourceColumn": "SalesTerritoryGroup",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "3005f4e4-ad99-4906-907c-dceaf3de38fa",
        "partitions": [
          {
            "name": "dim_SalesTerritory",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\Nedko\\Desktop\\Power BI 365 Data Science\\Task Five\\8_1_section-five-data-extract.xlsx\"), null, true),",
                "    dim_SalesTerritory_Sheet = Source{[Item=\"dim_SalesTerritory\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(dim_SalesTerritory_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"SalesTerritoryKey\", Int64.Type}, {\"SalesTerritoryAlternateKey\", Int64.Type}, {\"SalesTerritoryRegion\", type text}, {\"SalesTerritoryCountry\", type text}, {\"SalesTerritoryGroup\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "fact_InternetSales",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ProductKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0f8c9335-c668-49b1-9b41-d454259086d2",
            "sourceColumn": "ProductKey",
            "summarizeBy": "none"
          },
          {
            "name": "OrderDateKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ac38362a-c8f8-4801-beb7-e82771c853d1",
            "sourceColumn": "OrderDateKey",
            "summarizeBy": "count"
          },
          {
            "name": "DueDateKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "842bb46a-2fdc-471f-898e-279ff2008e85",
            "sourceColumn": "DueDateKey",
            "summarizeBy": "count"
          },
          {
            "name": "ShipDateKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "601b313f-c8bc-4d54-8c33-97a7c59109ca",
            "sourceColumn": "ShipDateKey",
            "summarizeBy": "count"
          },
          {
            "name": "CustomerKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d8a18c37-ed92-4720-b1eb-2525d286ff65",
            "sourceColumn": "CustomerKey",
            "summarizeBy": "none"
          },
          {
            "name": "PromotionKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7718fd5e-136f-42a5-b082-ef2dfe478d50",
            "sourceColumn": "PromotionKey",
            "summarizeBy": "count"
          },
          {
            "name": "CurrencyKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8752b219-3a99-4968-a5f1-04aecef8a5e5",
            "sourceColumn": "CurrencyKey",
            "summarizeBy": "none"
          },
          {
            "name": "SalesTerritoryKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "743c09f8-7280-4239-a4ff-633ec00523ec",
            "sourceColumn": "SalesTerritoryKey",
            "summarizeBy": "none"
          },
          {
            "name": "SalesOrderNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c6357531-5c93-4653-9900-e12f8b3afc8a",
            "sourceColumn": "SalesOrderNumber",
            "summarizeBy": "none"
          },
          {
            "name": "SalesOrderLineNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "88c79eb6-80e2-4454-831c-121bf183bc32",
            "sourceColumn": "SalesOrderLineNumber",
            "summarizeBy": "sum"
          },
          {
            "name": "RevisionNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f462427d-0b73-4310-804d-f301ae060892",
            "sourceColumn": "RevisionNumber",
            "summarizeBy": "sum"
          },
          {
            "name": "OrderQuantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "59237ab2-db31-49eb-9f0f-e843462e8512",
            "sourceColumn": "OrderQuantity",
            "summarizeBy": "sum"
          },
          {
            "name": "UnitPrice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "9d6987b2-f8b8-454f-a8c4-58c3cbd98e00",
            "sourceColumn": "UnitPrice",
            "summarizeBy": "sum"
          },
          {
            "name": "ExtendedAmount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c30f4230-d4ce-402e-81d2-8f2fbcd66396",
            "sourceColumn": "ExtendedAmount",
            "summarizeBy": "sum"
          },
          {
            "name": "UnitPriceDiscountPct",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4229f250-d50d-4199-a91d-ed91df1e1002",
            "sourceColumn": "UnitPriceDiscountPct",
            "summarizeBy": "sum"
          },
          {
            "name": "DiscountAmount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6e272905-9153-47e4-9b5d-378fd2bb070a",
            "sourceColumn": "DiscountAmount",
            "summarizeBy": "sum"
          },
          {
            "name": "ProductStandardCost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "4e1f05df-40d2-4f62-af83-754edf04407a",
            "sourceColumn": "ProductStandardCost",
            "summarizeBy": "sum"
          },
          {
            "name": "TotalProductCost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "15888720-6e0b-4431-8404-4f4645c4f3f8",
            "sourceColumn": "TotalProductCost",
            "summarizeBy": "sum"
          },
          {
            "name": "SalesAmount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "1ae5802d-9625-4ff5-b9c6-fab2d60fd81d",
            "sourceColumn": "SalesAmount",
            "summarizeBy": "sum"
          },
          {
            "name": "TaxAmt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "34b5c3df-fd4e-4d96-b9b5-56c50df2f55c",
            "sourceColumn": "TaxAmt",
            "summarizeBy": "sum"
          },
          {
            "name": "Freight",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "93ab55d1-ea23-4b20-b94f-8a54a04b76fa",
            "sourceColumn": "Freight",
            "summarizeBy": "sum"
          },
          {
            "name": "CarrierTrackingNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ec2a3c57-fda0-42b9-a27a-bc8c8f6d9947",
            "sourceColumn": "CarrierTrackingNumber",
            "summarizeBy": "none"
          },
          {
            "name": "CustomerPONumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8331fc5e-da63-4e8c-8037-e8c559ba497e",
            "sourceColumn": "CustomerPONumber",
            "summarizeBy": "none"
          },
          {
            "name": "OrderDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "98757cd5-f415-4d7b-be03-2ee9fd5561b1",
            "sourceColumn": "OrderDate",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_03523142-955b-4a0d-a2fa-b147be95498b"
                },
                "isDefault": true,
                "relationship": "f948f8f1-3e9b-4d95-936c-c2de2dc045e8"
              }
            ]
          },
          {
            "name": "DueDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "96b6e868-8cbd-4c3f-91a1-066dee7c9949",
            "sourceColumn": "DueDate",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_e842b0ed-90c2-41c8-af23-55612987e3f5"
                },
                "isDefault": true,
                "relationship": "6a10a2f2-ebca-40c1-a350-da11ce7ee266"
              }
            ]
          },
          {
            "name": "ShipDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "4078f347-1862-4dd5-b0c8-76c48ceff045",
            "sourceColumn": "ShipDate",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_5b9f202e-4594-4add-8b6e-f9fc0fb11789"
                },
                "isDefault": true,
                "relationship": "f831c6dd-2276-41bd-b9a7-c2fb287c5023"
              }
            ]
          }
        ],
        "lineageTag": "793111ee-cb4f-43c9-80dd-98958a2e47ea",
        "partitions": [
          {
            "name": "fact_InternetSales",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\Nedko\\Desktop\\Power BI 365 Data Science\\Task Five\\8_1_section-five-data-extract.xlsx\"), null, true),",
                "    fact_InternetSales_Sheet = Source{[Item=\"fact_InternetSales\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(fact_InternetSales_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"ProductKey\", Int64.Type}, {\"OrderDateKey\", Int64.Type}, {\"DueDateKey\", Int64.Type}, {\"ShipDateKey\", Int64.Type}, {\"CustomerKey\", Int64.Type}, {\"PromotionKey\", Int64.Type}, {\"CurrencyKey\", Int64.Type}, {\"SalesTerritoryKey\", Int64.Type}, {\"SalesOrderNumber\", type text}, {\"SalesOrderLineNumber\", Int64.Type}, {\"RevisionNumber\", Int64.Type}, {\"OrderQuantity\", Int64.Type}, {\"UnitPrice\", type number}, {\"ExtendedAmount\", type number}, {\"UnitPriceDiscountPct\", Int64.Type}, {\"DiscountAmount\", Int64.Type}, {\"ProductStandardCost\", type number}, {\"TotalProductCost\", type number}, {\"SalesAmount\", type number}, {\"TaxAmt\", type number}, {\"Freight\", type number}, {\"CarrierTrackingNumber\", type text}, {\"CustomerPONumber\", type text}, {\"OrderDate\", type datetime}, {\"DueDate\", type datetime}, {\"ShipDate\", type datetime}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_03523142-955b-4a0d-a2fa-b147be95498b",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "cdb8e10b-04bd-4ff2-a6f1-a4c86e82e43b",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "dc465d30-bae4-4742-8f2a-1907a719c79b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "cc9f2159-0534-409b-bc7b-90ffee4aa9db",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "4bcb3c5c-5326-40e0-b8bf-a81361021baa",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "cd7c98f8-956e-45af-80e5-77f6fd515a74",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "f16d7a96-6efc-4de6-99d3-e61ed35d4b15",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "b0c0d935-9950-4aa8-876d-25f31b8f1716",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "792ce839-b256-40f4-a20b-2ee670b916e1",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "2c2f585c-c454-44c4-bb0d-509b672ff791",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "8a0e6cc0-ed47-4cec-88fe-d6773597f1f8",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "a3976ef9-b649-4740-8f07-ae97eaa4e205",
                "ordinal": 3
              }
            ],
            "lineageTag": "dd617bd5-bcbf-4098-86ab-616beff97284"
          }
        ],
        "isHidden": true,
        "lineageTag": "8f043704-43b3-4a72-bf7e-61c58af76d7e",
        "partitions": [
          {
            "name": "LocalDateTable_03523142-955b-4a0d-a2fa-b147be95498b",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('fact_InternetSales'[OrderDate])), 1, 1), Date(Year(MAX('fact_InternetSales'[OrderDate])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_e842b0ed-90c2-41c8-af23-55612987e3f5",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "379799cc-f1da-45c4-9923-f7df2a769c09",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "c6641f23-f9c6-4871-95ba-f16352253434",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "c08cea26-eb9a-4ea7-b2eb-566994dc5546",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "c9eba24f-79ae-44f2-9f75-17e88860c794",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "5b4c2785-6b5c-4a2b-945e-477358480ccb",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "4664b8b3-b625-4ef7-bdb5-c431627e9661",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "a685fb70-6785-454a-b0e6-d18b810c071c",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "12dec2b0-b7ae-4207-a45d-2c9a6128b810",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "b7a0c60e-c49e-4e80-9cdc-ef53f9c83202",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "64f934eb-5df0-4958-b258-ee30dce7b8d3",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "c97c2707-8b29-4e72-9d4a-336737cb5bc2",
                "ordinal": 3
              }
            ],
            "lineageTag": "d2d5c243-e21a-44e8-a633-49eec46bdf1b"
          }
        ],
        "isHidden": true,
        "lineageTag": "865f8f04-7bb4-4051-9fcc-bca774e71d2c",
        "partitions": [
          {
            "name": "LocalDateTable_e842b0ed-90c2-41c8-af23-55612987e3f5",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('fact_InternetSales'[DueDate])), 1, 1), Date(Year(MAX('fact_InternetSales'[DueDate])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_5b9f202e-4594-4add-8b6e-f9fc0fb11789",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "7d005d6f-f0b3-4349-88b2-a4c1af3d311c",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "59ca78af-e935-4cc7-9090-c52677e6b580",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "df2133b5-7abc-4ad9-aa19-7742ee49bc5e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "cd192b71-a4f6-4dc3-8422-f1b67a528aaf",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "03f6fa4d-5b42-44d6-9d57-99ee65c29f17",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "22fb16d2-c828-40cb-9b91-8cf85b34a56e",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "811efd52-5fc3-49e1-85e8-a5be6807de91",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "86a80ece-8db7-4b6d-bee1-bb4ab8258bb2",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "255ef27d-161f-4e0b-8bae-4201b510ccc9",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "6af0259f-afa0-486e-a620-78b51819a419",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "4af7e6e3-9133-4286-a178-6f5eb22a6a45",
                "ordinal": 3
              }
            ],
            "lineageTag": "81036b7a-a2fc-41a5-aeb3-10df407f0064"
          }
        ],
        "isHidden": true,
        "lineageTag": "816ae65d-83e2-4d52-807b-0f3da7cb878c",
        "partitions": [
          {
            "name": "LocalDateTable_5b9f202e-4594-4add-8b6e-f9fc0fb11789",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('fact_InternetSales'[ShipDate])), 1, 1), Date(Year(MAX('fact_InternetSales'[ShipDate])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "#Measure",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "e73693ed26394fb48dc6cb572fd98fc9"
          }
        ],
        "columns": [
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "44b7a8d7-26cf-4090-a058-90640fab7924",
            "sourceColumn": "[Value]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "37bfb8d0-d9cd-4463-b706-e4485b7208c7",
        "measures": [
          {
            "name": "ProductsSold",
            "expression": "COUNTROWS(fact_InternetSales)",
            "formatString": "0",
            "lineageTag": "6d811b06-7dfa-4f91-b586-90a43e928e82"
          },
          {
            "name": "Customers",
            "expression": "COUNTROWS(dim_Customer)",
            "formatString": "0",
            "lineageTag": "712037c0-8db4-49d9-89d0-359580db2a7d"
          },
          {
            "name": "TotalSalesAmount",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "SUM(fact_InternetSales[SalesAmount])",
            "lineageTag": "ff114bc6-c6d0-4fce-b6a5-699b58290731"
          }
        ],
        "partitions": [
          {
            "name": "#Measure",
            "mode": "import",
            "source": {
              "expression": "GENERATESERIES(1,1,1)",
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}