{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"dim_Currency\",\"dim_Customer\",\"dim_Product\",\"dim_SalesTeritory\",\"fact_InternetSales\",\"SwitchTable\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.124.2028.0 (23.12)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "6477dee4-e10f-4e45-bf39-9b847d53050c",
        "fromColumn": "BirthDate",
        "fromTable": "dim_Customer",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_66029369-c4d7-4316-8dfe-15cd5df06050"
      },
      {
        "name": "4f612f2f-55d4-4b34-9cd6-3e8291b70eb4",
        "fromColumn": "DateFirstPurchase",
        "fromTable": "dim_Customer",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_c2dd2b07-7bcf-4557-9382-df7410c1a3d7"
      },
      {
        "name": "1a5320b3-5b0a-4081-8730-cf6f4d892953",
        "fromColumn": "StartDate",
        "fromTable": "dim_Product",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_5b329dcb-4f14-4a14-a60d-6b569e4c8768"
      },
      {
        "name": "8a6d2c0c-f353-45f2-97d2-39bec27d4209",
        "fromColumn": "OrderDate",
        "fromTable": "fact_InternetSales",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_c535fb3e-a130-493f-aea9-b60633804db6"
      },
      {
        "name": "585cedc0-a1a8-47d7-ad86-2abe10c14f12",
        "fromColumn": "DueDate",
        "fromTable": "fact_InternetSales",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_5ab76db6-97c3-404f-93f0-5da8846858f7"
      },
      {
        "name": "37a7be2c-f7b0-452a-8e83-83631ab9f2ba",
        "fromColumn": "ShipDate",
        "fromTable": "fact_InternetSales",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_674de304-6ec6-4631-9875-946aa27bb344"
      },
      {
        "name": "bf4cf5a3-9b16-49d4-a210-29473a2c9578",
        "fromColumn": "CurrencyKey",
        "fromTable": "fact_InternetSales",
        "toColumn": "CurrencyKey",
        "toTable": "dim_Currency"
      },
      {
        "name": "6bb9ccb2-2e53-4ea4-963b-b41f1d0ef4b3",
        "fromColumn": "CustomerKey",
        "fromTable": "fact_InternetSales",
        "toColumn": "CustomerKey",
        "toTable": "dim_Customer"
      },
      {
        "name": "d8ab146d-cc71-4af8-a2ed-f4ce1b748d70",
        "fromColumn": "ProductKey",
        "fromTable": "fact_InternetSales",
        "toColumn": "ProductKey",
        "toTable": "dim_Product"
      },
      {
        "name": "c17a41b5-8927-4fe3-a878-0e3e0d415123",
        "fromColumn": "SalesTerritoryKey",
        "fromTable": "fact_InternetSales",
        "toColumn": "SalesTerritoryKey",
        "toTable": "dim_SalesTeritory"
      }
    ],
    "sourceQueryCulture": "bg-BG",
    "tables": [
      {
        "name": "dim_Currency",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "CurrencyKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "af743d4d-16d8-4122-b209-dbace9d513de",
            "sourceColumn": "CurrencyKey",
            "summarizeBy": "none"
          },
          {
            "name": "CurrencyAlternateKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "91fa7be0-7fdc-4197-a580-bc6b70e87b9c",
            "sourceColumn": "CurrencyAlternateKey",
            "summarizeBy": "none"
          },
          {
            "name": "CurrencyName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b7c71576-4ad3-497b-88d9-869e4e7dc3ae",
            "sourceColumn": "CurrencyName",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "9d33350d-bc89-4865-87b6-371da8ac2fdf",
        "partitions": [
          {
            "name": "dim_Currency",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\Nedko\\Desktop\\Power BI 365 Data Science\\Task Four\\Section Four Data Extract.xlsx\"), null, true),",
                "    dim_Currency_Sheet = Source{[Item=\"dim_Currency\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(dim_Currency_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"CurrencyKey\", Int64.Type}, {\"CurrencyAlternateKey\", type text}, {\"CurrencyName\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_99011be8-f1c8-4a41-bfe9-a9c1e5fe9070",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "f29e8aaf-24e1-4eca-bc1c-68e232f999c9",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "aef05d7b-48db-40c6-9544-bc3e9649cae5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "2627787f-a3e6-4778-89cf-53252543b956",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "5d5a4ead-2f0a-43b7-a45f-9a306de84918",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "636e306f-cc6d-493c-847a-8b345ee3ab1b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "ccf7283b-7740-4d62-8381-743036976249",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "11ba1d6d-cd1f-4b61-bc05-0916fcc09e9c",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "57577bc3-ef72-4f6e-9fec-ddc6f7c9d06d",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "c4bf5cc0-0481-4002-ad94-532f9cb56c4e",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "eccdd8e0-974c-414d-ac58-5053b466ca11",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "2a8ceb32-3516-4bef-89f3-bb927869aefa",
                "ordinal": 3
              }
            ],
            "lineageTag": "4350a957-a7a2-44be-a916-d294222ac69b"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "f0bdca3f-4bd0-4705-8573-fd87cc5c9825",
        "partitions": [
          {
            "name": "DateTableTemplate_99011be8-f1c8-4a41-bfe9-a9c1e5fe9070",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "dim_Customer",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "CustomerKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c915fed6-0bb4-475a-bee0-f14696deabb1",
            "sourceColumn": "CustomerKey",
            "summarizeBy": "none"
          },
          {
            "name": "GeographyKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9aef0444-b917-46ba-8443-f1672c194b45",
            "sourceColumn": "GeographyKey",
            "summarizeBy": "count"
          },
          {
            "name": "CustomerAlternateKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9ffa9c7f-8e05-40b7-b7cc-fbc09e3ba8dc",
            "sourceColumn": "CustomerAlternateKey",
            "summarizeBy": "none"
          },
          {
            "name": "Title",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "26661d17-d576-43ae-86c9-653022f0b927",
            "sourceColumn": "Title",
            "summarizeBy": "none"
          },
          {
            "name": "FirstName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0b3da6c2-f472-4f8c-b6db-17f94c21460f",
            "sourceColumn": "FirstName",
            "summarizeBy": "none"
          },
          {
            "name": "MiddleName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f9f2c8eb-c076-45c5-99fb-682992dc0ee0",
            "sourceColumn": "MiddleName",
            "summarizeBy": "none"
          },
          {
            "name": "LastName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fc5f3a13-1607-414f-9a0e-fe39e50038eb",
            "sourceColumn": "LastName",
            "summarizeBy": "none"
          },
          {
            "name": "NameStyle",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f5109902-a904-45c7-8551-3531327fa664",
            "sourceColumn": "NameStyle",
            "summarizeBy": "sum"
          },
          {
            "name": "BirthDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "44c13326-765e-4ef8-bf8e-418506b8195b",
            "sourceColumn": "BirthDate",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_66029369-c4d7-4316-8dfe-15cd5df06050"
                },
                "isDefault": true,
                "relationship": "6477dee4-e10f-4e45-bf39-9b847d53050c"
              }
            ]
          },
          {
            "name": "MaritalStatus",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9b96fc20-5b5a-4a2c-85c7-26d479ce430f",
            "sourceColumn": "MaritalStatus",
            "summarizeBy": "none"
          },
          {
            "name": "Suffix",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "da44a1a3-e992-416c-8867-fffe14f68d89",
            "sourceColumn": "Suffix",
            "summarizeBy": "none"
          },
          {
            "name": "Gender",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "08629120-656f-4527-924a-32a66629ec4c",
            "sourceColumn": "Gender",
            "summarizeBy": "none"
          },
          {
            "name": "EmailAddress",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b349e880-21a4-42fe-9015-1acfb3bdb455",
            "sourceColumn": "EmailAddress",
            "summarizeBy": "none"
          },
          {
            "name": "YearlyIncome",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "25079ee8-1246-4bb6-889e-b9a1ee9638b7",
            "sourceColumn": "YearlyIncome",
            "summarizeBy": "sum"
          },
          {
            "name": "TotalChildren",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a2fc61f3-2cca-4c9f-8150-44bddc9ff301",
            "sourceColumn": "TotalChildren",
            "summarizeBy": "sum"
          },
          {
            "name": "NumberChildrenAtHome",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8da29e27-f68d-41e3-8c64-8be6cae7ef07",
            "sourceColumn": "NumberChildrenAtHome",
            "summarizeBy": "sum"
          },
          {
            "name": "EnglishEducation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "faad3962-74c6-428f-9fbf-4f4e883a8c8b",
            "sourceColumn": "EnglishEducation",
            "summarizeBy": "none"
          },
          {
            "name": "SpanishEducation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "11517cc9-38a3-4ebd-965a-87c112adab36",
            "sourceColumn": "SpanishEducation",
            "summarizeBy": "none"
          },
          {
            "name": "FrenchEducation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d433aa16-ade7-4730-aef1-c0f2a6b17f83",
            "sourceColumn": "FrenchEducation",
            "summarizeBy": "none"
          },
          {
            "name": "EnglishOccupation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d8ec301b-a24f-4fa3-bd84-9bc41732068c",
            "sourceColumn": "EnglishOccupation",
            "summarizeBy": "none"
          },
          {
            "name": "SpanishOccupation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f629b5bf-f43f-4e62-a9e0-3d7754de2560",
            "sourceColumn": "SpanishOccupation",
            "summarizeBy": "none"
          },
          {
            "name": "FrenchOccupation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "75a852d8-e8c2-4d9b-a528-fd1c465592c5",
            "sourceColumn": "FrenchOccupation",
            "summarizeBy": "none"
          },
          {
            "name": "HouseOwnerFlag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9ab1657b-fe3f-428c-a70f-b12fc8fbd337",
            "sourceColumn": "HouseOwnerFlag",
            "summarizeBy": "sum"
          },
          {
            "name": "NumberCarsOwned",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "30fc1549-e8ed-4079-9e31-a7d484927089",
            "sourceColumn": "NumberCarsOwned",
            "summarizeBy": "sum"
          },
          {
            "name": "AddressLine1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7cb10576-c946-4d28-aec7-5e84eb000a5a",
            "sourceColumn": "AddressLine1",
            "summarizeBy": "none"
          },
          {
            "name": "AddressLine2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e20c2c53-cca4-4923-afb9-c99bb693fe07",
            "sourceColumn": "AddressLine2",
            "summarizeBy": "none"
          },
          {
            "name": "Phone",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "38155c06-89e0-4912-bd07-d3cca946cded",
            "sourceColumn": "Phone",
            "summarizeBy": "none"
          },
          {
            "name": "DateFirstPurchase",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "58442647-0573-4cb6-84db-72ee5bc854d4",
            "sourceColumn": "DateFirstPurchase",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_c2dd2b07-7bcf-4557-9382-df7410c1a3d7"
                },
                "isDefault": true,
                "relationship": "4f612f2f-55d4-4b34-9cd6-3e8291b70eb4"
              }
            ]
          },
          {
            "name": "CommuteDistance",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "92ef08fb-4994-45f6-adb7-e5dfe5969756",
            "sourceColumn": "CommuteDistance",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "9badefe6-df36-4034-818e-a6788cf694bd",
        "partitions": [
          {
            "name": "dim_Customer",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\Nedko\\Desktop\\Power BI 365 Data Science\\Task Four\\Section Four Data Extract.xlsx\"), null, true),",
                "    dim_Customer_Sheet = Source{[Item=\"dim_Customer\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(dim_Customer_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"CustomerKey\", Int64.Type}, {\"GeographyKey\", Int64.Type}, {\"CustomerAlternateKey\", type text}, {\"Title\", type text}, {\"FirstName\", type text}, {\"MiddleName\", type text}, {\"LastName\", type text}, {\"NameStyle\", Int64.Type}, {\"BirthDate\", type date}, {\"MaritalStatus\", type text}, {\"Suffix\", type text}, {\"Gender\", type text}, {\"EmailAddress\", type text}, {\"YearlyIncome\", Int64.Type}, {\"TotalChildren\", Int64.Type}, {\"NumberChildrenAtHome\", Int64.Type}, {\"EnglishEducation\", type text}, {\"SpanishEducation\", type text}, {\"FrenchEducation\", type text}, {\"EnglishOccupation\", type text}, {\"SpanishOccupation\", type text}, {\"FrenchOccupation\", type text}, {\"HouseOwnerFlag\", Int64.Type}, {\"NumberCarsOwned\", Int64.Type}, {\"AddressLine1\", type text}, {\"AddressLine2\", type text}, {\"Phone\", type text}, {\"DateFirstPurchase\", type date}, {\"CommuteDistance\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_66029369-c4d7-4316-8dfe-15cd5df06050",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "005d5573-6583-4a4e-af07-c1c6b6613f0f",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "9d6b761d-2d2d-41a1-a145-1ee9734aeff9",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "3906737b-e2d4-4a39-a3d6-a611acdc571b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "390f2d76-e76d-487d-8e86-f43d7f8b87dd",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "3f5a580b-340a-461a-a294-9e9c6a5c7849",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "bb1b5d65-82f2-413a-851e-c33dfd4a5939",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "3c770d84-6770-4f31-b441-fb9e55eca9ec",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "396ba3b4-15a1-4ac5-b247-70a4bbc9db4c",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "fab0d490-b4c1-42d2-9a7c-8eb2b7325e39",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "5a18917a-a5b2-4e2b-b952-ab82ea78c1ea",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "e941cd0e-f887-45c6-84d8-2603925ea4b3",
                "ordinal": 3
              }
            ],
            "lineageTag": "5f0da436-5a93-4240-af27-397612c9dcad"
          }
        ],
        "isHidden": true,
        "lineageTag": "19017cbf-ca14-4573-8d10-bc6a7ac7b903",
        "partitions": [
          {
            "name": "LocalDateTable_66029369-c4d7-4316-8dfe-15cd5df06050",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('dim_Customer'[BirthDate])), 1, 1), Date(Year(MAX('dim_Customer'[BirthDate])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_c2dd2b07-7bcf-4557-9382-df7410c1a3d7",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "0000e853-971f-49eb-ab71-56a1466834cb",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "b5457a28-fe58-46d1-a477-2f3c105834c0",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "ae78cc01-bfda-4d8e-bb5c-6c7f883e1fa4",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "bd39fd2b-f3ee-4d57-bc3e-b27f214182a9",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "186c1213-e3d4-4e4c-ba25-17c4407cdd49",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "27d2b1a2-3e02-43e3-9567-e7cd0ff6be2c",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "f4af2916-bc72-4c2f-9e56-7c598442f3cd",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "a19f9faa-1f72-4796-bf34-ffd00a40f43e",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "ee0280f5-e359-4ec2-ab42-e862c5e56584",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "e59ec54e-2c4d-4e0c-aeef-f72f0b443254",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "e2385b99-6984-4392-9b3f-4f9744935677",
                "ordinal": 3
              }
            ],
            "lineageTag": "dd8966ff-7fab-41e2-b0b5-6efdeef2bba2"
          }
        ],
        "isHidden": true,
        "lineageTag": "a18d0bee-549c-408d-86e4-7df4d2af13d3",
        "partitions": [
          {
            "name": "LocalDateTable_c2dd2b07-7bcf-4557-9382-df7410c1a3d7",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('dim_Customer'[DateFirstPurchase])), 1, 1), Date(Year(MAX('dim_Customer'[DateFirstPurchase])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "dim_Product",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ProductKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "32993956-fd04-417b-a87d-8f26db4a4da1",
            "sourceColumn": "ProductKey",
            "summarizeBy": "none"
          },
          {
            "name": "ProductAlternateKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e66598b6-3803-4670-983a-fc840b7620f8",
            "sourceColumn": "ProductAlternateKey",
            "summarizeBy": "none"
          },
          {
            "name": "ProductSubcategoryKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c57a2699-ce7a-4006-9cec-29952228d6e9",
            "sourceColumn": "ProductSubcategoryKey",
            "summarizeBy": "none"
          },
          {
            "name": "EnglishProductName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "47a0c8a8-0dd9-48e0-b512-44f77a407ebd",
            "sourceColumn": "EnglishProductName",
            "summarizeBy": "none"
          },
          {
            "name": "StandardCost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5c739a0a-2690-456e-8114-0cc0fcc22ade",
            "sourceColumn": "StandardCost",
            "summarizeBy": "none"
          },
          {
            "name": "Color",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ea101e52-4656-48a2-aaf6-c7ce7d7f2db8",
            "sourceColumn": "Color",
            "summarizeBy": "none"
          },
          {
            "name": "Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5ade0059-201c-4a88-b115-03eae75580dd",
            "sourceColumn": "Status",
            "summarizeBy": "none"
          },
          {
            "name": "StartDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "e670d4d6-67f8-4428-8fa0-97fa5a070fff",
            "sourceColumn": "StartDate",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_5b329dcb-4f14-4a14-a60d-6b569e4c8768"
                },
                "isDefault": true,
                "relationship": "1a5320b3-5b0a-4081-8730-cf6f4d892953"
              }
            ]
          }
        ],
        "lineageTag": "7a9e1d70-464e-4126-a14f-f43eef5020e3",
        "partitions": [
          {
            "name": "dim_Product",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\Nedko\\Desktop\\Power BI 365 Data Science\\Task Four\\Section Four Data Extract.xlsx\"), null, true),",
                "    dim_Product_Sheet = Source{[Item=\"dim_Product\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(dim_Product_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"ProductKey\", Int64.Type}, {\"ProductAlternateKey\", type text}, {\"ProductSubcategoryKey\", type text}, {\"EnglishProductName\", type text}, {\"StandardCost\", type text}, {\"Color\", type text}, {\"Status\", type text}, {\"StartDate\", type date}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_5b329dcb-4f14-4a14-a60d-6b569e4c8768",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "051f8d2d-a75b-4e3d-a541-c2464ec3e7e9",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "1872f565-4256-4b81-99ac-d39192249194",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "587e55fc-e205-455d-831a-e0c0cc6c789c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "d6177c3d-e0fc-4e4c-a5e0-73a2f0a3abda",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "cd75771a-e14c-4882-94ff-3f01e68ae64f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "71d255ff-c984-423a-aa46-763624d18087",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "e243a202-3eba-49f4-9bec-cb1adbe2ccfa",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "6ede954e-8aad-4880-af09-17f857ee608a",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "cc2fad4f-5af3-4359-867c-f2e37b8cadd8",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "5693804a-6a1c-43f7-a175-31b7c36e22b8",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "807496fa-4915-4450-bb81-929d6996e232",
                "ordinal": 3
              }
            ],
            "lineageTag": "49c3cb6e-43c5-4813-a506-50cd736fc91a"
          }
        ],
        "isHidden": true,
        "lineageTag": "d4830ca8-343d-4770-86c2-41dcc9c74708",
        "partitions": [
          {
            "name": "LocalDateTable_5b329dcb-4f14-4a14-a60d-6b569e4c8768",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('dim_Product'[StartDate])), 1, 1), Date(Year(MAX('dim_Product'[StartDate])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "dim_SalesTeritory",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "SalesTerritoryKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ed58d232-fb74-4667-8966-054e3180492e",
            "sourceColumn": "SalesTerritoryKey",
            "summarizeBy": "none"
          },
          {
            "name": "SalesTerritoryAlternateKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "053225cb-76d0-48da-92c4-94a6f737064c",
            "sourceColumn": "SalesTerritoryAlternateKey",
            "summarizeBy": "none"
          },
          {
            "name": "SalesTerritoryRegion",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "36f3cd5d-c92e-4efb-8ad2-51006da21770",
            "sourceColumn": "SalesTerritoryRegion",
            "summarizeBy": "none"
          },
          {
            "name": "SalesTerritoryGroup",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "73f803c2-2cde-476a-897a-7182cdd8464d",
            "sourceColumn": "SalesTerritoryGroup",
            "summarizeBy": "none"
          },
          {
            "name": "SalesTerritoryCountry",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2e3fa53c-83ab-4456-9569-637e60e79b34",
            "sourceColumn": "SalesTerritoryCountry",
            "summarizeBy": "none"
          },
          {
            "name": "CountryOrder",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "IF(dim_SalesTeritory[SalesTerritoryRegion]=\"Australia\",1,",
              "IF(dim_SalesTeritory[SalesTerritoryRegion]=\"Canada\",2,",
              "IF(dim_SalesTeritory[SalesTerritoryRegion]=\"Germany\",3,",
              "IF(dim_SalesTeritory[SalesTerritoryRegion]=\"France\",4,",
              "IF(dim_SalesTeritory[SalesTerritoryRegion]=\"United Kingdom\",5,",
              "IF(dim_SalesTeritory[SalesTerritoryRegion]=\"Northeast\",6,",
              "IF(dim_SalesTeritory[SalesTerritoryRegion]=\"Central\",6,",
              "IF(dim_SalesTeritory[SalesTerritoryRegion]=\"Southwest\",6,",
              "IF(dim_SalesTeritory[SalesTerritoryRegion]=\"Southeast\",6,",
              "IF(dim_SalesTeritory[SalesTerritoryRegion]=\"Northwest\",6,",
              "BLANK()))))))))))"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "192ad244-8803-43b3-bc45-c88fe02689a2",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "7b690f5c-28ad-4dd4-bb36-e0e3d2176b4d",
        "partitions": [
          {
            "name": "dim_SalesTeritory",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\Nedko\\Desktop\\Power BI 365 Data Science\\Task Four\\Section Four Data Extract.xlsx\"), null, true),",
                "    dim_SalesTeritory_Sheet = Source{[Item=\"dim_SalesTeritory\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(dim_SalesTeritory_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"SalesTerritoryKey\", Int64.Type}, {\"SalesTerritoryAlternateKey\", Int64.Type}, {\"SalesTerritoryRegion\", type text}, {\"SalesTerritoryGroup\", type text}, {\"SalesTerritoryCountry\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "fact_InternetSales",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ProductKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "24b974c3-2773-4592-b36d-adb1551ddd8a",
            "sourceColumn": "ProductKey",
            "summarizeBy": "none"
          },
          {
            "name": "OrderDateKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "238f8392-c20a-43c9-b418-c882342d6bab",
            "sourceColumn": "OrderDateKey",
            "summarizeBy": "count"
          },
          {
            "name": "DueDateKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "48d168a1-5f78-4c8b-9516-b195900eae25",
            "sourceColumn": "DueDateKey",
            "summarizeBy": "count"
          },
          {
            "name": "ShipDateKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9699f48f-b0a7-478d-9301-4001bd5e4d63",
            "sourceColumn": "ShipDateKey",
            "summarizeBy": "count"
          },
          {
            "name": "CustomerKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "027eb61a-b1f6-4e24-b1eb-b837071f90fb",
            "sourceColumn": "CustomerKey",
            "summarizeBy": "none"
          },
          {
            "name": "PromotionKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d2d8c8e2-ff91-4537-b1c8-85b174cd01e2",
            "sourceColumn": "PromotionKey",
            "summarizeBy": "count"
          },
          {
            "name": "CurrencyKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8891f646-d24b-41fc-b67e-744d844dc6c8",
            "sourceColumn": "CurrencyKey",
            "summarizeBy": "none"
          },
          {
            "name": "SalesTerritoryKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "dd9d3fed-d53b-4bb9-9e9e-3f1199f291fe",
            "sourceColumn": "SalesTerritoryKey",
            "summarizeBy": "none"
          },
          {
            "name": "SalesOrderNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "aee14c93-8c52-4374-b5b8-0d55fbcb8666",
            "sourceColumn": "SalesOrderNumber",
            "summarizeBy": "none"
          },
          {
            "name": "SalesOrderLineNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "75676479-9a51-4a85-bd50-85f76e13bf31",
            "sourceColumn": "SalesOrderLineNumber",
            "summarizeBy": "sum"
          },
          {
            "name": "RevisionNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5c1b0888-f862-4ada-9cb4-9617a6227760",
            "sourceColumn": "RevisionNumber",
            "summarizeBy": "sum"
          },
          {
            "name": "OrderQuantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "24488684-b804-4890-87a8-2d3bbb7c2726",
            "sourceColumn": "OrderQuantity",
            "summarizeBy": "sum"
          },
          {
            "name": "UnitPrice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "25db823c-eb9f-410c-a751-0ce774e5ccfd",
            "sourceColumn": "UnitPrice",
            "summarizeBy": "sum"
          },
          {
            "name": "ExtendedAmount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "48123d61-ae57-4e79-8605-21b3a2d6f3a2",
            "sourceColumn": "ExtendedAmount",
            "summarizeBy": "sum"
          },
          {
            "name": "UnitPriceDiscountPct",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e23f0e58-0b1a-43c3-b481-ee598d363d83",
            "sourceColumn": "UnitPriceDiscountPct",
            "summarizeBy": "sum"
          },
          {
            "name": "DiscountAmount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9acb1c93-2989-4703-b61d-4fb49a86257f",
            "sourceColumn": "DiscountAmount",
            "summarizeBy": "sum"
          },
          {
            "name": "ProductStandardCost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "6e398ee2-57fa-47ba-85c2-089e0d172436",
            "sourceColumn": "ProductStandardCost",
            "summarizeBy": "sum"
          },
          {
            "name": "TotalProductCost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "2284f77e-c95e-4cb2-a065-b18236b0eef6",
            "sourceColumn": "TotalProductCost",
            "summarizeBy": "sum"
          },
          {
            "name": "SalesAmount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "78df3f6e-7b80-4480-ac9e-c09bcd82def8",
            "sourceColumn": "SalesAmount",
            "summarizeBy": "sum"
          },
          {
            "name": "TaxAmt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "4ad21a3a-65a9-406c-bd99-df8798da6112",
            "sourceColumn": "TaxAmt",
            "summarizeBy": "sum"
          },
          {
            "name": "Freight",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a3106776-9069-42ef-9559-671b155ffb03",
            "sourceColumn": "Freight",
            "summarizeBy": "sum"
          },
          {
            "name": "CarrierTrackingNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "37b0cd1c-b326-47ce-b4cb-bd77f250206d",
            "sourceColumn": "CarrierTrackingNumber",
            "summarizeBy": "none"
          },
          {
            "name": "CustomerPONumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b6308aac-ab52-4cc7-81aa-82f76115369e",
            "sourceColumn": "CustomerPONumber",
            "summarizeBy": "none"
          },
          {
            "name": "OrderDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "386ed99f-1788-4711-9ea8-0142ba50408f",
            "sourceColumn": "OrderDate",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_c535fb3e-a130-493f-aea9-b60633804db6"
                },
                "isDefault": true,
                "relationship": "8a6d2c0c-f353-45f2-97d2-39bec27d4209"
              }
            ]
          },
          {
            "name": "DueDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "6dbd5f2b-2ae0-4564-9d7c-bc516decfa21",
            "sourceColumn": "DueDate",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_5ab76db6-97c3-404f-93f0-5da8846858f7"
                },
                "isDefault": true,
                "relationship": "585cedc0-a1a8-47d7-ad86-2abe10c14f12"
              }
            ]
          },
          {
            "name": "ShipDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "ebaa5b93-b75b-4679-be41-e94a7742ce19",
            "sourceColumn": "ShipDate",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_674de304-6ec6-4631-9875-946aa27bb344"
                },
                "isDefault": true,
                "relationship": "37a7be2c-f7b0-452a-8e83-83631ab9f2ba"
              }
            ]
          }
        ],
        "lineageTag": "1500ff6f-322d-42a1-8047-25505bc57436",
        "partitions": [
          {
            "name": "fact_InternetSales",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\Nedko\\Desktop\\Power BI 365 Data Science\\Task Four\\Section Four Data Extract.xlsx\"), null, true),",
                "    fact_InternetSales_Sheet = Source{[Item=\"fact_InternetSales\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(fact_InternetSales_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"ProductKey\", Int64.Type}, {\"OrderDateKey\", Int64.Type}, {\"DueDateKey\", Int64.Type}, {\"ShipDateKey\", Int64.Type}, {\"CustomerKey\", Int64.Type}, {\"PromotionKey\", Int64.Type}, {\"CurrencyKey\", Int64.Type}, {\"SalesTerritoryKey\", Int64.Type}, {\"SalesOrderNumber\", type text}, {\"SalesOrderLineNumber\", Int64.Type}, {\"RevisionNumber\", Int64.Type}, {\"OrderQuantity\", Int64.Type}, {\"UnitPrice\", type number}, {\"ExtendedAmount\", type number}, {\"UnitPriceDiscountPct\", Int64.Type}, {\"DiscountAmount\", Int64.Type}, {\"ProductStandardCost\", type number}, {\"TotalProductCost\", type number}, {\"SalesAmount\", type number}, {\"TaxAmt\", type number}, {\"Freight\", type number}, {\"CarrierTrackingNumber\", type text}, {\"CustomerPONumber\", type text}, {\"OrderDate\", type datetime}, {\"DueDate\", type datetime}, {\"ShipDate\", type datetime}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_c535fb3e-a130-493f-aea9-b60633804db6",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "9f8bad2d-3d9d-4831-91c8-c2a3fa699eba",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "683d6c0b-5384-4b31-b8d4-c15bd7415531",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "9cc3e61f-e31c-454c-96ce-efa14dd32f75",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "2a8571a9-b0cf-40db-ba56-d5c49add24dc",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "5cbe3a40-1516-424b-80cf-d27e25ddfaa8",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "a1d28045-d918-49e7-b3e0-0b16b7a95a75",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "297b73ed-1655-4504-8380-ed23f7145c8e",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "eead7f8a-0883-4402-8328-c133eb1e4034",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "a7172b56-8ff6-427c-91a8-6e3ae333ebcf",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "c5bca2d6-d44f-4ea8-b480-6a8c830305da",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "2b3d15ef-4595-453b-9394-bd0b78f38bdf",
                "ordinal": 3
              }
            ],
            "lineageTag": "133e375e-2bc2-4b9d-b128-cdc7018606eb"
          }
        ],
        "isHidden": true,
        "lineageTag": "a11fe41c-2512-4caa-94bd-e84db0c3cb15",
        "partitions": [
          {
            "name": "LocalDateTable_c535fb3e-a130-493f-aea9-b60633804db6",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('fact_InternetSales'[OrderDate])), 1, 1), Date(Year(MAX('fact_InternetSales'[OrderDate])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_5ab76db6-97c3-404f-93f0-5da8846858f7",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "c022c844-2ad1-4697-8ee6-22b3dfefe727",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "1a65152a-8f6b-4ea4-a7a7-8176eb0a1922",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "9fb39636-9a44-46e8-a163-67d5fd9c0660",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "5c302db9-fee3-4306-8647-69640692cacd",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "bc8c5597-55b6-4d74-9f32-4859aebe0c32",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "1fff843b-fbcc-401d-8b16-4e2f2fb9c592",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "d3bb5be1-0cee-4b18-91ac-e941137c3543",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "3bab7e1a-d327-4b1f-9652-0993a8cdc030",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "dbda2ee8-83db-48cb-8646-e8e2ebe65fd5",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "1e68348c-426e-439d-86d1-c427ae9a00ce",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "af771a4e-097a-47b9-956f-5492184a49e4",
                "ordinal": 3
              }
            ],
            "lineageTag": "787b4aaa-8f90-45f6-968d-45f6c863c6b5"
          }
        ],
        "isHidden": true,
        "lineageTag": "59709f1c-2a9e-4c11-9bb8-623f7ab269cd",
        "partitions": [
          {
            "name": "LocalDateTable_5ab76db6-97c3-404f-93f0-5da8846858f7",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('fact_InternetSales'[DueDate])), 1, 1), Date(Year(MAX('fact_InternetSales'[DueDate])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_674de304-6ec6-4631-9875-946aa27bb344",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "bd038a52-8a36-48d6-9d03-9f72f3d46010",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "310b6d1d-209e-411e-8d41-3abc8a1e33ab",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "745b8468-2ba2-4b60-a037-61e81b4d08ef",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "91118549-b4c9-4a38-8df7-004501c7f67b",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "5d2724bc-8365-4856-a625-00700637e129",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "e4eec0a3-0755-4408-a7ef-4a34fc0742f9",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "38b3d33d-f37b-40b8-b3ed-d88d1bb234b8",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "137276da-a849-478e-b8dd-3c2881ab5943",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "ca72f921-7e1d-4094-a586-a73cca06fb42",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "a84e76ef-6801-44c6-98be-ec8d38c99b95",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "7211cd52-1c49-4185-9c12-db6ea29dbaab",
                "ordinal": 3
              }
            ],
            "lineageTag": "306b1735-c087-4a0a-9a39-388906e6bf29"
          }
        ],
        "isHidden": true,
        "lineageTag": "e41f6303-53be-435f-810a-c388eda375d3",
        "partitions": [
          {
            "name": "LocalDateTable_674de304-6ec6-4631-9875-946aa27bb344",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('fact_InternetSales'[ShipDate])), 1, 1), Date(Year(MAX('fact_InternetSales'[ShipDate])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "#Measures",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "708d70547b784f7f8ea913f739d41a05"
          }
        ],
        "columns": [
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "0060ce4b-1a97-4780-863d-02905dd40780",
            "sourceColumn": "[Value]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "c73975e5-e660-4e69-a232-f107d9751ca5",
        "measures": [
          {
            "name": "TotalSalesAmount",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "SUM(fact_InternetSales[SalesAmount])",
            "lineageTag": "3114d283-cee0-4b97-9ae0-48e0922540ea"
          },
          {
            "name": "SalesAmountUS",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE(SUM(fact_InternetSales[SalesAmount]), dim_SalesTeritory[SalesTerritoryCountry] = \"United States\")",
            "lineageTag": "2c7528bd-c521-4b5c-bdc2-13b52b8193b8"
          },
          {
            "name": "%SalesAmountUS",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "DIVIDE([SalesAmountUS],",
              "CALCULATE(SUM(fact_InternetSales[SalesAmount]), ALL(dim_SalesTeritory[SalesTerritoryCountry])))*100"
            ],
            "lineageTag": "a0cffad2-3a61-4ccb-a81a-89c71a229e4c"
          },
          {
            "name": "SelectedCountry",
            "expression": [
              "",
              "var CountrySelected = ISFILTERED(dim_SalesTeritory[SalesTerritoryCountry])",
              "RETURN",
              "IF(CountrySelected, \"Selected country is \" & SELECTEDVALUE(dim_SalesTeritory[SalesTerritoryCountry]), \"Please, choose a country!\")"
            ],
            "lineageTag": "0fff9058-8a3d-4471-a9c3-96baad50a3dc"
          },
          {
            "name": "%TotalSalesAmount",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "DIVIDE([TotalSalesAmount], CALCULATE(SUM(fact_InternetSales[SalesAmount]), ALL(dim_SalesTeritory[SalesTerritoryCountry]),ALL(dim_SalesTeritory[CountryOrder])))*100"
            ],
            "lineageTag": "ee3294db-d6a7-48bf-a0f8-bca556702759"
          },
          {
            "name": "NumberVSPercantage",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "IF(SELECTEDVALUE(SwitchTable[DataType])=\"Number\",[TotalSalesAmount],",
              "IF(SELECTEDVALUE(SwitchTable[DataType])=\"Percentage\", [%TotalSalesAmount], BLANK()))"
            ],
            "lineageTag": "fe3d392a-15ee-4b81-961d-d6a893cf3ab2"
          }
        ],
        "partitions": [
          {
            "name": "#Measures",
            "mode": "import",
            "source": {
              "expression": "GENERATESERIES(1,1,1)",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "SwitchTable",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "DataType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cc23d32a-c678-4112-8521-4b4c0a42155d",
            "sourceColumn": "DataType",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "cb92ba94-d29e-41fb-9b3b-1c3a43bba87c",
        "partitions": [
          {
            "name": "SwitchTable",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45W8ivNTUotUorViVYKSC1KTs0rSUxPVYqNBQA=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [DataType = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"DataType\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}