{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Metrics\",\"Rate_Data\",\"Errors in Rate_Data\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.131.901.0 (24.07)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Entities": {
              "metrics": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Metrics"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "metrics": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "metrics.iqrr": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Metrics",
                    "ConceptualProperty": "IQRR"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "iqrr": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "metrics.max_IQRR": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Metrics",
                    "ConceptualProperty": "MaxIQRR"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "max IQRR": {
                      "State": "Generated"
                    }
                  },
                  {
                    "MaxIQRR": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "maximum iqrr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  }
                ]
              },
              "metrics.min_IQRR": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Metrics",
                    "ConceptualProperty": "MinIQRR"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "min IQRR": {
                      "State": "Generated"
                    }
                  },
                  {
                    "MinIQRR": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "minimum iqrr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  }
                ]
              },
              "metrics.renewed_contracts": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Metrics",
                    "ConceptualProperty": "TotalRenewedContracts"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "total renewed contracts": {
                      "State": "Generated"
                    }
                  },
                  {
                    "TotalRenewedContracts": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "aggregate renewed contract": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.591
                    }
                  },
                  {
                    "overall renewed contract": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.591
                    }
                  },
                  {
                    "total renewed agreement": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.508
                    }
                  },
                  {
                    "total renewed pact": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.508
                    }
                  },
                  {
                    "total renewed convention": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.508
                    }
                  },
                  {
                    "total renewed treaty": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.508
                    }
                  },
                  {
                    "total renewed bond": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.492
                    }
                  },
                  {
                    "total renewed indenture": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.492
                    }
                  },
                  {
                    "total renewed deal": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.492
                    }
                  },
                  {
                    "Renewed Contracts": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "metrics.total_expiring_contracts": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Metrics",
                    "ConceptualProperty": "TotalExpiringContracts"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "total expiring contracts": {
                      "State": "Generated"
                    }
                  },
                  {
                    "TotalExpiringContracts": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "contracts": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "aggregate expiring contract": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.591
                    }
                  },
                  {
                    "overall expiring contract": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.591
                    }
                  },
                  {
                    "total expiring agreement": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.508
                    }
                  },
                  {
                    "total expiring pact": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.508
                    }
                  },
                  {
                    "total expiring convention": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.508
                    }
                  },
                  {
                    "total expiring treaty": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.508
                    }
                  },
                  {
                    "total expiring bond": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.492
                    }
                  },
                  {
                    "total expiring indenture": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.492
                    }
                  },
                  {
                    "total expiring deal": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.492
                    }
                  },
                  {
                    "agreement": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "Expiring Contracts": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "rate_data": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Rate_Data"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "rate data": {
                      "State": "Generated"
                    }
                  },
                  {
                    "Rate_Data": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "data": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "rate information": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "rate fact": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "rate info": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "rate statistic": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "information": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "fact": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "info": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "statistic": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "rate document": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "rate figure": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  }
                ]
              },
              "rate_data.account_name": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Rate_Data",
                    "ConceptualProperty": "Account Name"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "account name": {
                      "State": "Generated"
                    }
                  },
                  {
                    "account": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "account nickname": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "account title": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "account label": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "account tag": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "acct name": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "explanation": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "version": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "interpretation": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "justification": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "reason": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  }
                ]
              },
              "rate_data.contract_number": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Rate_Data",
                    "ConceptualProperty": "Contract Number"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "contract number": {
                      "State": "Generated"
                    }
                  },
                  {
                    "contract no": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  }
                ]
              },
              "rate_data.contract_status": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Rate_Data",
                    "ConceptualProperty": "Contract Status"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "contract status": {
                      "State": "Generated"
                    }
                  },
                  {
                    "status": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "contract category": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "contract importance": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "contract prestige": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "contract prominence": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "category": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "importance": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "prestige": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "prominence": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "contract condition": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "contract class": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  }
                ]
              },
              "rate_data.direct_channel": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Rate_Data",
                    "ConceptualProperty": "Direct/Channel"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "direct/channel": {
                      "State": "Generated"
                    }
                  },
                  {
                    "direct": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "direct channel": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "channel": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "direct/ frequency": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.508
                    }
                  },
                  {
                    "direct frequency": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "direct/ station": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.492
                    }
                  },
                  {
                    "direct/ network": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.492
                    }
                  },
                  {
                    "frequency": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "direct station": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "direct network": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "direct/ conduit": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.482
                    }
                  },
                  {
                    "direct/ waterway": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.482
                    }
                  },
                  {
                    "straight": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  }
                ]
              },
              "rate_data.expiration_date": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Rate_Data",
                    "ConceptualProperty": "Expiration Date"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "expiration date": {
                      "State": "Generated"
                    }
                  },
                  {
                    "date": {
                      "State": "Generated",
                      "Weight": 0.7
                    }
                  },
                  {
                    "expiration moment": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "expiration period": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  }
                ]
              },
              "rate_data.expiration_date.variation.date_hierarchy": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Rate_Data",
                    "Hierarchy": "Date Hierarchy",
                    "VariationSet": "Variation",
                    "VariationSource": "Expiration Date"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "expiration date hierarchy": {
                      "State": "Generated"
                    }
                  },
                  {
                    "date hierarchy": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  }
                ]
              },
              "rate_data.expiration_date.variation.date_hierarchy.day": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Rate_Data",
                    "Hierarchy": "Date Hierarchy",
                    "HierarchyLevel": "Day",
                    "VariationSet": "Variation",
                    "VariationSource": "Expiration Date"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "expiration day": {
                      "State": "Generated"
                    }
                  },
                  {
                    "day": {
                      "State": "Generated"
                    }
                  },
                  {
                    "expiration date day": {
                      "State": "Generated"
                    }
                  },
                  {
                    "date day": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "expiration moment day": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.609
                    }
                  },
                  {
                    "moment day": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "expiration period day": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.591
                    }
                  },
                  {
                    "period day": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  }
                ]
              },
              "rate_data.expiration_date.variation.date_hierarchy.month": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Rate_Data",
                    "Hierarchy": "Date Hierarchy",
                    "HierarchyLevel": "Month",
                    "VariationSet": "Variation",
                    "VariationSource": "Expiration Date"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "expiration month": {
                      "State": "Generated"
                    }
                  },
                  {
                    "month": {
                      "State": "Generated"
                    }
                  },
                  {
                    "expiration date month": {
                      "State": "Generated"
                    }
                  },
                  {
                    "date month": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "expiration date mth": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.762
                    }
                  },
                  {
                    "expiration mth": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "date mth": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "mth": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "expiration moment month": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.609
                    }
                  },
                  {
                    "moment month": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "expiration period month": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.591
                    }
                  },
                  {
                    "period month": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  }
                ]
              },
              "rate_data.expiration_date.variation.date_hierarchy.quarter": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Rate_Data",
                    "Hierarchy": "Date Hierarchy",
                    "HierarchyLevel": "Quarter",
                    "VariationSet": "Variation",
                    "VariationSource": "Expiration Date"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "expiration quarter": {
                      "State": "Generated"
                    }
                  },
                  {
                    "quarter": {
                      "State": "Generated"
                    }
                  },
                  {
                    "expiration date quarter": {
                      "State": "Generated"
                    }
                  },
                  {
                    "date quarter": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "expiration date qtr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.846
                    }
                  },
                  {
                    "expiration qtr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.833
                    }
                  },
                  {
                    "date qtr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.833
                    }
                  },
                  {
                    "qtr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.818
                    }
                  },
                  {
                    "expiration moment quarter": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.609
                    }
                  },
                  {
                    "moment quarter": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "expiration period quarter": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.591
                    }
                  },
                  {
                    "period quarter": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  }
                ]
              },
              "rate_data.expiration_date.variation.date_hierarchy.year": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Rate_Data",
                    "Hierarchy": "Date Hierarchy",
                    "HierarchyLevel": "Year",
                    "VariationSet": "Variation",
                    "VariationSource": "Expiration Date"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "expiration year": {
                      "State": "Generated"
                    }
                  },
                  {
                    "year": {
                      "State": "Generated"
                    }
                  },
                  {
                    "expiration date year": {
                      "State": "Generated"
                    }
                  },
                  {
                    "date year": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "expiration date yr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.762
                    }
                  },
                  {
                    "expiration yr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "date yr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "yr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "expiration moment year": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.609
                    }
                  },
                  {
                    "moment year": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "expiration period year": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.591
                    }
                  },
                  {
                    "period year": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  }
                ]
              },
              "rate_data.expiration_quarter": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Rate_Data",
                    "ConceptualProperty": "Expiration Quarter"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "expiration quarter": {
                      "State": "Generated"
                    }
                  },
                  {
                    "expiration qtr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.833
                    }
                  }
                ]
              },
              "rate_data.new_contract_amount": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Rate_Data",
                    "ConceptualProperty": "New Contract Amount"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "new contract amount": {
                      "State": "Generated"
                    }
                  },
                  {
                    "contract amount": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "new contract quantity": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.508
                    }
                  },
                  {
                    "new contract volume": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.508
                    }
                  },
                  {
                    "new contract expanse": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.508
                    }
                  },
                  {
                    "new contract extent": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.508
                    }
                  },
                  {
                    "contract quantity": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "contract volume": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "contract expanse": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "contract extent": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "new contract sum": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.492
                    }
                  },
                  {
                    "new contract total": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.492
                    }
                  }
                ]
              },
              "rate_data.new_contract_bucket": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Rate_Data",
                    "ConceptualProperty": "New Contract Bucket"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "new contract bucket": {
                      "State": "Generated"
                    }
                  },
                  {
                    "bucket": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "contract bucket": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "new contract pail": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.508
                    }
                  },
                  {
                    "new contract container": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.508
                    }
                  },
                  {
                    "new contract vessel": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.508
                    }
                  },
                  {
                    "contract pail": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "contract container": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "contract vessel": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "pail": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "container": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "vessel": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  }
                ]
              },
              "rate_data.partner": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Rate_Data",
                    "ConceptualProperty": "Partner"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "partner": {
                      "State": "Generated"
                    }
                  },
                  {
                    "wife": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "lover": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "spouse": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "companion": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "husband": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "mate": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "colleague": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.466
                    }
                  },
                  {
                    "cohort": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.466
                    }
                  },
                  {
                    "collaborator": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.466
                    }
                  },
                  {
                    "coworker": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.466
                    }
                  }
                ]
              },
              "rate_data.previous_contract_amount": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Rate_Data",
                    "ConceptualProperty": "Previous Contract Amount"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "previous contract amount": {
                      "State": "Generated"
                    }
                  },
                  {
                    "contract amount": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "previous contract quantity": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.508
                    }
                  },
                  {
                    "previous contract volume": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.508
                    }
                  },
                  {
                    "previous contract expanse": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.508
                    }
                  },
                  {
                    "previous contract extent": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.508
                    }
                  },
                  {
                    "contract quantity": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "contract volume": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "contract expanse": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "contract extent": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "previous contract sum": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.492
                    }
                  },
                  {
                    "previous contract total": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.492
                    }
                  }
                ]
              },
              "rate_data.previous_contract_bucket": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Rate_Data",
                    "ConceptualProperty": "Previous Contract Bucket"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "previous contract bucket": {
                      "State": "Generated"
                    }
                  },
                  {
                    "bucket": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "contract bucket": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "previous contract pail": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.508
                    }
                  },
                  {
                    "previous contract container": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.508
                    }
                  },
                  {
                    "previous contract vessel": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.508
                    }
                  },
                  {
                    "contract pail": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "contract container": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "contract vessel": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "pail": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "container": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "vessel": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  }
                ]
              },
              "rate_data.region": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Rate_Data",
                    "ConceptualProperty": "Region"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "region": {
                      "State": "Generated"
                    }
                  },
                  {
                    "location": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.818
                    }
                  },
                  {
                    "province": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "area": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  },
                  {
                    "district": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  },
                  {
                    "section": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  },
                  {
                    "zone": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  },
                  {
                    "continent": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  }
                ]
              },
              "rate_data.renewal_date": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Rate_Data",
                    "ConceptualProperty": "Renewal Date"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "renewal date": {
                      "State": "Generated"
                    }
                  },
                  {
                    "date": {
                      "State": "Generated",
                      "Weight": 0.7
                    }
                  },
                  {
                    "renewal moment": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "renewal period": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  }
                ]
              },
              "rate_data.renewal_date.variation.date_hierarchy": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Rate_Data",
                    "Hierarchy": "Date Hierarchy",
                    "VariationSet": "Variation",
                    "VariationSource": "Renewal Date"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "renewal date hierarchy": {
                      "State": "Generated"
                    }
                  },
                  {
                    "date hierarchy": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  }
                ]
              },
              "rate_data.renewal_date.variation.date_hierarchy.day": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Rate_Data",
                    "Hierarchy": "Date Hierarchy",
                    "HierarchyLevel": "Day",
                    "VariationSet": "Variation",
                    "VariationSource": "Renewal Date"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "renewal day": {
                      "State": "Generated"
                    }
                  },
                  {
                    "day": {
                      "State": "Generated"
                    }
                  },
                  {
                    "renewal date day": {
                      "State": "Generated"
                    }
                  },
                  {
                    "date day": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "renewal moment day": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.609
                    }
                  },
                  {
                    "moment day": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "renewal period day": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.591
                    }
                  },
                  {
                    "period day": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  }
                ]
              },
              "rate_data.renewal_date.variation.date_hierarchy.month": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Rate_Data",
                    "Hierarchy": "Date Hierarchy",
                    "HierarchyLevel": "Month",
                    "VariationSet": "Variation",
                    "VariationSource": "Renewal Date"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "renewal month": {
                      "State": "Generated"
                    }
                  },
                  {
                    "month": {
                      "State": "Generated"
                    }
                  },
                  {
                    "renewal date month": {
                      "State": "Generated"
                    }
                  },
                  {
                    "date month": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "renewal date mth": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.762
                    }
                  },
                  {
                    "renewal mth": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "date mth": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "mth": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "renewal moment month": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.609
                    }
                  },
                  {
                    "moment month": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "renewal period month": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.591
                    }
                  },
                  {
                    "period month": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  }
                ]
              },
              "rate_data.renewal_date.variation.date_hierarchy.quarter": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Rate_Data",
                    "Hierarchy": "Date Hierarchy",
                    "HierarchyLevel": "Quarter",
                    "VariationSet": "Variation",
                    "VariationSource": "Renewal Date"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "renewal quarter": {
                      "State": "Generated"
                    }
                  },
                  {
                    "quarter": {
                      "State": "Generated"
                    }
                  },
                  {
                    "renewal date quarter": {
                      "State": "Generated"
                    }
                  },
                  {
                    "date quarter": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "renewal date qtr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.846
                    }
                  },
                  {
                    "renewal qtr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.833
                    }
                  },
                  {
                    "date qtr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.833
                    }
                  },
                  {
                    "qtr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.818
                    }
                  },
                  {
                    "renewal moment quarter": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.609
                    }
                  },
                  {
                    "moment quarter": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "renewal period quarter": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.591
                    }
                  },
                  {
                    "period quarter": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  }
                ]
              },
              "rate_data.renewal_date.variation.date_hierarchy.year": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Rate_Data",
                    "Hierarchy": "Date Hierarchy",
                    "HierarchyLevel": "Year",
                    "VariationSet": "Variation",
                    "VariationSource": "Renewal Date"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "renewal year": {
                      "State": "Generated"
                    }
                  },
                  {
                    "year": {
                      "State": "Generated"
                    }
                  },
                  {
                    "renewal date year": {
                      "State": "Generated"
                    }
                  },
                  {
                    "date year": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "renewal date yr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.762
                    }
                  },
                  {
                    "renewal yr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "date yr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "yr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "renewal moment year": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.609
                    }
                  },
                  {
                    "moment year": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "renewal period year": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.591
                    }
                  },
                  {
                    "period year": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  }
                ]
              },
              "rate_data.renewal_quarter": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Rate_Data",
                    "ConceptualProperty": "Renewal Quarter"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "renewal quarter": {
                      "State": "Generated"
                    }
                  },
                  {
                    "renewal qtr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.833
                    }
                  }
                ]
              },
              "rate_data.sales_representative": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Rate_Data",
                    "ConceptualProperty": "Sales Representative"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "sales representative": {
                      "State": "Generated"
                    }
                  },
                  {
                    "sale representative": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.78
                    }
                  },
                  {
                    "representative": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "characteristic": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "demonstrative": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "sale agent": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.451
                    }
                  },
                  {
                    "sale rep": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.451
                    }
                  }
                ]
              }
            },
            "Language": "en-US",
            "Relationships": {
              "metrics_has_max_IQRR": {
                "Binding": {
                  "ConceptualEntity": "Metrics"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "metrics.max_IQRR"
                      },
                      "Subject": {
                        "Role": "metrics"
                      }
                    },
                    "ID": "metrics_have_max_IQRR",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "metrics": {
                    "Target": {
                      "Entity": "metrics"
                    }
                  },
                  "metrics.max_IQRR": {
                    "Target": {
                      "Entity": "metrics.max_IQRR"
                    }
                  }
                },
                "State": "Generated"
              },
              "metrics_has_min_IQRR": {
                "Binding": {
                  "ConceptualEntity": "Metrics"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "metrics.min_IQRR"
                      },
                      "Subject": {
                        "Role": "metrics"
                      }
                    },
                    "ID": "metrics_have_min_IQRR",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "metrics": {
                    "Target": {
                      "Entity": "metrics"
                    }
                  },
                  "metrics.min_IQRR": {
                    "Target": {
                      "Entity": "metrics.min_IQRR"
                    }
                  }
                },
                "State": "Generated"
              },
              "rate_data_expiration_date_has_variation_date_hierarchy": {
                "Binding": {
                  "ConceptualEntity": "Rate_Data"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "rate_data.expiration_date.variation.date_hierarchy"
                      },
                      "Subject": {
                        "Role": "rate_data.expiration_date"
                      }
                    },
                    "ID": "expiration_dates_have_expiration_date_hierarchies",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "rate_data.expiration_date": {
                    "Target": {
                      "Entity": "rate_data.expiration_date"
                    }
                  },
                  "rate_data.expiration_date.variation.date_hierarchy": {
                    "Target": {
                      "Entity": "rate_data.expiration_date.variation.date_hierarchy"
                    }
                  }
                },
                "State": "Generated"
              },
              "rate_data_expiration_date_variation_date_hierarchy_has_day": {
                "Binding": {
                  "ConceptualEntity": "Rate_Data"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "rate_data.expiration_date.variation.date_hierarchy.day"
                      },
                      "Subject": {
                        "Role": "rate_data.expiration_date.variation.date_hierarchy"
                      }
                    },
                    "ID": "expiration_date_hierarchies_have_expiration_days",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "rate_data.expiration_date.variation.date_hierarchy": {
                    "Target": {
                      "Entity": "rate_data.expiration_date.variation.date_hierarchy"
                    }
                  },
                  "rate_data.expiration_date.variation.date_hierarchy.day": {
                    "Target": {
                      "Entity": "rate_data.expiration_date.variation.date_hierarchy.day"
                    }
                  }
                },
                "State": "Generated"
              },
              "rate_data_expiration_date_variation_date_hierarchy_has_month": {
                "Binding": {
                  "ConceptualEntity": "Rate_Data"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "rate_data.expiration_date.variation.date_hierarchy.month"
                      },
                      "Subject": {
                        "Role": "rate_data.expiration_date.variation.date_hierarchy"
                      }
                    },
                    "ID": "expiration_date_hierarchies_have_expiration_months",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "rate_data.expiration_date.variation.date_hierarchy": {
                    "Target": {
                      "Entity": "rate_data.expiration_date.variation.date_hierarchy"
                    }
                  },
                  "rate_data.expiration_date.variation.date_hierarchy.month": {
                    "Target": {
                      "Entity": "rate_data.expiration_date.variation.date_hierarchy.month"
                    }
                  }
                },
                "State": "Generated"
              },
              "rate_data_expiration_date_variation_date_hierarchy_has_quarter": {
                "Binding": {
                  "ConceptualEntity": "Rate_Data"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "rate_data.expiration_date.variation.date_hierarchy.quarter"
                      },
                      "Subject": {
                        "Role": "rate_data.expiration_date.variation.date_hierarchy"
                      }
                    },
                    "ID": "expiration_date_hierarchies_have_expiration_quarters",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "rate_data.expiration_date.variation.date_hierarchy": {
                    "Target": {
                      "Entity": "rate_data.expiration_date.variation.date_hierarchy"
                    }
                  },
                  "rate_data.expiration_date.variation.date_hierarchy.quarter": {
                    "Target": {
                      "Entity": "rate_data.expiration_date.variation.date_hierarchy.quarter"
                    }
                  }
                },
                "State": "Generated"
              },
              "rate_data_expiration_date_variation_date_hierarchy_has_year": {
                "Binding": {
                  "ConceptualEntity": "Rate_Data"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "rate_data.expiration_date.variation.date_hierarchy.year"
                      },
                      "Subject": {
                        "Role": "rate_data.expiration_date.variation.date_hierarchy"
                      }
                    },
                    "ID": "expiration_date_hierarchies_have_expiration_years",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "rate_data.expiration_date.variation.date_hierarchy": {
                    "Target": {
                      "Entity": "rate_data.expiration_date.variation.date_hierarchy"
                    }
                  },
                  "rate_data.expiration_date.variation.date_hierarchy.year": {
                    "Target": {
                      "Entity": "rate_data.expiration_date.variation.date_hierarchy.year"
                    }
                  }
                },
                "State": "Generated"
              },
              "rate_data_has_account_name": {
                "Binding": {
                  "ConceptualEntity": "Rate_Data"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "rate_data.account_name"
                      },
                      "Subject": {
                        "Role": "rate_data"
                      }
                    },
                    "ID": "rate_data_have_account_names",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "rate_data": {
                    "Target": {
                      "Entity": "rate_data"
                    }
                  },
                  "rate_data.account_name": {
                    "Target": {
                      "Entity": "rate_data.account_name"
                    }
                  }
                },
                "State": "Generated"
              },
              "rate_data_has_contract_number": {
                "Binding": {
                  "ConceptualEntity": "Rate_Data"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "rate_data.contract_number"
                      },
                      "Subject": {
                        "Role": "rate_data"
                      }
                    },
                    "ID": "rate_data_have_contract_numbers",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "rate_data": {
                    "Target": {
                      "Entity": "rate_data"
                    }
                  },
                  "rate_data.contract_number": {
                    "Target": {
                      "Entity": "rate_data.contract_number"
                    }
                  }
                },
                "State": "Generated"
              },
              "rate_data_has_contract_status": {
                "Binding": {
                  "ConceptualEntity": "Rate_Data"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "rate_data.contract_status"
                      },
                      "Subject": {
                        "Role": "rate_data"
                      }
                    },
                    "ID": "rate_data_have_contract_statuses",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "DynamicAdjective": {
                      "Adjective": {
                        "Role": "rate_data.contract_status"
                      },
                      "Subject": {
                        "Role": "rate_data"
                      }
                    },
                    "ID": "contract_statuses_describe_rate_data",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "rate_data": {
                    "Target": {
                      "Entity": "rate_data"
                    }
                  },
                  "rate_data.contract_status": {
                    "Target": {
                      "Entity": "rate_data.contract_status"
                    }
                  }
                },
                "State": "Generated"
              },
              "rate_data_has_direct_channel": {
                "Binding": {
                  "ConceptualEntity": "Rate_Data"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "rate_data.direct_channel"
                      },
                      "Subject": {
                        "Role": "rate_data"
                      }
                    },
                    "ID": "rate_data_have_direct_channels",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "rate_data": {
                    "Target": {
                      "Entity": "rate_data"
                    }
                  },
                  "rate_data.direct_channel": {
                    "Target": {
                      "Entity": "rate_data.direct_channel"
                    }
                  }
                },
                "State": "Generated"
              },
              "rate_data_has_expiration_date": {
                "Binding": {
                  "ConceptualEntity": "Rate_Data"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "rate_data.expiration_date"
                      },
                      "Subject": {
                        "Role": "rate_data"
                      }
                    },
                    "ID": "rate_data_have_expiration_dates",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "rate_data": {
                    "Target": {
                      "Entity": "rate_data"
                    }
                  },
                  "rate_data.expiration_date": {
                    "Target": {
                      "Entity": "rate_data.expiration_date"
                    }
                  }
                },
                "State": "Generated"
              },
              "rate_data_has_expiration_quarter": {
                "Binding": {
                  "ConceptualEntity": "Rate_Data"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "rate_data.expiration_quarter"
                      },
                      "Subject": {
                        "Role": "rate_data"
                      }
                    },
                    "ID": "rate_data_have_expiration_quarters",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "rate_data": {
                    "Target": {
                      "Entity": "rate_data"
                    }
                  },
                  "rate_data.expiration_quarter": {
                    "Target": {
                      "Entity": "rate_data.expiration_quarter"
                    }
                  }
                },
                "State": "Generated"
              },
              "rate_data_has_metrics_iqrr": {
                "Binding": {
                  "ConceptualEntity": "Rate_Data"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "metrics.iqrr"
                      },
                      "Subject": {
                        "Role": "rate_data"
                      }
                    },
                    "ID": "rate_data_have_iqrr",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "metrics.iqrr": {
                    "Target": {
                      "Entity": "metrics.iqrr"
                    }
                  },
                  "rate_data": {
                    "Target": {
                      "Entity": "rate_data"
                    }
                  }
                },
                "State": "Generated"
              },
              "rate_data_has_metrics_renewed_contracts": {
                "Binding": {
                  "ConceptualEntity": "Rate_Data"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "metrics.renewed_contracts"
                      },
                      "Subject": {
                        "Role": "rate_data"
                      }
                    },
                    "ID": "rate_data_have_total_renewed_contracts",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "metrics.renewed_contracts": {
                    "Target": {
                      "Entity": "metrics.renewed_contracts"
                    }
                  },
                  "rate_data": {
                    "Target": {
                      "Entity": "rate_data"
                    }
                  }
                },
                "State": "Generated"
              },
              "rate_data_has_metrics_total_expiring_contracts": {
                "Binding": {
                  "ConceptualEntity": "Rate_Data"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "metrics.total_expiring_contracts"
                      },
                      "Subject": {
                        "Role": "rate_data"
                      }
                    },
                    "ID": "rate_data_have_total_expiring_contracts",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "metrics.total_expiring_contracts": {
                    "Target": {
                      "Entity": "metrics.total_expiring_contracts"
                    }
                  },
                  "rate_data": {
                    "Target": {
                      "Entity": "rate_data"
                    }
                  }
                },
                "State": "Generated"
              },
              "rate_data_has_new_contract_amount": {
                "Binding": {
                  "ConceptualEntity": "Rate_Data"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "rate_data.new_contract_amount"
                      },
                      "Subject": {
                        "Role": "rate_data"
                      }
                    },
                    "ID": "rate_data_have_new_contract_amounts",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "Adjective": {
                      "Adjectives": [
                        {
                          "expensive": {
                            "State": "Generated"
                          }
                        }
                      ],
                      "Antonyms": [
                        {
                          "cheap": {
                            "State": "Generated"
                          }
                        }
                      ],
                      "Measurement": {
                        "Role": "rate_data.new_contract_amount"
                      },
                      "Subject": {
                        "Role": "rate_data"
                      }
                    },
                    "ID": "new_contract_amount_indicates_how_expensive_rate_data_are",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "rate_data": {
                    "Target": {
                      "Entity": "rate_data"
                    }
                  },
                  "rate_data.new_contract_amount": {
                    "Target": {
                      "Entity": "rate_data.new_contract_amount"
                    }
                  }
                },
                "State": "Generated"
              },
              "rate_data_has_new_contract_bucket": {
                "Binding": {
                  "ConceptualEntity": "Rate_Data"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "rate_data.new_contract_bucket"
                      },
                      "Subject": {
                        "Role": "rate_data"
                      }
                    },
                    "ID": "rate_data_have_new_contract_buckets",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "rate_data": {
                    "Target": {
                      "Entity": "rate_data"
                    }
                  },
                  "rate_data.new_contract_bucket": {
                    "Target": {
                      "Entity": "rate_data.new_contract_bucket"
                    }
                  }
                },
                "State": "Generated"
              },
              "rate_data_has_partner": {
                "Binding": {
                  "ConceptualEntity": "Rate_Data"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "rate_data.partner"
                      },
                      "Subject": {
                        "Role": "rate_data"
                      }
                    },
                    "ID": "rate_data_have_partners",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "rate_data": {
                    "Target": {
                      "Entity": "rate_data"
                    }
                  },
                  "rate_data.partner": {
                    "Target": {
                      "Entity": "rate_data.partner"
                    }
                  }
                },
                "State": "Generated"
              },
              "rate_data_has_previous_contract_amount": {
                "Binding": {
                  "ConceptualEntity": "Rate_Data"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "rate_data.previous_contract_amount"
                      },
                      "Subject": {
                        "Role": "rate_data"
                      }
                    },
                    "ID": "rate_data_have_previous_contract_amounts",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "Adjective": {
                      "Adjectives": [
                        {
                          "expensive": {
                            "State": "Generated"
                          }
                        }
                      ],
                      "Antonyms": [
                        {
                          "cheap": {
                            "State": "Generated"
                          }
                        }
                      ],
                      "Measurement": {
                        "Role": "rate_data.previous_contract_amount"
                      },
                      "Subject": {
                        "Role": "rate_data"
                      }
                    },
                    "ID": "previous_contract_amount_indicates_how_expensive_rate_data_are",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "rate_data": {
                    "Target": {
                      "Entity": "rate_data"
                    }
                  },
                  "rate_data.previous_contract_amount": {
                    "Target": {
                      "Entity": "rate_data.previous_contract_amount"
                    }
                  }
                },
                "State": "Generated"
              },
              "rate_data_has_previous_contract_bucket": {
                "Binding": {
                  "ConceptualEntity": "Rate_Data"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "rate_data.previous_contract_bucket"
                      },
                      "Subject": {
                        "Role": "rate_data"
                      }
                    },
                    "ID": "rate_data_have_previous_contract_buckets",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "rate_data": {
                    "Target": {
                      "Entity": "rate_data"
                    }
                  },
                  "rate_data.previous_contract_bucket": {
                    "Target": {
                      "Entity": "rate_data.previous_contract_bucket"
                    }
                  }
                },
                "State": "Generated"
              },
              "rate_data_has_region": {
                "Binding": {
                  "ConceptualEntity": "Rate_Data"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "rate_data.region"
                      },
                      "Subject": {
                        "Role": "rate_data"
                      }
                    },
                    "ID": "rate_data_have_regions",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "rate_data": {
                    "Target": {
                      "Entity": "rate_data"
                    }
                  },
                  "rate_data.region": {
                    "Target": {
                      "Entity": "rate_data.region"
                    }
                  }
                },
                "State": "Generated"
              },
              "rate_data_has_renewal_date": {
                "Binding": {
                  "ConceptualEntity": "Rate_Data"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "rate_data.renewal_date"
                      },
                      "Subject": {
                        "Role": "rate_data"
                      }
                    },
                    "ID": "rate_data_have_renewal_dates",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "rate_data": {
                    "Target": {
                      "Entity": "rate_data"
                    }
                  },
                  "rate_data.renewal_date": {
                    "Target": {
                      "Entity": "rate_data.renewal_date"
                    }
                  }
                },
                "State": "Generated"
              },
              "rate_data_has_renewal_quarter": {
                "Binding": {
                  "ConceptualEntity": "Rate_Data"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "rate_data.renewal_quarter"
                      },
                      "Subject": {
                        "Role": "rate_data"
                      }
                    },
                    "ID": "rate_data_have_renewal_quarters",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "rate_data": {
                    "Target": {
                      "Entity": "rate_data"
                    }
                  },
                  "rate_data.renewal_quarter": {
                    "Target": {
                      "Entity": "rate_data.renewal_quarter"
                    }
                  }
                },
                "State": "Generated"
              },
              "rate_data_has_sales_representative": {
                "Binding": {
                  "ConceptualEntity": "Rate_Data"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "rate_data.sales_representative"
                      },
                      "Subject": {
                        "Role": "rate_data"
                      }
                    },
                    "ID": "rate_data_have_sales_representatives",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "rate_data": {
                    "Target": {
                      "Entity": "rate_data"
                    }
                  },
                  "rate_data.sales_representative": {
                    "Target": {
                      "Entity": "rate_data.sales_representative"
                    }
                  }
                },
                "State": "Generated"
              },
              "rate_data_in_region": {
                "Binding": {
                  "ConceptualEntity": "Rate_Data"
                },
                "Phrasings": [
                  {
                    "ID": "rate_data_are_in_regions",
                    "Preposition": {
                      "Object": {
                        "Role": "rate_data.region"
                      },
                      "Prepositions": [
                        {
                          "in": {
                            "State": "Generated"
                          }
                        }
                      ],
                      "Subject": {
                        "Role": "rate_data"
                      }
                    },
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "rate_data": {
                    "Target": {
                      "Entity": "rate_data"
                    }
                  },
                  "rate_data.region": {
                    "Target": {
                      "Entity": "rate_data.region"
                    }
                  }
                },
                "SemanticSlots": {
                  "Where": {
                    "Role": "rate_data.region"
                  }
                },
                "State": "Generated"
              },
              "rate_data_renewal_date_has_variation_date_hierarchy": {
                "Binding": {
                  "ConceptualEntity": "Rate_Data"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "rate_data.renewal_date.variation.date_hierarchy"
                      },
                      "Subject": {
                        "Role": "rate_data.renewal_date"
                      }
                    },
                    "ID": "renewal_dates_have_renewal_date_hierarchies",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "rate_data.renewal_date": {
                    "Target": {
                      "Entity": "rate_data.renewal_date"
                    }
                  },
                  "rate_data.renewal_date.variation.date_hierarchy": {
                    "Target": {
                      "Entity": "rate_data.renewal_date.variation.date_hierarchy"
                    }
                  }
                },
                "State": "Generated"
              },
              "rate_data_renewal_date_variation_date_hierarchy_has_day": {
                "Binding": {
                  "ConceptualEntity": "Rate_Data"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "rate_data.renewal_date.variation.date_hierarchy.day"
                      },
                      "Subject": {
                        "Role": "rate_data.renewal_date.variation.date_hierarchy"
                      }
                    },
                    "ID": "renewal_date_hierarchies_have_renewal_days",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "rate_data.renewal_date.variation.date_hierarchy": {
                    "Target": {
                      "Entity": "rate_data.renewal_date.variation.date_hierarchy"
                    }
                  },
                  "rate_data.renewal_date.variation.date_hierarchy.day": {
                    "Target": {
                      "Entity": "rate_data.renewal_date.variation.date_hierarchy.day"
                    }
                  }
                },
                "State": "Generated"
              },
              "rate_data_renewal_date_variation_date_hierarchy_has_month": {
                "Binding": {
                  "ConceptualEntity": "Rate_Data"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "rate_data.renewal_date.variation.date_hierarchy.month"
                      },
                      "Subject": {
                        "Role": "rate_data.renewal_date.variation.date_hierarchy"
                      }
                    },
                    "ID": "renewal_date_hierarchies_have_renewal_months",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "rate_data.renewal_date.variation.date_hierarchy": {
                    "Target": {
                      "Entity": "rate_data.renewal_date.variation.date_hierarchy"
                    }
                  },
                  "rate_data.renewal_date.variation.date_hierarchy.month": {
                    "Target": {
                      "Entity": "rate_data.renewal_date.variation.date_hierarchy.month"
                    }
                  }
                },
                "State": "Generated"
              },
              "rate_data_renewal_date_variation_date_hierarchy_has_quarter": {
                "Binding": {
                  "ConceptualEntity": "Rate_Data"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "rate_data.renewal_date.variation.date_hierarchy.quarter"
                      },
                      "Subject": {
                        "Role": "rate_data.renewal_date.variation.date_hierarchy"
                      }
                    },
                    "ID": "renewal_date_hierarchies_have_renewal_quarters",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "rate_data.renewal_date.variation.date_hierarchy": {
                    "Target": {
                      "Entity": "rate_data.renewal_date.variation.date_hierarchy"
                    }
                  },
                  "rate_data.renewal_date.variation.date_hierarchy.quarter": {
                    "Target": {
                      "Entity": "rate_data.renewal_date.variation.date_hierarchy.quarter"
                    }
                  }
                },
                "State": "Generated"
              },
              "rate_data_renewal_date_variation_date_hierarchy_has_year": {
                "Binding": {
                  "ConceptualEntity": "Rate_Data"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "rate_data.renewal_date.variation.date_hierarchy.year"
                      },
                      "Subject": {
                        "Role": "rate_data.renewal_date.variation.date_hierarchy"
                      }
                    },
                    "ID": "renewal_date_hierarchies_have_renewal_years",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "rate_data.renewal_date.variation.date_hierarchy": {
                    "Target": {
                      "Entity": "rate_data.renewal_date.variation.date_hierarchy"
                    }
                  },
                  "rate_data.renewal_date.variation.date_hierarchy.year": {
                    "Target": {
                      "Entity": "rate_data.renewal_date.variation.date_hierarchy.year"
                    }
                  }
                },
                "State": "Generated"
              }
            },
            "Version": "3.5.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "Errors in Rate_Data",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "Source = Rate_Data,",
          "  #\"Detected Type Mismatches\" = let",
          "    tableWithOnlyPrimitiveTypes = Table.SelectColumns(Source, Table.ColumnsOfType(Source, {type nullable number, type nullable text, type nullable logical, type nullable date, type nullable datetime, type nullable datetimezone, type nullable time, type nullable duration})),",
          "    recordTypeFields = Type.RecordFields(Type.TableRow(Value.Type(tableWithOnlyPrimitiveTypes))),",
          "    fieldNames = Record.FieldNames(recordTypeFields),",
          "    fieldTypes = List.Transform(Record.ToList(recordTypeFields), each [Type]),",
          "    pairs = List.Transform(List.Positions(fieldNames), (i) => {fieldNames{i}, (v) => if v = null or Value.Is(v, fieldTypes{i}) then v else error [Message = \"The type of the value does not match the type of the column.\", Detail = v], fieldTypes{i}})",
          "in",
          "    Table.TransformColumns(Source, pairs),",
          "  #\"Added Index\" = Table.AddIndexColumn(#\"Detected Type Mismatches\", \"Row Number\" ,1),",
          "  #\"Kept Errors\" = Table.SelectRowsWithErrors(#\"Added Index\", {\"Contract Number\", \"Account Name\", \"Sales Representative\", \"Contract Status\", \"Expiration Date\", \"Expiration Quarter\", \"Direct/Channel\", \"Partner\", \"Previous Contract Amount\", \"Previous Contract Bucket\", \"New Contract Amount\", \"New Contract Bucket\", \"Renewal Date\", \"Renewal Quarter\", \"Region\"}),",
          "  #\"Reordered Columns\" = Table.ReorderColumns(#\"Kept Errors\", {\"Row Number\", \"Contract Number\", \"Account Name\", \"Sales Representative\", \"Contract Status\", \"Expiration Date\", \"Expiration Quarter\", \"Direct/Channel\", \"Partner\", \"Previous Contract Amount\", \"Previous Contract Bucket\", \"New Contract Amount\", \"New Contract Bucket\", \"Renewal Date\", \"Renewal Quarter\", \"Region\"})",
          "in",
          "  #\"Reordered Columns\""
        ],
        "kind": "m",
        "lineageTag": "f995653e-501a-42de-b316-b8840d16e8d4",
        "queryGroup": "Query Errors - 10 7 2024   14:06:50"
      }
    ],
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "description": "Errors in queries that were loaded on 10.7.2024 . 14:06:50.",
        "folder": "Query Errors - 10 7 2024   14:06:50"
      }
    ],
    "relationships": [
      {
        "name": "3495920d-7a6e-4c91-a43c-24c351ba2887",
        "fromColumn": "Expiration Date",
        "fromTable": "Rate_Data",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_7b964b63-8a17-4bab-8d73-8acb8477067d"
      },
      {
        "name": "740061c5-866f-4311-a20f-db38c9a59d14",
        "fromColumn": "Renewal Date",
        "fromTable": "Rate_Data",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_b7271bed-2c69-49f9-b9e1-e822c0821d18"
      }
    ],
    "sourceQueryCulture": "bg-BG",
    "tables": [
      {
        "name": "DateTableTemplate_852dec62-64e3-491a-9cf4-40afa7bdea6b",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "7d431268-2b7e-4698-b73a-c0c4f42a3fb4",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "f2b5738e-2325-4c86-a197-f6074833ca98",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "995deee8-3215-46e0-a95f-2d53b53b3e40",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "74a1445c-bed3-4389-9288-07fc9b78cea0",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "13f11aa3-605f-4372-880e-fecb74f83c18",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "eb083c03-59cd-4ccf-9409-088b2f48512c",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "e9642dc8-5327-422d-9244-8a8ee07205d9",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "a952def0-b59f-4fe3-912a-cd31d7244c30",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "fd778612-2aab-4fb0-8ccf-25ded2b67983",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "74aa490d-0133-430b-bc34-2f960ac2d559",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "b6e53a41-6eae-4ea2-a6a6-5a43f6a79d13",
                "ordinal": 3
              }
            ],
            "lineageTag": "8ecd707f-d51d-4bb3-b2a5-baa13296eeef"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "b08b2b4d-c312-4e89-86e0-9f570c955090",
        "partitions": [
          {
            "name": "DateTableTemplate_852dec62-64e3-491a-9cf4-40afa7bdea6b",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Metrics",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "lineageTag": "656f6214-d49f-4a67-8a82-29c1766c997c",
        "measures": [
          {
            "name": "TotalExpiringContracts",
            "expression": [
              "",
              "SUM(Rate_Data[Previous Contract Amount])"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "43668414-fb69-4626-b246-c666ceccd258"
          },
          {
            "name": "TotalRenewedContracts",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM(Rate_Data[Previous Contract Amount]),",
              "    Rate_Data[Contract Status] = \"Renewed\"",
              ")"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "6d2fcced-9cb1-4e06-8cc6-41f8cf564b69"
          },
          {
            "name": "IQRR",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "DIVIDE([TotalRenewedContracts], [TotalExpiringContracts])"
            ],
            "lineageTag": "6d281890-da1b-4ace-a2c4-5cfd85b3374c"
          },
          {
            "name": "MinIQRR",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "0",
            "lineageTag": "71279a05-f887-4555-94ca-4ccbea0650a4"
          },
          {
            "name": "MaxIQRR",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "1",
              ""
            ],
            "lineageTag": "1c30930f-64f4-4dfc-bf1f-cf07e01763f4"
          }
        ],
        "partitions": [
          {
            "name": "Metrics",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Rate_Data",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Contract Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "820a6bd6-6496-4e3a-996c-5860aabcc38d",
            "sourceColumn": "Contract Number",
            "summarizeBy": "sum"
          },
          {
            "name": "Account Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6920cf1d-596e-4493-8daf-68df315e20ac",
            "sourceColumn": "Account Name",
            "summarizeBy": "none"
          },
          {
            "name": "Sales Representative",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a5008d68-b3d8-48d6-9bc7-2e34824c3691",
            "sourceColumn": "Sales Representative",
            "summarizeBy": "none"
          },
          {
            "name": "Contract Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b7948cdf-f693-4133-ba69-a1c48202ea79",
            "sourceColumn": "Contract Status",
            "summarizeBy": "none"
          },
          {
            "name": "Expiration Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd/mm/yyyy",
            "lineageTag": "a7b59628-78c7-49df-b3a5-25d396620baa",
            "sourceColumn": "Expiration Date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_7b964b63-8a17-4bab-8d73-8acb8477067d"
                },
                "isDefault": true,
                "relationship": "3495920d-7a6e-4c91-a43c-24c351ba2887"
              }
            ]
          },
          {
            "name": "Expiration Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f210618e-936f-4243-a01a-a9c337248473",
            "sourceColumn": "Expiration Quarter",
            "summarizeBy": "none"
          },
          {
            "name": "Direct/Channel",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7d283f69-0b28-4d09-9b16-2a4b2f7f1443",
            "sourceColumn": "Direct/Channel",
            "summarizeBy": "none"
          },
          {
            "name": "Partner",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c2c84ac2-14fc-4fba-b038-3d153c9170ed",
            "sourceColumn": "Partner",
            "summarizeBy": "none"
          },
          {
            "name": "Previous Contract Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "e80a7b71-7cdd-4f8e-8b2e-71d4a83e7519",
            "sourceColumn": "Previous Contract Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Previous Contract Bucket",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "70eb7308-0f58-4253-a681-249ef13f3036",
            "sourceColumn": "Previous Contract Bucket",
            "summarizeBy": "none"
          },
          {
            "name": "New Contract Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "b805974c-bc4a-4577-ac0e-f2ba98586feb",
            "sourceColumn": "New Contract Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "New Contract Bucket",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b4e4c4ed-d7da-4d49-b29d-51cb9a4197e9",
            "sourceColumn": "New Contract Bucket",
            "summarizeBy": "none"
          },
          {
            "name": "Renewal Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd/mm/yyyy",
            "lineageTag": "2898e711-0db8-423b-83a0-8bb3638c507f",
            "sourceColumn": "Renewal Date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_b7271bed-2c69-49f9-b9e1-e822c0821d18"
                },
                "isDefault": true,
                "relationship": "740061c5-866f-4311-a20f-db38c9a59d14"
              }
            ]
          },
          {
            "name": "Renewal Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f77d063a-0ca1-442f-a1c5-7e31b3a98cdd",
            "sourceColumn": "Renewal Quarter",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d2d6dfbe-7a89-4a0e-acef-01c746a10afa",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "c36b4a5e-ae11-450a-bcbf-5328b9380c01",
        "partitions": [
          {
            "name": "Rate_Data",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\Nedko\\Desktop\\Work\\Power BI\\BI Interview Business Case Study 2024\\BI Business Case Study Task\\BI Interview Business Case Study 2024.xlsb\"), null, true),",
                "    Rate_Data1 = Source{[Name=\"Rate_Data\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Rate_Data1, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Contract Number\", Int64.Type}, {\"Account Name\", type text}, {\"Sales Representative\", type text}, {\"Contract Status\", type text}, {\"Expiration Date\", type text}, {\"Expiration Quarter\", type text}, {\"Direct/Channel\", type text}, {\"Partner\", type text}, {\"Previous Contract Amount\", type text}, {\"Previous Contract Bucket\", type text}, {\"New Contract Amount\", type text}, {\"New Contract Bucket\", type text}, {\"Renewal Date\", type text}, {\"Renewal Quarter\", type text}, {\"Region\", type text}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Changed Type\",\"'.'\",\"\",Replacer.ReplaceText,{\"Expiration Date\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",\"'.'\",\"\",Replacer.ReplaceText,{\"Renewal Date\"}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Replaced Value1\",{{\"Expiration Date\", type date}, {\"Renewal Date\", type date}}),",
                "    #\"Replaced Value2\" = Table.ReplaceValue(#\"Changed Type1\",\"$\",\"\",Replacer.ReplaceText,{\"Previous Contract Amount\"}),",
                "    #\"Replaced Value3\" = Table.ReplaceValue(#\"Replaced Value2\",\"$\",\"\",Replacer.ReplaceText,{\"New Contract Amount\"}),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Replaced Value3\",{{\"Previous Contract Amount\", Currency.Type}, {\"New Contract Amount\", Currency.Type}})",
                "in",
                "    #\"Changed Type2\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_7b964b63-8a17-4bab-8d73-8acb8477067d",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "c198cce9-9eea-4b9b-9939-3d1a3d72b2fb",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "d89f5263-ba6f-4da0-bd61-c21d99e22a91",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "3d3838d2-2214-47c3-a061-17a9cafa5f78",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "a1a12af5-4338-4eb0-bbff-8bdcc901f8dc",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "d1207be3-4839-4db8-8ddf-cb51313c423b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "f42f5094-242b-432a-97d2-307ba4c42030",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "723fc3be-48b7-4b3f-b895-bf7c5a96a81e",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "e87417cb-0c35-4032-b539-0e434886cc3f",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "785c1d10-027d-4b9f-8fef-ac9433982556",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "b7372c3b-2f68-45e9-bba5-db43b8abe380",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "384c8746-2e01-4aef-bcb1-ca5f16f051f6",
                "ordinal": 3
              }
            ],
            "lineageTag": "3d954c49-912b-4faf-8c97-87068d15d990"
          }
        ],
        "isHidden": true,
        "lineageTag": "1f4c7da3-87ae-4f42-bd1c-a1d8b5502fb3",
        "partitions": [
          {
            "name": "LocalDateTable_7b964b63-8a17-4bab-8d73-8acb8477067d",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Rate_Data'[Expiration Date])), 1, 1), Date(Year(MAX('Rate_Data'[Expiration Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_b7271bed-2c69-49f9-b9e1-e822c0821d18",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "3b87f4e2-6dcd-48ca-8037-94b8a30c4e43",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "27b56dbf-3e99-485a-b059-d14aad567ea9",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "3a8f64e9-a108-4987-ba79-bdddee3fbe67",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "9fb33d42-ced3-4857-8ece-ba238a4512de",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "977aa7cf-bbb1-44a6-97de-bbc7a03e373a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "af03079b-604c-4f2d-b970-99d9953663ce",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "2ad26572-516f-497b-9507-86098d89d1c9",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "45f8bf2b-e079-4bc9-ad78-81ad6de9a9fd",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "7cb5ec42-e697-485e-ac2c-1b8566a2cbdf",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "581c4fca-c77b-44b4-b474-9ef670407d27",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "deff73e5-cea4-48fe-b30d-2278c4bcb324",
                "ordinal": 3
              }
            ],
            "lineageTag": "8d7c7154-9f0b-492b-8f7f-bfb2e28686ca"
          }
        ],
        "isHidden": true,
        "lineageTag": "b3eb868a-cc4e-46b3-b58b-10a9b458c71a",
        "partitions": [
          {
            "name": "LocalDateTable_b7271bed-2c69-49f9-b9e1-e822c0821d18",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Rate_Data'[Renewal Date])), 1, 1), Date(Year(MAX('Rate_Data'[Renewal Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}