{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Inventory Levels (week 8 close)\",\"Sales Forecast (week 9+)\",\"Metrics\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.130.930.0 (24.06)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "ba7b4d3c-516f-f2eb-b359-b8fb072b5255",
        "fromColumn": "SKU Short",
        "fromTable": "Sales Forecast (week 9+)",
        "toColumn": "SKU Short",
        "toTable": "Inventory Levels (week 8 close)"
      }
    ],
    "sourceQueryCulture": "bg-BG",
    "tables": [
      {
        "name": "Inventory Levels (week 8 close)",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cbf8eba3-ae01-4737-8093-5489e9f7bc76",
            "sourceColumn": "Country",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f175d414-b13e-42b5-8d80-52ac64df71d7",
            "sourceColumn": "Fiscal year",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal week / year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8bf32cb3-7b13-40d4-8f46-41cbfd910717",
            "sourceColumn": "Fiscal week / year",
            "summarizeBy": "none"
          },
          {
            "name": "Legacy Material number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3058f9e8-7535-45dc-9511-af2d2ce5f63a",
            "sourceColumn": "Legacy Material number",
            "summarizeBy": "none"
          },
          {
            "name": "SKU Short",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2e621fd1-895a-4c25-a10e-ace28d0139f4",
            "sourceColumn": "SKU Short",
            "summarizeBy": "none"
          },
          {
            "name": "Material",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "18ccc1b3-978c-49a1-b1e2-a681f7826f8a",
            "sourceColumn": "Material",
            "summarizeBy": "none"
          },
          {
            "name": "Material description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5a8612e5-5fe7-41db-9474-72364540f832",
            "sourceColumn": "Material description",
            "summarizeBy": "none"
          },
          {
            "name": "#pallets",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0370a8b1-d708-494b-b7a4-0891d66d940e",
            "sourceColumn": "#pallets",
            "summarizeBy": "none"
          },
          {
            "name": "Unit cases (UC)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c0d97586-90b4-4f5e-a9c8-f4b4952efc12",
            "sourceColumn": "Unit cases (UC)",
            "summarizeBy": "none"
          },
          {
            "name": "EUR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "\"€\"\\ #,0.00;-\"€\"\\ #,0.00;\"€\"\\ #,0.00",
            "lineageTag": "b14d17fd-8284-45de-929f-2f3a502a94bd",
            "sourceColumn": "EUR",
            "summarizeBy": "none"
          },
          {
            "name": "Country Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "29013ce1-84c9-4692-8605-51fcfa248e7e",
            "sourceColumn": "Country Name",
            "summarizeBy": "none"
          },
          {
            "name": "Week Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "bd450e07-f040-430e-b0ae-594dedeab407",
            "sortByColumn": "Fiscal week / year",
            "sourceColumn": "Week Name",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "03b4d556-db2f-4b62-af4e-fc96aca77ba6",
        "partitions": [
          {
            "name": "Inventory Levels (week 8 close)",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\Nedko\\Desktop\\Work\\Power BI\\SC Case Study\\SC Case Study Task\\SC Case Study 1.xlsx\"), null, true),",
                "    #\"Inventory Levels (week 8 close)_Sheet\" = Source{[Item=\"Inventory Levels (week 8 close)\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Inventory Levels (week 8 close)_Sheet\", [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"\", type text}, {\"_1\", type text}, {\"_2\", type text}, {\"_3\", type text}, {\"Column5\", type text}, {\"_4\", type text}, {\"_5\", type text}, {\"Quantity Total Stock\", type any}, {\"Quantity Total Stock_6\", type any}, {\"ValStockValue\", type any}}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Changed Type\", each ([#\"\"] <> null)),",
                "    #\"Promoted Headers1\" = Table.PromoteHeaders(#\"Filtered Rows\", [PromoteAllScalars=true]),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Promoted Headers1\",{{\"Country\", type text}, {\"Fiscal year\", Int64.Type}, {\"Fiscal week / year\", type text}, {\"Legacy Material number\", type text}, {\"SKU Short\", Int64.Type}, {\"Material\", Int64.Type}, {\"Material description\", type text}, {\"#pallets\", Int64.Type}, {\"Unit cases (UC)\", Int64.Type}, {\"EUR\", type number}}),",
                "    #\"Duplicated Column\" = Table.DuplicateColumn(#\"Changed Type1\", \"Country\", \"Country - Copy\"),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Duplicated Column\",\"GB\",\"United Kingdom of Great Britain and Northern Ireland\",Replacer.ReplaceText,{\"Country - Copy\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Replaced Value\",{{\"Country - Copy\", \"Country Name\"}}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Renamed Columns\",\"United Kingdom of Great Britain and Northern Ireland\",\"Great Britain\",Replacer.ReplaceText,{\"Country Name\"}),",
                "    #\"Duplicated Column1\" = Table.DuplicateColumn(#\"Replaced Value1\", \"Fiscal week / year\", \"Fiscal week / year - Copy\"),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Duplicated Column1\",{\"Country\", \"Fiscal year\", \"Fiscal week / year\", \"Fiscal week / year - Copy\", \"Legacy Material number\", \"SKU Short\", \"Material\", \"Material description\", \"#pallets\", \"Unit cases (UC)\", \"EUR\", \"Country Name\"}),",
                "    #\"Replaced Value2\" = Table.ReplaceValue(#\"Reordered Columns\",\"008.2023\",\"Week 8\",Replacer.ReplaceText,{\"Fiscal week / year - Copy\"}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Replaced Value2\",{{\"Fiscal week / year - Copy\", \"Fiscal week Name\"}}),",
                "    #\"Reordered Columns1\" = Table.ReorderColumns(#\"Renamed Columns1\",{\"Country\", \"Country Name\", \"Fiscal year\", \"Fiscal week / year\", \"Fiscal week Name\", \"Legacy Material number\", \"SKU Short\", \"Material\", \"Material description\", \"#pallets\", \"Unit cases (UC)\", \"EUR\"}),",
                "    #\"Renamed Columns2\" = Table.RenameColumns(#\"Reordered Columns1\",{{\"Fiscal week Name\", \"Week Name\"}})",
                "in",
                "    #\"Renamed Columns2\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_af285a7b-b9e2-4cbc-98ba-a29c0640b4c8",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "53e04767-3c04-43a5-a003-6dd62864c4a7",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "44ba6c6d-c873-4076-a92a-f64ad97bac13",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "2463e7f2-2bac-4d46-b982-b6734f2872a6",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "561b1eea-26eb-425e-9695-1b799cbda7b4",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "a6cbbee3-924a-4dad-b62f-106d74b7029c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "533bced8-5038-4643-82e8-dfc8a52e5837",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "9d6b06d5-5fa2-48e2-a90e-b4e10075dec5",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "8e49ba76-2be2-4b3e-bfe9-778d1c48ef61",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "1084d9c3-91ee-44ad-a408-4b174ae8841e",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "e54d1a4f-5bfb-4687-91d6-fa54aa27a743",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "1a8e88a6-cef9-411c-a1f0-d15193a6ba4b",
                "ordinal": 3
              }
            ],
            "lineageTag": "03ca7720-989d-4a48-95ac-3abb7f8928f4"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "5d40becb-81b7-463d-9c7a-073fb1af0e25",
        "partitions": [
          {
            "name": "DateTableTemplate_af285a7b-b9e2-4cbc-98ba-a29c0640b4c8",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Sales Forecast (week 9+)",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "SKU Short",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "caa200b6-7be0-45d2-88d1-82b60524668f",
            "sourceColumn": "SKU Short",
            "summarizeBy": "none"
          },
          {
            "name": "Material description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "64e9edd0-fee9-4890-9a62-89838249a213",
            "sourceColumn": "Material description",
            "summarizeBy": "none"
          },
          {
            "name": "Week.year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a07eb47d-8aaa-4775-b026-13bc59d9fb10",
            "sourceColumn": "Week.year",
            "summarizeBy": "none"
          },
          {
            "name": "Demand Planning Forecast (unit cases)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "15494f70-84d5-439f-89d4-ab5899f7433e",
            "sourceColumn": "Demand Planning Forecast (unit cases)",
            "summarizeBy": "sum"
          },
          {
            "name": "Week Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "4cb2daeb-492f-4884-9497-aca1e42cd406",
            "sortByColumn": "Week.year",
            "sourceColumn": "Week Name",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "73b4e2fb-3b69-46fc-95ab-6a696f125424",
        "partitions": [
          {
            "name": "Sales Forecast (week 9+)",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\Nedko\\Desktop\\Work\\Power BI\\SC Case Study\\SC Case Study Task\\SC Case Study 1.xlsx\"), null, true),",
                "    #\"Sales forecast  (week 9+)_Sheet\" = Source{[Item=\"Sales forecast  (week 9+)\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Sales forecast  (week 9+)_Sheet\", [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"SKU Short\", Int64.Type}, {\"Material description\", type text}, {\"Week.year\", type text}, {\"Demand Planning Forecast (unit cases)\", Int64.Type}}),",
                "    #\"Duplicated Column\" = Table.DuplicateColumn(#\"Changed Type\", \"Week.year\", \"Week.year - Copy\"),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Duplicated Column\",{{\"Week.year - Copy\", \"Week Name\"}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Renamed Columns\",\"009.2023\",\"Week 9\",Replacer.ReplaceText,{\"Week Name\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",\"010.2023\",\"Week 10\",Replacer.ReplaceText,{\"Week Name\"}),",
                "    #\"Replaced Value2\" = Table.ReplaceValue(#\"Replaced Value1\",\"011.2023\",\"Week 11\",Replacer.ReplaceText,{\"Week Name\"}),",
                "    #\"Replaced Value3\" = Table.ReplaceValue(#\"Replaced Value2\",\"012.2023\",\"Week 12\",Replacer.ReplaceText,{\"Week Name\"}),",
                "    #\"Replaced Value4\" = Table.ReplaceValue(#\"Replaced Value3\",\"013.2023\",\"Week 13\",Replacer.ReplaceText,{\"Week Name\"}),",
                "    #\"Replaced Value5\" = Table.ReplaceValue(#\"Replaced Value4\",\"014.2023\",\"Week 14\",Replacer.ReplaceText,{\"Week Name\"}),",
                "    #\"Replaced Value6\" = Table.ReplaceValue(#\"Replaced Value5\",\"015.2023\",\"Week 15\",Replacer.ReplaceText,{\"Week Name\"}),",
                "    #\"Replaced Value7\" = Table.ReplaceValue(#\"Replaced Value6\",\"016.2023\",\"Week 16\",Replacer.ReplaceText,{\"Week Name\"}),",
                "    #\"Replaced Value8\" = Table.ReplaceValue(#\"Replaced Value7\",\"017.2023\",\"Week 17\",Replacer.ReplaceText,{\"Week Name\"}),",
                "    #\"Replaced Value9\" = Table.ReplaceValue(#\"Replaced Value8\",\"018.2023\",\"Week 18\",Replacer.ReplaceText,{\"Week Name\"}),",
                "    #\"Replaced Value10\" = Table.ReplaceValue(#\"Replaced Value9\",\"019.2023\",\"Week 19\",Replacer.ReplaceText,{\"Week Name\"}),",
                "    #\"Replaced Value11\" = Table.ReplaceValue(#\"Replaced Value10\",\"020.2023\",\"Week 20\",Replacer.ReplaceText,{\"Week Name\"}),",
                "    #\"Replaced Value12\" = Table.ReplaceValue(#\"Replaced Value11\",\"021.2023\",\"Week 21\",Replacer.ReplaceText,{\"Week Name\"}),",
                "    #\"Replaced Value13\" = Table.ReplaceValue(#\"Replaced Value12\",\"Week 9 \",\"Week 9\",Replacer.ReplaceText,{\"Week Name\"})",
                "in",
                "    #\"Replaced Value13\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Metrics",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "lineageTag": "ed2ea557-fcb5-458e-a4ec-1b4b286f7da2",
        "measures": [
          {
            "name": "Total Unit Cases (Inventory)",
            "expression": [
              "CALCULATE(",
              "    SUM('Inventory Levels (week 8 close)'[Unit cases (UC)])",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "fbf04ece-bffb-432a-a39f-5c54c5435aea"
          },
          {
            "name": "Total Unit Cases (Forecast)",
            "expression": [
              "CALCULATE(",
              "    SUM('Sales Forecast (week 9+)'[Demand Planning Forecast (unit cases)]),",
              "    ALL('Sales Forecast (week 9+)'[Demand Planning Forecast (unit cases)]))"
            ],
            "formatString": "0",
            "lineageTag": "15c927d9-fce7-4210-ac91-e8aeb15dd959"
          },
          {
            "name": "Total Product Cost",
            "expression": [
              "CALCULATE(",
              "    SUM('Inventory Levels (week 8 close)'[EUR]))"
            ],
            "formatString": "\"€\"\\ #,0.0;-\"€\"\\ #,0.0;\"€\"\\ #,0.0",
            "lineageTag": "89e96416-5c58-43cf-95f9-3f7014117b0a"
          },
          {
            "name": "Product Price per Unit (Inventory)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "DIVIDE([Total Product Cost],[Total Unit Cases (Inventory)])",
            "lineageTag": "e47646b4-434a-4cfd-8949-7460a5f35d76"
          },
          {
            "name": "Total Product Cost (Forecast)",
            "expression": "CALCULATE([Product Price per Unit (Inventory)] * [Total Unit Cases (Forecast)])",
            "formatString": "\"€\"\\ #,0.0;-\"€\"\\ #,0.0;\"€\"\\ #,0.0",
            "lineageTag": "93a56a87-c319-4737-8449-0cfc9c3082af"
          }
        ],
        "partitions": [
          {
            "name": "Metrics",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}